namespace Tecnologia
{
    partial class AbrirOrdemForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null) components.Dispose();
                if (BackgroundImage != null) BackgroundImage.Dispose();
                if (marcaSecundaria != null && marcaSecundaria.Image != null) marcaSecundaria.Image.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AbrirOrdemForm));
            this.tablelayoutpanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.marcaSecundaria = new System.Windows.Forms.PictureBox();
            this.tabcontrol3 = new System.Windows.Forms.TabControl();
            this.tabpage4 = new System.Windows.Forms.TabPage();
            this.panel5 = new System.Windows.Forms.Panel();
            this.flowlayoutpanel6 = new System.Windows.Forms.FlowLayoutPanel();
            this.label7 = new System.Windows.Forms.Label();
            this.flowlayoutpanel8 = new System.Windows.Forms.FlowLayoutPanel();
            this.panel9 = new System.Windows.Forms.Panel();
            this.lblCliente = new System.Windows.Forms.Label();
            this.cmbCliente = new System.Windows.Forms.ComboBox();
            this.panel10 = new System.Windows.Forms.Panel();
            this.lblAparelho = new System.Windows.Forms.Label();
            this.cmbAparelho = new System.Windows.Forms.ComboBox();
            this.label11 = new System.Windows.Forms.Label();
            this.flowlayoutpanel12 = new System.Windows.Forms.FlowLayoutPanel();
            this.panel13 = new System.Windows.Forms.Panel();
            this.lblProblema = new System.Windows.Forms.Label();
            this.txtProblema = new System.Windows.Forms.TextBox();
            this.panel14 = new System.Windows.Forms.Panel();
            this.lblPrevisao = new System.Windows.Forms.Label();
            this.dtPrevisao = new System.Windows.Forms.DateTimePicker();
            this.panel15 = new System.Windows.Forms.Panel();
            this.lblObservacoes = new System.Windows.Forms.Label();
            this.txtObservacoesFundo = new System.Windows.Forms.Panel();
            this.txtObservacoes = new System.Windows.Forms.TextBox();
            this.flowlayoutpanel16 = new System.Windows.Forms.FlowLayoutPanel();
            this.btnSalvar = new System.Windows.Forms.Button();
            this.SuspendLayout();
            this.tablelayoutpanel1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.marcaSecundaria)).BeginInit();
            this.tabcontrol3.SuspendLayout();
            this.tabpage4.SuspendLayout();
            this.panel5.SuspendLayout();
            this.flowlayoutpanel6.SuspendLayout();
            this.flowlayoutpanel8.SuspendLayout();
            this.panel9.SuspendLayout();
            this.panel10.SuspendLayout();
            this.flowlayoutpanel12.SuspendLayout();
            this.panel13.SuspendLayout();
            this.panel14.SuspendLayout();
            this.panel15.SuspendLayout();
            this.txtObservacoesFundo.SuspendLayout();
            this.flowlayoutpanel16.SuspendLayout();
            // AbrirOrdemForm
            this.Text = "Abrir ordem de serviço";
            this.AccessibleName = null;
            this.MinimumSize = new System.Drawing.Size(780, 520);
            this.MaximumSize = new System.Drawing.Size(0, 0);
            this.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Dock = (System.Windows.Forms.DockStyle)0;
            this.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.TabIndex = 0;
            this.TabStop = true;
            this.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.AutoScroll = true;
            this.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)3;
            this.ClientSize = new System.Drawing.Size(1060, 720);
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.Name = "AbrirOrdemForm";
            // tablelayoutpanel1
            this.tablelayoutpanel1.Text = "";
            this.tablelayoutpanel1.AccessibleName = null;
            this.tablelayoutpanel1.Location = new System.Drawing.Point(0, 0);
            this.tablelayoutpanel1.Size = new System.Drawing.Size(1028, 720);
            this.tablelayoutpanel1.MinimumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.MaximumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.tablelayoutpanel1.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.tablelayoutpanel1.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tablelayoutpanel1.Dock = (System.Windows.Forms.DockStyle)5;
            this.tablelayoutpanel1.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tablelayoutpanel1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tablelayoutpanel1.Padding = new System.Windows.Forms.Padding(16);
            this.tablelayoutpanel1.TabIndex = 0;
            this.tablelayoutpanel1.TabStop = false;
            this.tablelayoutpanel1.AutoSize = false;
            this.tablelayoutpanel1.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tablelayoutpanel1.AutoScroll = false;
            this.tablelayoutpanel1.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tablelayoutpanel1.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tablelayoutpanel1.RowCount = 2;
            this.tablelayoutpanel1.ColumnCount = 1;
            this.tablelayoutpanel1.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.tablelayoutpanel1.Name = "tablelayoutpanel1";
            this.tablelayoutpanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 100F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 64F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)2, 100F));
            // panel2
            this.panel2.Text = "";
            this.panel2.AccessibleName = null;
            this.panel2.Location = new System.Drawing.Point(25, 25);
            this.panel2.Size = new System.Drawing.Size(978, 72);
            this.panel2.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel2.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel2.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.panel2.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.panel2.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel2.Dock = (System.Windows.Forms.DockStyle)5;
            this.panel2.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel2.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.panel2.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel2.TabIndex = 0;
            this.panel2.TabStop = false;
            this.panel2.AutoSize = false;
            this.panel2.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel2.AutoScroll = false;
            this.panel2.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel2.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel2.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel2.Name = "panel2";
            // lblTitulo
            this.lblTitulo.Text = "Nova ordem de serviço";
            this.lblTitulo.AccessibleName = null;
            this.lblTitulo.Location = new System.Drawing.Point(0, 4);
            this.lblTitulo.Size = new System.Drawing.Size(728, 50);
            this.lblTitulo.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblTitulo.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 22F, (System.Drawing.FontStyle)1);
            this.lblTitulo.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblTitulo.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.lblTitulo.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblTitulo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblTitulo.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblTitulo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.TabStop = false;
            this.lblTitulo.AutoSize = false;
            this.lblTitulo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblTitulo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblTitulo.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblTitulo.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblTitulo.UseCompatibleTextRendering = false;
            this.lblTitulo.Name = "lblTitulo";
            // marcaSecundaria
            this.marcaSecundaria.Text = "";
            this.marcaSecundaria.AccessibleName = null;
            this.marcaSecundaria.Location = new System.Drawing.Point(758, 4);
            this.marcaSecundaria.Size = new System.Drawing.Size(220, 48);
            this.marcaSecundaria.MinimumSize = new System.Drawing.Size(0, 0);
            this.marcaSecundaria.MaximumSize = new System.Drawing.Size(0, 0);
            this.marcaSecundaria.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.marcaSecundaria.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.marcaSecundaria.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.marcaSecundaria.Dock = (System.Windows.Forms.DockStyle)0;
            this.marcaSecundaria.Anchor = (System.Windows.Forms.AnchorStyles)9;
            this.marcaSecundaria.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.marcaSecundaria.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.marcaSecundaria.TabIndex = 1;
            this.marcaSecundaria.TabStop = false;
            this.marcaSecundaria.AutoSize = false;
            this.marcaSecundaria.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.marcaSecundaria.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.marcaSecundaria.SizeMode = (System.Windows.Forms.PictureBoxSizeMode)4;
            this.marcaSecundaria.Image = ((System.Drawing.Image)(resources.GetObject("marcaSecundaria.Image")));
            this.marcaSecundaria.Name = "marcaSecundaria";
            // tabcontrol3
            this.tabcontrol3.Text = "";
            this.tabcontrol3.AccessibleName = null;
            this.tabcontrol3.Location = new System.Drawing.Point(25, 103);
            this.tabcontrol3.Size = new System.Drawing.Size(978, 592);
            this.tabcontrol3.MinimumSize = new System.Drawing.Size(0, 0);
            this.tabcontrol3.MaximumSize = new System.Drawing.Size(0, 0);
            this.tabcontrol3.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.tabcontrol3.BackColor = System.Drawing.Color.FromArgb(255, 240, 240, 240);
            this.tabcontrol3.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tabcontrol3.Dock = (System.Windows.Forms.DockStyle)5;
            this.tabcontrol3.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tabcontrol3.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabcontrol3.Padding = new System.Drawing.Point(20, 9);
            this.tabcontrol3.TabIndex = 1;
            this.tabcontrol3.TabStop = true;
            this.tabcontrol3.AutoSize = false;
            this.tabcontrol3.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tabcontrol3.Multiline = false;
            this.tabcontrol3.SizeMode = (System.Windows.Forms.TabSizeMode)0;
            this.tabcontrol3.Name = "tabcontrol3";
            // tabpage4
            this.tabpage4.Text = "Recebimento";
            this.tabpage4.AccessibleName = null;
            this.tabpage4.Location = new System.Drawing.Point(4, 38);
            this.tabpage4.Size = new System.Drawing.Size(970, 550);
            this.tabpage4.MinimumSize = new System.Drawing.Size(0, 0);
            this.tabpage4.MaximumSize = new System.Drawing.Size(0, 0);
            this.tabpage4.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.tabpage4.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.tabpage4.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tabpage4.Dock = (System.Windows.Forms.DockStyle)0;
            this.tabpage4.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tabpage4.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabpage4.Padding = new System.Windows.Forms.Padding(12);
            this.tabpage4.TabIndex = 0;
            this.tabpage4.TabStop = false;
            this.tabpage4.AutoSize = false;
            this.tabpage4.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tabpage4.AutoScroll = false;
            this.tabpage4.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tabpage4.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tabpage4.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tabpage4.UseVisualStyleBackColor = false;
            this.tabpage4.Name = "tabpage4";
            // panel5
            this.panel5.Text = "";
            this.panel5.AccessibleName = null;
            this.panel5.Location = new System.Drawing.Point(16, 16);
            this.panel5.Size = new System.Drawing.Size(938, 518);
            this.panel5.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel5.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel5.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel5.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel5.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel5.Dock = (System.Windows.Forms.DockStyle)5;
            this.panel5.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel5.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.panel5.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel5.TabIndex = 0;
            this.panel5.TabStop = false;
            this.panel5.AutoSize = false;
            this.panel5.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel5.AutoScroll = true;
            this.panel5.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel5.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel5.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel5.Name = "panel5";
            // flowlayoutpanel6
            this.flowlayoutpanel6.Text = "";
            this.flowlayoutpanel6.AccessibleName = null;
            this.flowlayoutpanel6.Location = new System.Drawing.Point(0, 0);
            this.flowlayoutpanel6.Size = new System.Drawing.Size(893, 557);
            this.flowlayoutpanel6.MinimumSize = new System.Drawing.Size(893, 0);
            this.flowlayoutpanel6.MaximumSize = new System.Drawing.Size(893, 0);
            this.flowlayoutpanel6.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel6.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel6.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel6.Dock = (System.Windows.Forms.DockStyle)0;
            this.flowlayoutpanel6.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel6.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.flowlayoutpanel6.Padding = new System.Windows.Forms.Padding(10, 10, 10, 10);
            this.flowlayoutpanel6.TabIndex = 0;
            this.flowlayoutpanel6.TabStop = false;
            this.flowlayoutpanel6.AutoSize = true;
            this.flowlayoutpanel6.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.flowlayoutpanel6.AutoScroll = false;
            this.flowlayoutpanel6.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel6.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel6.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel6.FlowDirection = (System.Windows.Forms.FlowDirection)1;
            this.flowlayoutpanel6.WrapContents = false;
            this.flowlayoutpanel6.Name = "flowlayoutpanel6";
            // label7
            this.label7.Text = "Cliente e aparelho";
            this.label7.AccessibleName = null;
            this.label7.Location = new System.Drawing.Point(13, 24);
            this.label7.Size = new System.Drawing.Size(867, 32);
            this.label7.MinimumSize = new System.Drawing.Size(0, 0);
            this.label7.MaximumSize = new System.Drawing.Size(0, 0);
            this.label7.Font = new System.Drawing.Font("Segoe UI", 12F, (System.Drawing.FontStyle)1);
            this.label7.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.label7.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.label7.Dock = (System.Windows.Forms.DockStyle)0;
            this.label7.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label7.Margin = new System.Windows.Forms.Padding(3, 14, 3, 4);
            this.label7.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label7.TabIndex = 0;
            this.label7.TabStop = false;
            this.label7.AutoSize = false;
            this.label7.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label7.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label7.TextAlign = (System.Drawing.ContentAlignment)1;
            this.label7.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label7.UseCompatibleTextRendering = false;
            this.label7.Name = "label7";
            // flowlayoutpanel8
            this.flowlayoutpanel8.Text = "";
            this.flowlayoutpanel8.AccessibleName = null;
            this.flowlayoutpanel8.Location = new System.Drawing.Point(10, 60);
            this.flowlayoutpanel8.Size = new System.Drawing.Size(867, 96);
            this.flowlayoutpanel8.MinimumSize = new System.Drawing.Size(867, 0);
            this.flowlayoutpanel8.MaximumSize = new System.Drawing.Size(867, 0);
            this.flowlayoutpanel8.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel8.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel8.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel8.Dock = (System.Windows.Forms.DockStyle)0;
            this.flowlayoutpanel8.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel8.Margin = new System.Windows.Forms.Padding(0, 0, 0, 10);
            this.flowlayoutpanel8.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.flowlayoutpanel8.TabIndex = 1;
            this.flowlayoutpanel8.TabStop = false;
            this.flowlayoutpanel8.AutoSize = true;
            this.flowlayoutpanel8.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.flowlayoutpanel8.AutoScroll = false;
            this.flowlayoutpanel8.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel8.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel8.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel8.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel8.WrapContents = true;
            this.flowlayoutpanel8.Name = "flowlayoutpanel8";
            // panel9
            this.panel9.Text = "";
            this.panel9.AccessibleName = null;
            this.panel9.Location = new System.Drawing.Point(3, 3);
            this.panel9.Size = new System.Drawing.Size(421, 84);
            this.panel9.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel9.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel9.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel9.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel9.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel9.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel9.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel9.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel9.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel9.TabIndex = 0;
            this.panel9.TabStop = false;
            this.panel9.AutoSize = false;
            this.panel9.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel9.AutoScroll = false;
            this.panel9.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel9.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel9.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel9.Name = "panel9";
            // lblCliente
            this.lblCliente.Text = "Cliente";
            this.lblCliente.AccessibleName = null;
            this.lblCliente.Location = new System.Drawing.Point(0, 0);
            this.lblCliente.Size = new System.Drawing.Size(401, 25);
            this.lblCliente.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblCliente.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblCliente.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblCliente.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblCliente.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblCliente.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblCliente.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblCliente.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblCliente.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblCliente.TabIndex = 1;
            this.lblCliente.TabStop = false;
            this.lblCliente.AutoSize = false;
            this.lblCliente.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblCliente.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblCliente.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblCliente.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblCliente.UseCompatibleTextRendering = false;
            this.lblCliente.Name = "lblCliente";
            // cmbCliente
            this.cmbCliente.Text = "";
            this.cmbCliente.AccessibleName = "Cliente";
            this.cmbCliente.Location = new System.Drawing.Point(0, 32);
            this.cmbCliente.Size = new System.Drawing.Size(401, 25);
            this.cmbCliente.MinimumSize = new System.Drawing.Size(0, 0);
            this.cmbCliente.MaximumSize = new System.Drawing.Size(0, 0);
            this.cmbCliente.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.cmbCliente.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.cmbCliente.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.cmbCliente.Dock = (System.Windows.Forms.DockStyle)0;
            this.cmbCliente.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.cmbCliente.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.cmbCliente.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.cmbCliente.TabIndex = 0;
            this.cmbCliente.TabStop = true;
            this.cmbCliente.AutoSize = false;
            this.cmbCliente.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.cmbCliente.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.cmbCliente.MaxLength = 0;
            this.cmbCliente.DropDownStyle = (System.Windows.Forms.ComboBoxStyle)2;
            this.cmbCliente.IntegralHeight = true;
            this.cmbCliente.DropDownWidth = 401;
            this.cmbCliente.MaxDropDownItems = 8;
            this.cmbCliente.Name = "cmbCliente";
            // panel10
            this.panel10.Text = "";
            this.panel10.AccessibleName = null;
            this.panel10.Location = new System.Drawing.Point(436, 3);
            this.panel10.Size = new System.Drawing.Size(421, 84);
            this.panel10.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel10.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel10.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel10.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel10.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel10.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel10.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel10.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel10.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel10.TabIndex = 1;
            this.panel10.TabStop = false;
            this.panel10.AutoSize = false;
            this.panel10.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel10.AutoScroll = false;
            this.panel10.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel10.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel10.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel10.Name = "panel10";
            // lblAparelho
            this.lblAparelho.Text = "Aparelho do cliente";
            this.lblAparelho.AccessibleName = null;
            this.lblAparelho.Location = new System.Drawing.Point(0, 0);
            this.lblAparelho.Size = new System.Drawing.Size(401, 25);
            this.lblAparelho.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblAparelho.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblAparelho.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblAparelho.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblAparelho.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblAparelho.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblAparelho.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblAparelho.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblAparelho.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblAparelho.TabIndex = 3;
            this.lblAparelho.TabStop = false;
            this.lblAparelho.AutoSize = false;
            this.lblAparelho.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblAparelho.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblAparelho.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblAparelho.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblAparelho.UseCompatibleTextRendering = false;
            this.lblAparelho.Name = "lblAparelho";
            // cmbAparelho
            this.cmbAparelho.Text = "";
            this.cmbAparelho.AccessibleName = "Aparelho do cliente";
            this.cmbAparelho.Location = new System.Drawing.Point(0, 32);
            this.cmbAparelho.Size = new System.Drawing.Size(401, 25);
            this.cmbAparelho.MinimumSize = new System.Drawing.Size(0, 0);
            this.cmbAparelho.MaximumSize = new System.Drawing.Size(0, 0);
            this.cmbAparelho.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.cmbAparelho.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.cmbAparelho.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.cmbAparelho.Dock = (System.Windows.Forms.DockStyle)0;
            this.cmbAparelho.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.cmbAparelho.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.cmbAparelho.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.cmbAparelho.TabIndex = 0;
            this.cmbAparelho.TabStop = true;
            this.cmbAparelho.AutoSize = false;
            this.cmbAparelho.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.cmbAparelho.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.cmbAparelho.MaxLength = 0;
            this.cmbAparelho.DropDownStyle = (System.Windows.Forms.ComboBoxStyle)2;
            this.cmbAparelho.IntegralHeight = true;
            this.cmbAparelho.DropDownWidth = 401;
            this.cmbAparelho.MaxDropDownItems = 8;
            this.cmbAparelho.Name = "cmbAparelho";
            // label11
            this.label11.Text = "Solicitação de manutenção";
            this.label11.AccessibleName = null;
            this.label11.Location = new System.Drawing.Point(13, 180);
            this.label11.Size = new System.Drawing.Size(867, 32);
            this.label11.MinimumSize = new System.Drawing.Size(0, 0);
            this.label11.MaximumSize = new System.Drawing.Size(0, 0);
            this.label11.Font = new System.Drawing.Font("Segoe UI", 12F, (System.Drawing.FontStyle)1);
            this.label11.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.label11.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.label11.Dock = (System.Windows.Forms.DockStyle)0;
            this.label11.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label11.Margin = new System.Windows.Forms.Padding(3, 14, 3, 4);
            this.label11.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label11.TabIndex = 2;
            this.label11.TabStop = false;
            this.label11.AutoSize = false;
            this.label11.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label11.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label11.TextAlign = (System.Drawing.ContentAlignment)1;
            this.label11.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label11.UseCompatibleTextRendering = false;
            this.label11.Name = "label11";
            // flowlayoutpanel12
            this.flowlayoutpanel12.Text = "";
            this.flowlayoutpanel12.AccessibleName = null;
            this.flowlayoutpanel12.Location = new System.Drawing.Point(10, 216);
            this.flowlayoutpanel12.Size = new System.Drawing.Size(867, 254);
            this.flowlayoutpanel12.MinimumSize = new System.Drawing.Size(867, 0);
            this.flowlayoutpanel12.MaximumSize = new System.Drawing.Size(867, 0);
            this.flowlayoutpanel12.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel12.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel12.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel12.Dock = (System.Windows.Forms.DockStyle)0;
            this.flowlayoutpanel12.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel12.Margin = new System.Windows.Forms.Padding(0, 0, 0, 10);
            this.flowlayoutpanel12.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.flowlayoutpanel12.TabIndex = 3;
            this.flowlayoutpanel12.TabStop = false;
            this.flowlayoutpanel12.AutoSize = true;
            this.flowlayoutpanel12.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.flowlayoutpanel12.AutoScroll = false;
            this.flowlayoutpanel12.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel12.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel12.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel12.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel12.WrapContents = true;
            this.flowlayoutpanel12.Name = "flowlayoutpanel12";
            // panel13
            this.panel13.Text = "";
            this.panel13.AccessibleName = null;
            this.panel13.Location = new System.Drawing.Point(3, 3);
            this.panel13.Size = new System.Drawing.Size(421, 146);
            this.panel13.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel13.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel13.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel13.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel13.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel13.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel13.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel13.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel13.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel13.TabIndex = 0;
            this.panel13.TabStop = false;
            this.panel13.AutoSize = false;
            this.panel13.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel13.AutoScroll = false;
            this.panel13.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel13.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel13.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel13.Name = "panel13";
            // lblProblema
            this.lblProblema.Text = "Problema relatado pelo cliente";
            this.lblProblema.AccessibleName = null;
            this.lblProblema.Location = new System.Drawing.Point(0, 0);
            this.lblProblema.Size = new System.Drawing.Size(401, 25);
            this.lblProblema.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblProblema.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblProblema.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblProblema.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblProblema.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblProblema.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblProblema.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblProblema.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblProblema.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblProblema.TabIndex = 5;
            this.lblProblema.TabStop = false;
            this.lblProblema.AutoSize = false;
            this.lblProblema.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblProblema.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblProblema.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblProblema.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblProblema.UseCompatibleTextRendering = false;
            this.lblProblema.Name = "lblProblema";
            // txtProblema
            this.txtProblema.Text = "";
            this.txtProblema.AccessibleName = "Problema relatado pelo cliente";
            this.txtProblema.Location = new System.Drawing.Point(0, 32);
            this.txtProblema.Size = new System.Drawing.Size(401, 106);
            this.txtProblema.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtProblema.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtProblema.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtProblema.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtProblema.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtProblema.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtProblema.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtProblema.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtProblema.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtProblema.TabIndex = 0;
            this.txtProblema.TabStop = true;
            this.txtProblema.AutoSize = true;
            this.txtProblema.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtProblema.BorderStyle = (System.Windows.Forms.BorderStyle)1;
            this.txtProblema.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.txtProblema.ReadOnly = false;
            this.txtProblema.Multiline = true;
            this.txtProblema.MaxLength = 2000;
            this.txtProblema.UseSystemPasswordChar = false;
            this.txtProblema.ScrollBars = (System.Windows.Forms.ScrollBars)2;
            this.txtProblema.WordWrap = true;
            this.txtProblema.AcceptsReturn = false;
            this.txtProblema.AcceptsTab = false;
            this.txtProblema.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.txtProblema.Name = "txtProblema";
            // panel14
            this.panel14.Text = "";
            this.panel14.AccessibleName = null;
            this.panel14.Location = new System.Drawing.Point(436, 3);
            this.panel14.Size = new System.Drawing.Size(421, 84);
            this.panel14.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel14.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel14.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel14.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel14.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel14.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel14.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel14.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel14.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel14.TabIndex = 1;
            this.panel14.TabStop = false;
            this.panel14.AutoSize = false;
            this.panel14.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel14.AutoScroll = false;
            this.panel14.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel14.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel14.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel14.Name = "panel14";
            // lblPrevisao
            this.lblPrevisao.Text = "Previsão de entrega (opcional)";
            this.lblPrevisao.AccessibleName = null;
            this.lblPrevisao.Location = new System.Drawing.Point(0, 0);
            this.lblPrevisao.Size = new System.Drawing.Size(401, 25);
            this.lblPrevisao.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblPrevisao.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblPrevisao.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblPrevisao.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblPrevisao.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblPrevisao.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblPrevisao.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblPrevisao.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblPrevisao.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblPrevisao.TabIndex = 7;
            this.lblPrevisao.TabStop = false;
            this.lblPrevisao.AutoSize = false;
            this.lblPrevisao.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblPrevisao.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblPrevisao.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblPrevisao.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblPrevisao.UseCompatibleTextRendering = false;
            this.lblPrevisao.Name = "lblPrevisao";
            // dtPrevisao
            this.dtPrevisao.AccessibleName = "Previsão de entrega (opcional)";
            this.dtPrevisao.Location = new System.Drawing.Point(0, 32);
            this.dtPrevisao.Size = new System.Drawing.Size(401, 25);
            this.dtPrevisao.MinimumSize = new System.Drawing.Size(0, 0);
            this.dtPrevisao.MaximumSize = new System.Drawing.Size(0, 0);
            this.dtPrevisao.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.dtPrevisao.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.dtPrevisao.ForeColor = System.Drawing.Color.FromArgb(255, 0, 0, 0);
            this.dtPrevisao.Dock = (System.Windows.Forms.DockStyle)0;
            this.dtPrevisao.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.dtPrevisao.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.dtPrevisao.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.dtPrevisao.TabIndex = 0;
            this.dtPrevisao.TabStop = true;
            this.dtPrevisao.AutoSize = false;
            this.dtPrevisao.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.dtPrevisao.Checked = true;
            this.dtPrevisao.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtPrevisao.CustomFormat = "dd/MM/yyyy";
            this.dtPrevisao.ShowCheckBox = true;
            this.dtPrevisao.Name = "dtPrevisao";
            // panel15
            this.panel15.Text = "";
            this.panel15.AccessibleName = null;
            this.panel15.Location = new System.Drawing.Point(3, 161);
            this.panel15.Size = new System.Drawing.Size(421, 84);
            this.panel15.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel15.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel15.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel15.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel15.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel15.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel15.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel15.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel15.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel15.TabIndex = 2;
            this.panel15.TabStop = false;
            this.panel15.AutoSize = false;
            this.panel15.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel15.AutoScroll = false;
            this.panel15.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel15.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel15.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel15.Name = "panel15";
            // lblObservacoes
            this.lblObservacoes.Text = "Observações de recebimento";
            this.lblObservacoes.AccessibleName = null;
            this.lblObservacoes.Location = new System.Drawing.Point(0, 0);
            this.lblObservacoes.Size = new System.Drawing.Size(401, 25);
            this.lblObservacoes.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblObservacoes.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblObservacoes.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblObservacoes.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblObservacoes.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblObservacoes.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblObservacoes.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblObservacoes.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblObservacoes.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblObservacoes.TabIndex = 9;
            this.lblObservacoes.TabStop = false;
            this.lblObservacoes.AutoSize = false;
            this.lblObservacoes.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblObservacoes.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblObservacoes.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblObservacoes.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblObservacoes.UseCompatibleTextRendering = false;
            this.lblObservacoes.Name = "lblObservacoes";
            // txtObservacoesFundo
            this.txtObservacoesFundo.Text = "";
            this.txtObservacoesFundo.AccessibleName = null;
            this.txtObservacoesFundo.Location = new System.Drawing.Point(0, 28);
            this.txtObservacoesFundo.Size = new System.Drawing.Size(401, 42);
            this.txtObservacoesFundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtObservacoesFundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtObservacoesFundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtObservacoesFundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtObservacoesFundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtObservacoesFundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtObservacoesFundo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtObservacoesFundo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtObservacoesFundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtObservacoesFundo.TabIndex = 0;
            this.txtObservacoesFundo.TabStop = false;
            this.txtObservacoesFundo.AutoSize = false;
            this.txtObservacoesFundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.txtObservacoesFundo.AutoScroll = false;
            this.txtObservacoesFundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.txtObservacoesFundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtObservacoesFundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtObservacoesFundo.Name = "txtObservacoesFundo";
            // txtObservacoes
            this.txtObservacoes.Text = "";
            this.txtObservacoes.AccessibleName = "Observações de recebimento";
            this.txtObservacoes.Location = new System.Drawing.Point(12, 12);
            this.txtObservacoes.Size = new System.Drawing.Size(377, 18);
            this.txtObservacoes.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtObservacoes.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtObservacoes.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtObservacoes.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtObservacoes.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtObservacoes.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtObservacoes.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtObservacoes.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtObservacoes.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtObservacoes.TabIndex = 0;
            this.txtObservacoes.TabStop = true;
            this.txtObservacoes.AutoSize = true;
            this.txtObservacoes.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtObservacoes.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtObservacoes.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.txtObservacoes.ReadOnly = false;
            this.txtObservacoes.Multiline = false;
            this.txtObservacoes.MaxLength = 1000;
            this.txtObservacoes.UseSystemPasswordChar = false;
            this.txtObservacoes.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.txtObservacoes.WordWrap = true;
            this.txtObservacoes.AcceptsReturn = false;
            this.txtObservacoes.AcceptsTab = false;
            this.txtObservacoes.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.txtObservacoes.Name = "txtObservacoes";
            // flowlayoutpanel16
            this.flowlayoutpanel16.Text = "";
            this.flowlayoutpanel16.AccessibleName = null;
            this.flowlayoutpanel16.Location = new System.Drawing.Point(13, 483);
            this.flowlayoutpanel16.Size = new System.Drawing.Size(867, 61);
            this.flowlayoutpanel16.MinimumSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel16.MaximumSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel16.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel16.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel16.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel16.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.flowlayoutpanel16.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel16.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.flowlayoutpanel16.Padding = new System.Windows.Forms.Padding(10, 8, 10, 4);
            this.flowlayoutpanel16.TabIndex = 4;
            this.flowlayoutpanel16.TabStop = false;
            this.flowlayoutpanel16.AutoSize = true;
            this.flowlayoutpanel16.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.flowlayoutpanel16.AutoScroll = false;
            this.flowlayoutpanel16.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel16.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel16.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel16.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel16.WrapContents = true;
            this.flowlayoutpanel16.Name = "flowlayoutpanel16";
            // btnSalvar
            this.btnSalvar.Text = "Abrir ordem";
            this.btnSalvar.AccessibleName = null;
            this.btnSalvar.Location = new System.Drawing.Point(0, 8);
            this.btnSalvar.Size = new System.Drawing.Size(144, 38);
            this.btnSalvar.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnSalvar.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnSalvar.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnSalvar.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnSalvar.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnSalvar.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnSalvar.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnSalvar.Margin = new System.Windows.Forms.Padding(0, 3, 10, 5);
            this.btnSalvar.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnSalvar.TabIndex = 0;
            this.btnSalvar.TabStop = true;
            this.btnSalvar.AutoSize = false;
            this.btnSalvar.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnSalvar.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnSalvar.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnSalvar.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnSalvar.UseVisualStyleBackColor = false;
            this.btnSalvar.UseCompatibleTextRendering = false;
            this.btnSalvar.FlatAppearance.BorderSize = 0;
            this.btnSalvar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnSalvar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnSalvar.Name = "btnSalvar";
            this.btnSalvar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Controls.Add(this.tablelayoutpanel1);
            this.tablelayoutpanel1.Controls.Add(this.panel2, 0, 0);
            this.panel2.Controls.Add(this.lblTitulo);
            this.panel2.Controls.Add(this.marcaSecundaria);
            this.tablelayoutpanel1.Controls.Add(this.tabcontrol3, 0, 1);
            this.tabcontrol3.Controls.Add(this.tabpage4);
            this.tabpage4.Controls.Add(this.panel5);
            this.panel5.Controls.Add(this.flowlayoutpanel6);
            this.flowlayoutpanel6.Controls.Add(this.label7);
            this.flowlayoutpanel6.Controls.Add(this.flowlayoutpanel8);
            this.flowlayoutpanel8.Controls.Add(this.panel9);
            this.panel9.Controls.Add(this.lblCliente);
            this.panel9.Controls.Add(this.cmbCliente);
            this.flowlayoutpanel8.Controls.Add(this.panel10);
            this.panel10.Controls.Add(this.lblAparelho);
            this.panel10.Controls.Add(this.cmbAparelho);
            this.flowlayoutpanel6.Controls.Add(this.label11);
            this.flowlayoutpanel6.Controls.Add(this.flowlayoutpanel12);
            this.flowlayoutpanel12.Controls.Add(this.panel13);
            this.panel13.Controls.Add(this.lblProblema);
            this.panel13.Controls.Add(this.txtProblema);
            this.flowlayoutpanel12.Controls.Add(this.panel14);
            this.panel14.Controls.Add(this.lblPrevisao);
            this.panel14.Controls.Add(this.dtPrevisao);
            this.flowlayoutpanel12.Controls.Add(this.panel15);
            this.panel15.Controls.Add(this.lblObservacoes);
            this.panel15.Controls.Add(this.txtObservacoesFundo);
            this.txtObservacoesFundo.Controls.Add(this.txtObservacoes);
            this.tabpage4.Controls.Add(this.flowlayoutpanel16);
            this.flowlayoutpanel16.Controls.Add(this.btnSalvar);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.cmbCliente.SelectedIndexChanged += new System.EventHandler(this.cmbCliente_SelectedIndexChanged);
            this.btnSalvar.Click += new System.EventHandler(this.btnSalvar_Click);
            this.Load += new System.EventHandler(this.AbrirOrdemForm_Load);
            this.txtObservacoesFundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnSalvar.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.panel5.SizeChanged += new System.EventHandler(this.flowlayoutpanel6_Redimensionar);
            this.flowlayoutpanel16.ResumeLayout(false);
            this.flowlayoutpanel16.PerformLayout();
            this.txtObservacoesFundo.ResumeLayout(false);
            this.txtObservacoesFundo.PerformLayout();
            this.panel15.ResumeLayout(false);
            this.panel15.PerformLayout();
            this.panel14.ResumeLayout(false);
            this.panel14.PerformLayout();
            this.panel13.ResumeLayout(false);
            this.panel13.PerformLayout();
            this.flowlayoutpanel12.ResumeLayout(false);
            this.flowlayoutpanel12.PerformLayout();
            this.panel10.ResumeLayout(false);
            this.panel10.PerformLayout();
            this.panel9.ResumeLayout(false);
            this.panel9.PerformLayout();
            this.flowlayoutpanel8.ResumeLayout(false);
            this.flowlayoutpanel8.PerformLayout();
            this.flowlayoutpanel6.ResumeLayout(false);
            this.flowlayoutpanel6.PerformLayout();
            this.panel5.ResumeLayout(false);
            this.panel5.PerformLayout();
            this.tabpage4.ResumeLayout(false);
            this.tabpage4.PerformLayout();
            this.tabcontrol3.ResumeLayout(false);
            this.tabcontrol3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.marcaSecundaria)).EndInit();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.tablelayoutpanel1.ResumeLayout(false);
            this.tablelayoutpanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.TableLayoutPanel tablelayoutpanel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.PictureBox marcaSecundaria;
        private System.Windows.Forms.TabControl tabcontrol3;
        private System.Windows.Forms.TabPage tabpage4;
        private System.Windows.Forms.Panel panel5;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel8;
        private System.Windows.Forms.Panel panel9;
        private System.Windows.Forms.Label lblCliente;
        private System.Windows.Forms.ComboBox cmbCliente;
        private System.Windows.Forms.Panel panel10;
        private System.Windows.Forms.Label lblAparelho;
        private System.Windows.Forms.ComboBox cmbAparelho;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel12;
        private System.Windows.Forms.Panel panel13;
        private System.Windows.Forms.Label lblProblema;
        private System.Windows.Forms.TextBox txtProblema;
        private System.Windows.Forms.Panel panel14;
        private System.Windows.Forms.Label lblPrevisao;
        private System.Windows.Forms.DateTimePicker dtPrevisao;
        private System.Windows.Forms.Panel panel15;
        private System.Windows.Forms.Label lblObservacoes;
        private System.Windows.Forms.Panel txtObservacoesFundo;
        private System.Windows.Forms.TextBox txtObservacoes;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel16;
        private System.Windows.Forms.Button btnSalvar;
    }
}
