namespace Tecnologia
{
    partial class AparelhosForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Location = new System.Drawing.Point(22, 14);
            this.lblTitulo.Size = new System.Drawing.Size(900, 24);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Aparelhos dos clientes";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblTitulo);
            this.cmbCampo = new System.Windows.Forms.ComboBox();
            this.cmbCampo.Name = "cmbCampo";
            this.cmbCampo.Location = new System.Drawing.Point(22, 55);
            this.cmbCampo.Size = new System.Drawing.Size(180, 26);
            this.cmbCampo.TabIndex = 1;
            this.cmbCampo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCampo.Items.AddRange(new object[] { "Modelo", "Código", "Código do cliente", "Marca", "Série / IMEI", "Tipo" });
            this.Controls.Add(this.cmbCampo);
            this.txtBusca = new System.Windows.Forms.TextBox();
            this.txtBusca.Name = "txtBusca";
            this.txtBusca.Location = new System.Drawing.Point(216, 55);
            this.txtBusca.Size = new System.Drawing.Size(350, 26);
            this.txtBusca.TabIndex = 2;
            this.txtBusca.MaxLength = 100;
            this.txtBusca.MaxLength = 100;
            this.Controls.Add(this.txtBusca);
            this.btnPesquisar = new System.Windows.Forms.Button();
            this.btnPesquisar.Name = "btnPesquisar";
            this.btnPesquisar.Location = new System.Drawing.Point(580, 50);
            this.btnPesquisar.Size = new System.Drawing.Size(142, 34);
            this.btnPesquisar.TabIndex = 3;
            this.btnPesquisar.Text = "Pesquisar";
            this.btnPesquisar.UseVisualStyleBackColor = true;
            this.btnPesquisar.Click += new System.EventHandler(this.btnPesquisar_Click);
            this.Controls.Add(this.btnPesquisar);
            this.btnExportar = new System.Windows.Forms.Button();
            this.btnExportar.Name = "btnExportar";
            this.btnExportar.Location = new System.Drawing.Point(738, 50);
            this.btnExportar.Size = new System.Drawing.Size(142, 34);
            this.btnExportar.TabIndex = 4;
            this.btnExportar.Text = "Exportar Excel";
            this.btnExportar.UseVisualStyleBackColor = true;
            this.btnExportar.Click += new System.EventHandler(this.btnExportar_Click);
            this.Controls.Add(this.btnExportar);
            this.lblcliente_id = new System.Windows.Forms.Label();
            this.lblcliente_id.Name = "lblcliente_id";
            this.lblcliente_id.Location = new System.Drawing.Point(22, 102);
            this.lblcliente_id.Size = new System.Drawing.Size(320, 24);
            this.lblcliente_id.TabIndex = 5;
            this.lblcliente_id.Text = "Cliente";
            this.lblcliente_id.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblcliente_id);
            this.campocliente_id = new System.Windows.Forms.ComboBox();
            this.campocliente_id.Name = "campocliente_id";
            this.campocliente_id.Location = new System.Drawing.Point(22, 126);
            this.campocliente_id.Size = new System.Drawing.Size(338, 26);
            this.campocliente_id.TabIndex = 6;
            this.campocliente_id.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.Controls.Add(this.campocliente_id);
            this.lbltipo = new System.Windows.Forms.Label();
            this.lbltipo.Name = "lbltipo";
            this.lbltipo.Location = new System.Drawing.Point(382, 102);
            this.lbltipo.Size = new System.Drawing.Size(320, 24);
            this.lbltipo.TabIndex = 7;
            this.lbltipo.Text = "Tipo";
            this.lbltipo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lbltipo);
            this.campotipo = new System.Windows.Forms.ComboBox();
            this.campotipo.Name = "campotipo";
            this.campotipo.Location = new System.Drawing.Point(382, 126);
            this.campotipo.Size = new System.Drawing.Size(338, 26);
            this.campotipo.TabIndex = 8;
            this.campotipo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.campotipo.Items.AddRange(new object[] { "Celular", "Notebook", "PC" });
            this.Controls.Add(this.campotipo);
            this.lblmarca = new System.Windows.Forms.Label();
            this.lblmarca.Name = "lblmarca";
            this.lblmarca.Location = new System.Drawing.Point(742, 102);
            this.lblmarca.Size = new System.Drawing.Size(320, 24);
            this.lblmarca.TabIndex = 9;
            this.lblmarca.Text = "Marca";
            this.lblmarca.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblmarca);
            this.campomarca = new System.Windows.Forms.TextBox();
            this.campomarca.Name = "campomarca";
            this.campomarca.Location = new System.Drawing.Point(742, 126);
            this.campomarca.Size = new System.Drawing.Size(338, 26);
            this.campomarca.TabIndex = 10;
            this.campomarca.MaxLength = 100;
            this.campomarca.MaxLength = 80;
            this.Controls.Add(this.campomarca);
            this.lblmodelo = new System.Windows.Forms.Label();
            this.lblmodelo.Name = "lblmodelo";
            this.lblmodelo.Location = new System.Drawing.Point(22, 158);
            this.lblmodelo.Size = new System.Drawing.Size(320, 24);
            this.lblmodelo.TabIndex = 11;
            this.lblmodelo.Text = "Modelo";
            this.lblmodelo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblmodelo);
            this.campomodelo = new System.Windows.Forms.TextBox();
            this.campomodelo.Name = "campomodelo";
            this.campomodelo.Location = new System.Drawing.Point(22, 182);
            this.campomodelo.Size = new System.Drawing.Size(338, 26);
            this.campomodelo.TabIndex = 12;
            this.campomodelo.MaxLength = 100;
            this.campomodelo.MaxLength = 100;
            this.Controls.Add(this.campomodelo);
            this.lblnumero_serie = new System.Windows.Forms.Label();
            this.lblnumero_serie.Name = "lblnumero_serie";
            this.lblnumero_serie.Location = new System.Drawing.Point(382, 158);
            this.lblnumero_serie.Size = new System.Drawing.Size(320, 24);
            this.lblnumero_serie.TabIndex = 13;
            this.lblnumero_serie.Text = "Número de série / IMEI";
            this.lblnumero_serie.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblnumero_serie);
            this.camponumero_serie = new System.Windows.Forms.TextBox();
            this.camponumero_serie.Name = "camponumero_serie";
            this.camponumero_serie.Location = new System.Drawing.Point(382, 182);
            this.camponumero_serie.Size = new System.Drawing.Size(338, 26);
            this.camponumero_serie.TabIndex = 14;
            this.camponumero_serie.MaxLength = 100;
            this.camponumero_serie.MaxLength = 100;
            this.Controls.Add(this.camponumero_serie);
            this.lblcor = new System.Windows.Forms.Label();
            this.lblcor.Name = "lblcor";
            this.lblcor.Location = new System.Drawing.Point(742, 158);
            this.lblcor.Size = new System.Drawing.Size(320, 24);
            this.lblcor.TabIndex = 15;
            this.lblcor.Text = "Cor";
            this.lblcor.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblcor);
            this.campocor = new System.Windows.Forms.TextBox();
            this.campocor.Name = "campocor";
            this.campocor.Location = new System.Drawing.Point(742, 182);
            this.campocor.Size = new System.Drawing.Size(338, 26);
            this.campocor.TabIndex = 16;
            this.campocor.MaxLength = 100;
            this.campocor.MaxLength = 50;
            this.Controls.Add(this.campocor);
            this.lblacessorios = new System.Windows.Forms.Label();
            this.lblacessorios.Name = "lblacessorios";
            this.lblacessorios.Location = new System.Drawing.Point(22, 214);
            this.lblacessorios.Size = new System.Drawing.Size(320, 24);
            this.lblacessorios.TabIndex = 17;
            this.lblacessorios.Text = "Acessórios recebidos";
            this.lblacessorios.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblacessorios);
            this.campoacessorios = new System.Windows.Forms.TextBox();
            this.campoacessorios.Name = "campoacessorios";
            this.campoacessorios.Location = new System.Drawing.Point(22, 238);
            this.campoacessorios.Size = new System.Drawing.Size(338, 26);
            this.campoacessorios.TabIndex = 18;
            this.campoacessorios.MaxLength = 100;
            this.campoacessorios.MaxLength = 200;
            this.Controls.Add(this.campoacessorios);
            this.lblestado_fisico = new System.Windows.Forms.Label();
            this.lblestado_fisico.Name = "lblestado_fisico";
            this.lblestado_fisico.Location = new System.Drawing.Point(382, 214);
            this.lblestado_fisico.Size = new System.Drawing.Size(320, 24);
            this.lblestado_fisico.TabIndex = 19;
            this.lblestado_fisico.Text = "Estado físico";
            this.lblestado_fisico.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblestado_fisico);
            this.campoestado_fisico = new System.Windows.Forms.TextBox();
            this.campoestado_fisico.Name = "campoestado_fisico";
            this.campoestado_fisico.Location = new System.Drawing.Point(382, 238);
            this.campoestado_fisico.Size = new System.Drawing.Size(338, 26);
            this.campoestado_fisico.TabIndex = 20;
            this.campoestado_fisico.MaxLength = 100;
            this.campoestado_fisico.MaxLength = 300;
            this.Controls.Add(this.campoestado_fisico);
            this.lblobservacoes = new System.Windows.Forms.Label();
            this.lblobservacoes.Name = "lblobservacoes";
            this.lblobservacoes.Location = new System.Drawing.Point(742, 214);
            this.lblobservacoes.Size = new System.Drawing.Size(320, 24);
            this.lblobservacoes.TabIndex = 21;
            this.lblobservacoes.Text = "Observações";
            this.lblobservacoes.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblobservacoes);
            this.campoobservacoes = new System.Windows.Forms.TextBox();
            this.campoobservacoes.Name = "campoobservacoes";
            this.campoobservacoes.Location = new System.Drawing.Point(742, 238);
            this.campoobservacoes.Size = new System.Drawing.Size(338, 26);
            this.campoobservacoes.TabIndex = 22;
            this.campoobservacoes.MaxLength = 100;
            this.campoobservacoes.MaxLength = 500;
            this.Controls.Add(this.campoobservacoes);
            this.btnNovo = new System.Windows.Forms.Button();
            this.btnNovo.Name = "btnNovo";
            this.btnNovo.Location = new System.Drawing.Point(22, 340);
            this.btnNovo.Size = new System.Drawing.Size(142, 34);
            this.btnNovo.TabIndex = 23;
            this.btnNovo.Text = "Novo / limpar";
            this.btnNovo.UseVisualStyleBackColor = true;
            this.btnNovo.Click += new System.EventHandler(this.btnNovo_Click);
            this.Controls.Add(this.btnNovo);
            this.btnSalvar = new System.Windows.Forms.Button();
            this.btnSalvar.Name = "btnSalvar";
            this.btnSalvar.Location = new System.Drawing.Point(178, 340);
            this.btnSalvar.Size = new System.Drawing.Size(142, 34);
            this.btnSalvar.TabIndex = 24;
            this.btnSalvar.Text = "Salvar";
            this.btnSalvar.UseVisualStyleBackColor = true;
            this.btnSalvar.Click += new System.EventHandler(this.btnSalvar_Click);
            this.Controls.Add(this.btnSalvar);
            this.btnEditar = new System.Windows.Forms.Button();
            this.btnEditar.Name = "btnEditar";
            this.btnEditar.Location = new System.Drawing.Point(334, 340);
            this.btnEditar.Size = new System.Drawing.Size(170, 34);
            this.btnEditar.TabIndex = 25;
            this.btnEditar.Text = "Editar selecionado";
            this.btnEditar.UseVisualStyleBackColor = true;
            this.btnEditar.Click += new System.EventHandler(this.btnEditar_Click);
            this.Controls.Add(this.btnEditar);
            this.btnExcluir = new System.Windows.Forms.Button();
            this.btnExcluir.Name = "btnExcluir";
            this.btnExcluir.Location = new System.Drawing.Point(518, 340);
            this.btnExcluir.Size = new System.Drawing.Size(170, 34);
            this.btnExcluir.TabIndex = 26;
            this.btnExcluir.Text = "Excluir selecionado";
            this.btnExcluir.UseVisualStyleBackColor = true;
            this.btnExcluir.Click += new System.EventHandler(this.btnExcluir_Click);
            this.Controls.Add(this.btnExcluir);
            this.lblEdicao = new System.Windows.Forms.Label();
            this.lblEdicao.Name = "lblEdicao";
            this.lblEdicao.Location = new System.Drawing.Point(710, 345);
            this.lblEdicao.Size = new System.Drawing.Size(365, 24);
            this.lblEdicao.TabIndex = 27;
            this.lblEdicao.Text = "Novo cadastro";
            this.lblEdicao.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblEdicao);
            this.grade = new System.Windows.Forms.DataGridView();
            this.grade.Name = "grade";
            this.grade.Location = new System.Drawing.Point(22, 390);
            this.grade.Size = new System.Drawing.Size(1076, 260);
            this.grade.TabIndex = 28;
            this.grade.ReadOnly = true;
            this.grade.AllowUserToAddRows = false;
            this.grade.AllowUserToDeleteRows = false;
            this.grade.MultiSelect = false;
            this.grade.RowHeadersVisible = false;
            this.grade.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.grade.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.grade.BackgroundColor = System.Drawing.Color.White;
            this.grade.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.Controls.Add(this.grade);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(1120, 680);
            this.MinimumSize = new System.Drawing.Size(1120, 680);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Aparelhos dos clientes";
            this.Name = "AparelhosForm";
            this.Load += new System.EventHandler(this.AparelhosForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.ComboBox cmbCampo;
        private System.Windows.Forms.TextBox txtBusca;
        private System.Windows.Forms.Button btnPesquisar;
        private System.Windows.Forms.Button btnExportar;
        private System.Windows.Forms.Label lblcliente_id;
        private System.Windows.Forms.ComboBox campocliente_id;
        private System.Windows.Forms.Label lbltipo;
        private System.Windows.Forms.ComboBox campotipo;
        private System.Windows.Forms.Label lblmarca;
        private System.Windows.Forms.TextBox campomarca;
        private System.Windows.Forms.Label lblmodelo;
        private System.Windows.Forms.TextBox campomodelo;
        private System.Windows.Forms.Label lblnumero_serie;
        private System.Windows.Forms.TextBox camponumero_serie;
        private System.Windows.Forms.Label lblcor;
        private System.Windows.Forms.TextBox campocor;
        private System.Windows.Forms.Label lblacessorios;
        private System.Windows.Forms.TextBox campoacessorios;
        private System.Windows.Forms.Label lblestado_fisico;
        private System.Windows.Forms.TextBox campoestado_fisico;
        private System.Windows.Forms.Label lblobservacoes;
        private System.Windows.Forms.TextBox campoobservacoes;
        private System.Windows.Forms.Button btnNovo;
        private System.Windows.Forms.Button btnSalvar;
        private System.Windows.Forms.Button btnEditar;
        private System.Windows.Forms.Button btnExcluir;
        private System.Windows.Forms.Label lblEdicao;
        private System.Windows.Forms.DataGridView grade;
    }
}
