namespace Tecnologia
{
    partial class CriarContaForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null) components.Dispose();
                if (BackgroundImage != null) BackgroundImage.Dispose();
                if (picturebox1 != null && picturebox1.Image != null) picturebox1.Image.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CriarContaForm));
            this.picturebox1 = new System.Windows.Forms.PictureBox();
            this.cartaoAcesso = new System.Windows.Forms.FlowLayoutPanel();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.Fundo = new System.Windows.Forms.Panel();
            this.nome = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.panel6 = new System.Windows.Forms.Panel();
            this.email = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.panel8 = new System.Windows.Forms.Panel();
            this.confirmarEmail = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.panel10 = new System.Windows.Forms.Panel();
            this.senha = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.panel12 = new System.Windows.Forms.Panel();
            this.confirmarSenha = new System.Windows.Forms.TextBox();
            this.criar = new System.Windows.Forms.Button();
            this.linklabel13 = new System.Windows.Forms.LinkLabel();
            this.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picturebox1)).BeginInit();
            this.cartaoAcesso.SuspendLayout();
            this.Fundo.SuspendLayout();
            this.panel6.SuspendLayout();
            this.panel8.SuspendLayout();
            this.panel10.SuspendLayout();
            this.panel12.SuspendLayout();
            // CriarContaForm
            this.Text = "Tecnologia — Criar conta";
            this.AccessibleName = null;
            this.MinimumSize = new System.Drawing.Size(480, 360);
            this.MaximumSize = new System.Drawing.Size(0, 0);
            this.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Dock = (System.Windows.Forms.DockStyle)0;
            this.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.TabIndex = 0;
            this.TabStop = true;
            this.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.AutoScroll = true;
            this.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)3;
            this.ClientSize = new System.Drawing.Size(1040, 780);
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.Name = "CriarContaForm";
            // picturebox1
            this.picturebox1.Text = "";
            this.picturebox1.AccessibleName = "Tecnologia";
            this.picturebox1.Location = new System.Drawing.Point(285, 24);
            this.picturebox1.Size = new System.Drawing.Size(440, 94);
            this.picturebox1.MinimumSize = new System.Drawing.Size(0, 0);
            this.picturebox1.MaximumSize = new System.Drawing.Size(0, 0);
            this.picturebox1.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.picturebox1.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.picturebox1.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.picturebox1.Dock = (System.Windows.Forms.DockStyle)0;
            this.picturebox1.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.picturebox1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.picturebox1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.picturebox1.TabIndex = 0;
            this.picturebox1.TabStop = false;
            this.picturebox1.AutoSize = false;
            this.picturebox1.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.picturebox1.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.picturebox1.SizeMode = (System.Windows.Forms.PictureBoxSizeMode)4;
            this.picturebox1.Image = ((System.Drawing.Image)(resources.GetObject("picturebox1.Image")));
            this.picturebox1.Name = "picturebox1";
            // cartaoAcesso
            this.cartaoAcesso.Text = "";
            this.cartaoAcesso.AccessibleName = null;
            this.cartaoAcesso.Location = new System.Drawing.Point(313, 146);
            this.cartaoAcesso.Size = new System.Drawing.Size(384, 592);
            this.cartaoAcesso.MinimumSize = new System.Drawing.Size(384, 0);
            this.cartaoAcesso.MaximumSize = new System.Drawing.Size(384, 0);
            this.cartaoAcesso.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.cartaoAcesso.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.cartaoAcesso.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.cartaoAcesso.Dock = (System.Windows.Forms.DockStyle)0;
            this.cartaoAcesso.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.cartaoAcesso.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.cartaoAcesso.Padding = new System.Windows.Forms.Padding(28, 24, 28, 24);
            this.cartaoAcesso.TabIndex = 1;
            this.cartaoAcesso.TabStop = false;
            this.cartaoAcesso.AutoSize = true;
            this.cartaoAcesso.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.cartaoAcesso.AutoScroll = false;
            this.cartaoAcesso.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.cartaoAcesso.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.cartaoAcesso.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.cartaoAcesso.FlowDirection = (System.Windows.Forms.FlowDirection)1;
            this.cartaoAcesso.WrapContents = false;
            this.cartaoAcesso.Name = "cartaoAcesso";
            // label2
            this.label2.Text = "Criar conta";
            this.label2.AccessibleName = null;
            this.label2.Location = new System.Drawing.Point(28, 24);
            this.label2.Size = new System.Drawing.Size(322, 32);
            this.label2.MinimumSize = new System.Drawing.Size(322, 0);
            this.label2.MaximumSize = new System.Drawing.Size(322, 0);
            this.label2.Font = new System.Drawing.Font("Segoe UI", 18F, (System.Drawing.FontStyle)1);
            this.label2.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label2.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.label2.Dock = (System.Windows.Forms.DockStyle)0;
            this.label2.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label2.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.label2.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label2.TabIndex = 0;
            this.label2.TabStop = false;
            this.label2.AutoSize = true;
            this.label2.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label2.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label2.TextAlign = (System.Drawing.ContentAlignment)32;
            this.label2.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label2.UseCompatibleTextRendering = false;
            this.label2.Name = "label2";
            // label3
            this.label3.Text = "Preencha seus dados para solicitar acesso ao sistema.";
            this.label3.AccessibleName = null;
            this.label3.Location = new System.Drawing.Point(28, 70);
            this.label3.Size = new System.Drawing.Size(322, 15);
            this.label3.MinimumSize = new System.Drawing.Size(322, 0);
            this.label3.MaximumSize = new System.Drawing.Size(322, 0);
            this.label3.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label3.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label3.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label3.Dock = (System.Windows.Forms.DockStyle)0;
            this.label3.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label3.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.label3.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label3.TabIndex = 1;
            this.label3.TabStop = false;
            this.label3.AutoSize = true;
            this.label3.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label3.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label3.TextAlign = (System.Drawing.ContentAlignment)32;
            this.label3.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label3.UseCompatibleTextRendering = false;
            this.label3.Name = "label3";
            // label4
            this.label4.Text = "Nome completo";
            this.label4.AccessibleName = null;
            this.label4.Location = new System.Drawing.Point(28, 99);
            this.label4.Size = new System.Drawing.Size(322, 15);
            this.label4.MinimumSize = new System.Drawing.Size(322, 0);
            this.label4.MaximumSize = new System.Drawing.Size(322, 0);
            this.label4.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label4.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label4.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label4.Dock = (System.Windows.Forms.DockStyle)0;
            this.label4.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label4.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.label4.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label4.TabIndex = 2;
            this.label4.TabStop = false;
            this.label4.AutoSize = true;
            this.label4.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label4.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label4.TextAlign = (System.Drawing.ContentAlignment)16;
            this.label4.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label4.UseCompatibleTextRendering = false;
            this.label4.Name = "label4";
            // Fundo
            this.Fundo.Text = "";
            this.Fundo.AccessibleName = null;
            this.Fundo.Location = new System.Drawing.Point(28, 119);
            this.Fundo.Size = new System.Drawing.Size(322, 42);
            this.Fundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.Fundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.Fundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.Fundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.Fundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Fundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.Fundo.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Fundo.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.Fundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.Fundo.TabIndex = 3;
            this.Fundo.TabStop = false;
            this.Fundo.AutoSize = false;
            this.Fundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.Fundo.AutoScroll = false;
            this.Fundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.Fundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.Fundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.Fundo.Name = "Fundo";
            // nome
            this.nome.Text = "";
            this.nome.AccessibleName = "Nome completo";
            this.nome.Location = new System.Drawing.Point(12, 12);
            this.nome.Size = new System.Drawing.Size(298, 18);
            this.nome.MinimumSize = new System.Drawing.Size(0, 0);
            this.nome.MaximumSize = new System.Drawing.Size(0, 0);
            this.nome.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.nome.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.nome.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.nome.Dock = (System.Windows.Forms.DockStyle)0;
            this.nome.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.nome.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.nome.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.nome.TabIndex = 0;
            this.nome.TabStop = true;
            this.nome.AutoSize = true;
            this.nome.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.nome.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.nome.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.nome.ReadOnly = false;
            this.nome.Multiline = false;
            this.nome.MaxLength = 100;
            this.nome.UseSystemPasswordChar = false;
            this.nome.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.nome.WordWrap = true;
            this.nome.AcceptsReturn = false;
            this.nome.AcceptsTab = false;
            this.nome.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.nome.Name = "nome";
            // label5
            this.label5.Text = "E-mail";
            this.label5.AccessibleName = null;
            this.label5.Location = new System.Drawing.Point(28, 175);
            this.label5.Size = new System.Drawing.Size(322, 15);
            this.label5.MinimumSize = new System.Drawing.Size(322, 0);
            this.label5.MaximumSize = new System.Drawing.Size(322, 0);
            this.label5.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label5.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label5.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label5.Dock = (System.Windows.Forms.DockStyle)0;
            this.label5.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label5.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.label5.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label5.TabIndex = 4;
            this.label5.TabStop = false;
            this.label5.AutoSize = true;
            this.label5.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label5.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label5.TextAlign = (System.Drawing.ContentAlignment)16;
            this.label5.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label5.UseCompatibleTextRendering = false;
            this.label5.Name = "label5";
            // panel6
            this.panel6.Text = "";
            this.panel6.AccessibleName = null;
            this.panel6.Location = new System.Drawing.Point(28, 195);
            this.panel6.Size = new System.Drawing.Size(322, 42);
            this.panel6.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel6.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel6.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel6.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.panel6.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel6.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel6.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel6.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.panel6.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel6.TabIndex = 5;
            this.panel6.TabStop = false;
            this.panel6.AutoSize = false;
            this.panel6.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel6.AutoScroll = false;
            this.panel6.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel6.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel6.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel6.Name = "panel6";
            // email
            this.email.Text = "";
            this.email.AccessibleName = "E-mail";
            this.email.Location = new System.Drawing.Point(12, 12);
            this.email.Size = new System.Drawing.Size(298, 18);
            this.email.MinimumSize = new System.Drawing.Size(0, 0);
            this.email.MaximumSize = new System.Drawing.Size(0, 0);
            this.email.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.email.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.email.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.email.Dock = (System.Windows.Forms.DockStyle)0;
            this.email.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.email.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.email.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.email.TabIndex = 0;
            this.email.TabStop = true;
            this.email.AutoSize = true;
            this.email.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.email.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.email.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.email.ReadOnly = false;
            this.email.Multiline = false;
            this.email.MaxLength = 100;
            this.email.UseSystemPasswordChar = false;
            this.email.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.email.WordWrap = true;
            this.email.AcceptsReturn = false;
            this.email.AcceptsTab = false;
            this.email.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.email.Name = "email";
            // label7
            this.label7.Text = "Confirme o e-mail";
            this.label7.AccessibleName = null;
            this.label7.Location = new System.Drawing.Point(28, 251);
            this.label7.Size = new System.Drawing.Size(322, 15);
            this.label7.MinimumSize = new System.Drawing.Size(322, 0);
            this.label7.MaximumSize = new System.Drawing.Size(322, 0);
            this.label7.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label7.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label7.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label7.Dock = (System.Windows.Forms.DockStyle)0;
            this.label7.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label7.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.label7.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label7.TabIndex = 6;
            this.label7.TabStop = false;
            this.label7.AutoSize = true;
            this.label7.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label7.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label7.TextAlign = (System.Drawing.ContentAlignment)16;
            this.label7.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label7.UseCompatibleTextRendering = false;
            this.label7.Name = "label7";
            // panel8
            this.panel8.Text = "";
            this.panel8.AccessibleName = null;
            this.panel8.Location = new System.Drawing.Point(28, 271);
            this.panel8.Size = new System.Drawing.Size(322, 42);
            this.panel8.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel8.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel8.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel8.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.panel8.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel8.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel8.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel8.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.panel8.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel8.TabIndex = 7;
            this.panel8.TabStop = false;
            this.panel8.AutoSize = false;
            this.panel8.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel8.AutoScroll = false;
            this.panel8.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel8.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel8.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel8.Name = "panel8";
            // confirmarEmail
            this.confirmarEmail.Text = "";
            this.confirmarEmail.AccessibleName = "Confirme o e-mail";
            this.confirmarEmail.Location = new System.Drawing.Point(12, 12);
            this.confirmarEmail.Size = new System.Drawing.Size(298, 18);
            this.confirmarEmail.MinimumSize = new System.Drawing.Size(0, 0);
            this.confirmarEmail.MaximumSize = new System.Drawing.Size(0, 0);
            this.confirmarEmail.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.confirmarEmail.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.confirmarEmail.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.confirmarEmail.Dock = (System.Windows.Forms.DockStyle)0;
            this.confirmarEmail.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.confirmarEmail.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.confirmarEmail.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.confirmarEmail.TabIndex = 0;
            this.confirmarEmail.TabStop = true;
            this.confirmarEmail.AutoSize = true;
            this.confirmarEmail.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.confirmarEmail.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.confirmarEmail.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.confirmarEmail.ReadOnly = false;
            this.confirmarEmail.Multiline = false;
            this.confirmarEmail.MaxLength = 100;
            this.confirmarEmail.UseSystemPasswordChar = false;
            this.confirmarEmail.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.confirmarEmail.WordWrap = true;
            this.confirmarEmail.AcceptsReturn = false;
            this.confirmarEmail.AcceptsTab = false;
            this.confirmarEmail.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.confirmarEmail.Name = "confirmarEmail";
            // label9
            this.label9.Text = "Senha (8 a 128 caracteres)";
            this.label9.AccessibleName = null;
            this.label9.Location = new System.Drawing.Point(28, 327);
            this.label9.Size = new System.Drawing.Size(322, 15);
            this.label9.MinimumSize = new System.Drawing.Size(322, 0);
            this.label9.MaximumSize = new System.Drawing.Size(322, 0);
            this.label9.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label9.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label9.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label9.Dock = (System.Windows.Forms.DockStyle)0;
            this.label9.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label9.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.label9.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label9.TabIndex = 8;
            this.label9.TabStop = false;
            this.label9.AutoSize = true;
            this.label9.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label9.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label9.TextAlign = (System.Drawing.ContentAlignment)16;
            this.label9.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label9.UseCompatibleTextRendering = false;
            this.label9.Name = "label9";
            // panel10
            this.panel10.Text = "";
            this.panel10.AccessibleName = null;
            this.panel10.Location = new System.Drawing.Point(28, 347);
            this.panel10.Size = new System.Drawing.Size(322, 42);
            this.panel10.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel10.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel10.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel10.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.panel10.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel10.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel10.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel10.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.panel10.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel10.TabIndex = 9;
            this.panel10.TabStop = false;
            this.panel10.AutoSize = false;
            this.panel10.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel10.AutoScroll = false;
            this.panel10.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel10.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel10.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel10.Name = "panel10";
            // senha
            this.senha.Text = "";
            this.senha.AccessibleName = "Senha (8 a 128 caracteres)";
            this.senha.Location = new System.Drawing.Point(12, 12);
            this.senha.Size = new System.Drawing.Size(298, 18);
            this.senha.MinimumSize = new System.Drawing.Size(0, 0);
            this.senha.MaximumSize = new System.Drawing.Size(0, 0);
            this.senha.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.senha.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.senha.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.senha.Dock = (System.Windows.Forms.DockStyle)0;
            this.senha.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.senha.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.senha.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.senha.TabIndex = 0;
            this.senha.TabStop = true;
            this.senha.AutoSize = true;
            this.senha.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.senha.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.senha.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.senha.ReadOnly = false;
            this.senha.Multiline = false;
            this.senha.MaxLength = 128;
            this.senha.UseSystemPasswordChar = true;
            this.senha.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.senha.WordWrap = true;
            this.senha.AcceptsReturn = false;
            this.senha.AcceptsTab = false;
            this.senha.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.senha.Name = "senha";
            // label11
            this.label11.Text = "Confirme a senha";
            this.label11.AccessibleName = null;
            this.label11.Location = new System.Drawing.Point(28, 403);
            this.label11.Size = new System.Drawing.Size(322, 15);
            this.label11.MinimumSize = new System.Drawing.Size(322, 0);
            this.label11.MaximumSize = new System.Drawing.Size(322, 0);
            this.label11.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label11.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label11.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label11.Dock = (System.Windows.Forms.DockStyle)0;
            this.label11.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label11.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.label11.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label11.TabIndex = 10;
            this.label11.TabStop = false;
            this.label11.AutoSize = true;
            this.label11.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label11.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label11.TextAlign = (System.Drawing.ContentAlignment)16;
            this.label11.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label11.UseCompatibleTextRendering = false;
            this.label11.Name = "label11";
            // panel12
            this.panel12.Text = "";
            this.panel12.AccessibleName = null;
            this.panel12.Location = new System.Drawing.Point(28, 423);
            this.panel12.Size = new System.Drawing.Size(322, 42);
            this.panel12.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel12.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel12.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel12.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.panel12.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel12.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel12.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel12.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.panel12.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel12.TabIndex = 11;
            this.panel12.TabStop = false;
            this.panel12.AutoSize = false;
            this.panel12.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel12.AutoScroll = false;
            this.panel12.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel12.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel12.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel12.Name = "panel12";
            // confirmarSenha
            this.confirmarSenha.Text = "";
            this.confirmarSenha.AccessibleName = "Confirme a senha";
            this.confirmarSenha.Location = new System.Drawing.Point(12, 12);
            this.confirmarSenha.Size = new System.Drawing.Size(298, 18);
            this.confirmarSenha.MinimumSize = new System.Drawing.Size(0, 0);
            this.confirmarSenha.MaximumSize = new System.Drawing.Size(0, 0);
            this.confirmarSenha.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.confirmarSenha.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.confirmarSenha.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.confirmarSenha.Dock = (System.Windows.Forms.DockStyle)0;
            this.confirmarSenha.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.confirmarSenha.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.confirmarSenha.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.confirmarSenha.TabIndex = 0;
            this.confirmarSenha.TabStop = true;
            this.confirmarSenha.AutoSize = true;
            this.confirmarSenha.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.confirmarSenha.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.confirmarSenha.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.confirmarSenha.ReadOnly = false;
            this.confirmarSenha.Multiline = false;
            this.confirmarSenha.MaxLength = 128;
            this.confirmarSenha.UseSystemPasswordChar = true;
            this.confirmarSenha.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.confirmarSenha.WordWrap = true;
            this.confirmarSenha.AcceptsReturn = false;
            this.confirmarSenha.AcceptsTab = false;
            this.confirmarSenha.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.confirmarSenha.Name = "confirmarSenha";
            // criar
            this.criar.Text = "CRIAR CONTA";
            this.criar.AccessibleName = null;
            this.criar.Location = new System.Drawing.Point(79, 484);
            this.criar.Size = new System.Drawing.Size(220, 40);
            this.criar.MinimumSize = new System.Drawing.Size(0, 0);
            this.criar.MaximumSize = new System.Drawing.Size(0, 0);
            this.criar.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.criar.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.criar.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.criar.Dock = (System.Windows.Forms.DockStyle)0;
            this.criar.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.criar.Margin = new System.Windows.Forms.Padding(51, 5, 0, 12);
            this.criar.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.criar.TabIndex = 12;
            this.criar.TabStop = true;
            this.criar.AutoSize = false;
            this.criar.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.criar.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.criar.TextAlign = (System.Drawing.ContentAlignment)32;
            this.criar.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.criar.UseVisualStyleBackColor = false;
            this.criar.UseCompatibleTextRendering = false;
            this.criar.FlatAppearance.BorderSize = 0;
            this.criar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.criar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.criar.Name = "criar";
            this.criar.Cursor = System.Windows.Forms.Cursors.Hand;
            // linklabel13
            this.linklabel13.Text = "Já tenho conta · Entrar";
            this.linklabel13.AccessibleName = null;
            this.linklabel13.Location = new System.Drawing.Point(28, 539);
            this.linklabel13.Size = new System.Drawing.Size(322, 26);
            this.linklabel13.MinimumSize = new System.Drawing.Size(0, 0);
            this.linklabel13.MaximumSize = new System.Drawing.Size(0, 0);
            this.linklabel13.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.linklabel13.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.linklabel13.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.linklabel13.Dock = (System.Windows.Forms.DockStyle)0;
            this.linklabel13.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.linklabel13.Margin = new System.Windows.Forms.Padding(0, 3, 0, 3);
            this.linklabel13.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.linklabel13.TabIndex = 13;
            this.linklabel13.TabStop = true;
            this.linklabel13.AutoSize = false;
            this.linklabel13.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.linklabel13.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.linklabel13.TextAlign = (System.Drawing.ContentAlignment)32;
            this.linklabel13.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.linklabel13.UseCompatibleTextRendering = false;
            this.linklabel13.LinkColor = System.Drawing.Color.FromArgb(255, 0, 112, 153);
            this.linklabel13.ActiveLinkColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.linklabel13.VisitedLinkColor = System.Drawing.Color.FromArgb(255, 0, 112, 153);
            this.linklabel13.Name = "linklabel13";
            this.linklabel13.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Controls.Add(this.picturebox1);
            this.Controls.Add(this.cartaoAcesso);
            this.cartaoAcesso.Controls.Add(this.label2);
            this.cartaoAcesso.Controls.Add(this.label3);
            this.cartaoAcesso.Controls.Add(this.label4);
            this.cartaoAcesso.Controls.Add(this.Fundo);
            this.Fundo.Controls.Add(this.nome);
            this.cartaoAcesso.Controls.Add(this.label5);
            this.cartaoAcesso.Controls.Add(this.panel6);
            this.panel6.Controls.Add(this.email);
            this.cartaoAcesso.Controls.Add(this.label7);
            this.cartaoAcesso.Controls.Add(this.panel8);
            this.panel8.Controls.Add(this.confirmarEmail);
            this.cartaoAcesso.Controls.Add(this.label9);
            this.cartaoAcesso.Controls.Add(this.panel10);
            this.panel10.Controls.Add(this.senha);
            this.cartaoAcesso.Controls.Add(this.label11);
            this.cartaoAcesso.Controls.Add(this.panel12);
            this.panel12.Controls.Add(this.confirmarSenha);
            this.cartaoAcesso.Controls.Add(this.criar);
            this.cartaoAcesso.Controls.Add(this.linklabel13);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.cartaoAcesso.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.Fundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.panel6.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.panel8.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.panel10.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.panel12.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.criar.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.Resize += new System.EventHandler(this.CentralizarAcesso);
            this.cartaoAcesso.SizeChanged += new System.EventHandler(this.CentralizarAcesso);
            this.criar.Click += new System.EventHandler(this.Criar_Click);
            this.AcceptButton = this.criar;
            this.linklabel13.Click += new System.EventHandler(this.linklabel13_Click);
            this.panel12.ResumeLayout(false);
            this.panel12.PerformLayout();
            this.panel10.ResumeLayout(false);
            this.panel10.PerformLayout();
            this.panel8.ResumeLayout(false);
            this.panel8.PerformLayout();
            this.panel6.ResumeLayout(false);
            this.panel6.PerformLayout();
            this.Fundo.ResumeLayout(false);
            this.Fundo.PerformLayout();
            this.cartaoAcesso.ResumeLayout(false);
            this.cartaoAcesso.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picturebox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.PictureBox picturebox1;
        private System.Windows.Forms.FlowLayoutPanel cartaoAcesso;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Panel Fundo;
        private System.Windows.Forms.TextBox nome;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Panel panel6;
        private System.Windows.Forms.TextBox email;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Panel panel8;
        private System.Windows.Forms.TextBox confirmarEmail;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Panel panel10;
        private System.Windows.Forms.TextBox senha;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Panel panel12;
        private System.Windows.Forms.TextBox confirmarSenha;
        private System.Windows.Forms.Button criar;
        private System.Windows.Forms.LinkLabel linklabel13;
    }
}
