namespace Tecnologia
{
    partial class MovimentoForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null) components.Dispose();
                if (BackgroundImage != null) BackgroundImage.Dispose();
                if (marcaSecundaria != null && marcaSecundaria.Image != null) marcaSecundaria.Image.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MovimentoForm));
            this.tablelayoutpanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.label3 = new System.Windows.Forms.Label();
            this.marcaSecundaria = new System.Windows.Forms.PictureBox();
            this.tabcontrol4 = new System.Windows.Forms.TabControl();
            this.tabpage5 = new System.Windows.Forms.TabPage();
            this.panel6 = new System.Windows.Forms.Panel();
            this.flowlayoutpanel7 = new System.Windows.Forms.FlowLayoutPanel();
            this.lblPeca = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.flowlayoutpanel9 = new System.Windows.Forms.FlowLayoutPanel();
            this.panel10 = new System.Windows.Forms.Panel();
            this.lblTipo = new System.Windows.Forms.Label();
            this.cmbTipo = new System.Windows.Forms.ComboBox();
            this.panel11 = new System.Windows.Forms.Panel();
            this.lblQuantidade = new System.Windows.Forms.Label();
            this.numQuantidade = new System.Windows.Forms.NumericUpDown();
            this.panel12 = new System.Windows.Forms.Panel();
            this.lblMotivo = new System.Windows.Forms.Label();
            this.txtMotivoFundo = new System.Windows.Forms.Panel();
            this.txtMotivo = new System.Windows.Forms.TextBox();
            this.lblDica = new System.Windows.Forms.Label();
            this.flowlayoutpanel13 = new System.Windows.Forms.FlowLayoutPanel();
            this.btnSalvar = new System.Windows.Forms.Button();
            this.SuspendLayout();
            this.tablelayoutpanel1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.marcaSecundaria)).BeginInit();
            this.tabcontrol4.SuspendLayout();
            this.tabpage5.SuspendLayout();
            this.panel6.SuspendLayout();
            this.flowlayoutpanel7.SuspendLayout();
            this.flowlayoutpanel9.SuspendLayout();
            this.panel10.SuspendLayout();
            this.panel11.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numQuantidade)).BeginInit();
            this.panel12.SuspendLayout();
            this.txtMotivoFundo.SuspendLayout();
            this.flowlayoutpanel13.SuspendLayout();
            // MovimentoForm
            this.Text = "Movimentar estoque";
            this.AccessibleName = null;
            this.MinimumSize = new System.Drawing.Size(780, 520);
            this.MaximumSize = new System.Drawing.Size(0, 0);
            this.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Dock = (System.Windows.Forms.DockStyle)0;
            this.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.TabIndex = 0;
            this.TabStop = true;
            this.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.AutoScroll = true;
            this.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)3;
            this.ClientSize = new System.Drawing.Size(1060, 720);
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.Name = "MovimentoForm";
            // tablelayoutpanel1
            this.tablelayoutpanel1.Text = "";
            this.tablelayoutpanel1.AccessibleName = null;
            this.tablelayoutpanel1.Location = new System.Drawing.Point(0, 0);
            this.tablelayoutpanel1.Size = new System.Drawing.Size(1028, 720);
            this.tablelayoutpanel1.MinimumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.MaximumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.tablelayoutpanel1.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.tablelayoutpanel1.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tablelayoutpanel1.Dock = (System.Windows.Forms.DockStyle)5;
            this.tablelayoutpanel1.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tablelayoutpanel1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tablelayoutpanel1.Padding = new System.Windows.Forms.Padding(22, 22, 22, 22);
            this.tablelayoutpanel1.TabIndex = 0;
            this.tablelayoutpanel1.TabStop = false;
            this.tablelayoutpanel1.AutoSize = false;
            this.tablelayoutpanel1.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tablelayoutpanel1.AutoScroll = false;
            this.tablelayoutpanel1.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tablelayoutpanel1.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tablelayoutpanel1.RowCount = 2;
            this.tablelayoutpanel1.ColumnCount = 1;
            this.tablelayoutpanel1.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.tablelayoutpanel1.Name = "tablelayoutpanel1";
            this.tablelayoutpanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 100F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)1, 78F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)2, 100F));
            // panel2
            this.panel2.Text = "";
            this.panel2.AccessibleName = null;
            this.panel2.Location = new System.Drawing.Point(25, 25);
            this.panel2.Size = new System.Drawing.Size(978, 72);
            this.panel2.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel2.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel2.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.panel2.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.panel2.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel2.Dock = (System.Windows.Forms.DockStyle)5;
            this.panel2.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel2.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.panel2.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel2.TabIndex = 0;
            this.panel2.TabStop = false;
            this.panel2.AutoSize = false;
            this.panel2.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel2.AutoScroll = false;
            this.panel2.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel2.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel2.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel2.Name = "panel2";
            // label3
            this.label3.Text = "Movimentar estoque";
            this.label3.AccessibleName = null;
            this.label3.Location = new System.Drawing.Point(0, 10);
            this.label3.Size = new System.Drawing.Size(728, 50);
            this.label3.MinimumSize = new System.Drawing.Size(0, 0);
            this.label3.MaximumSize = new System.Drawing.Size(0, 0);
            this.label3.Font = new System.Drawing.Font("Segoe UI", 22F, (System.Drawing.FontStyle)1);
            this.label3.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label3.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.label3.Dock = (System.Windows.Forms.DockStyle)0;
            this.label3.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.label3.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.label3.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label3.TabIndex = 0;
            this.label3.TabStop = false;
            this.label3.AutoSize = false;
            this.label3.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label3.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label3.TextAlign = (System.Drawing.ContentAlignment)1;
            this.label3.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label3.UseCompatibleTextRendering = false;
            this.label3.Name = "label3";
            // marcaSecundaria
            this.marcaSecundaria.Text = "";
            this.marcaSecundaria.AccessibleName = null;
            this.marcaSecundaria.Location = new System.Drawing.Point(758, 8);
            this.marcaSecundaria.Size = new System.Drawing.Size(220, 48);
            this.marcaSecundaria.MinimumSize = new System.Drawing.Size(0, 0);
            this.marcaSecundaria.MaximumSize = new System.Drawing.Size(0, 0);
            this.marcaSecundaria.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.marcaSecundaria.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.marcaSecundaria.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.marcaSecundaria.Dock = (System.Windows.Forms.DockStyle)0;
            this.marcaSecundaria.Anchor = (System.Windows.Forms.AnchorStyles)9;
            this.marcaSecundaria.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.marcaSecundaria.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.marcaSecundaria.TabIndex = 1;
            this.marcaSecundaria.TabStop = false;
            this.marcaSecundaria.AutoSize = false;
            this.marcaSecundaria.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.marcaSecundaria.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.marcaSecundaria.SizeMode = (System.Windows.Forms.PictureBoxSizeMode)4;
            this.marcaSecundaria.Image = ((System.Drawing.Image)(resources.GetObject("marcaSecundaria.Image")));
            this.marcaSecundaria.Name = "marcaSecundaria";
            // tabcontrol4
            this.tabcontrol4.Text = "";
            this.tabcontrol4.AccessibleName = null;
            this.tabcontrol4.Location = new System.Drawing.Point(25, 103);
            this.tabcontrol4.Size = new System.Drawing.Size(978, 592);
            this.tabcontrol4.MinimumSize = new System.Drawing.Size(0, 0);
            this.tabcontrol4.MaximumSize = new System.Drawing.Size(0, 0);
            this.tabcontrol4.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.tabcontrol4.BackColor = System.Drawing.Color.FromArgb(255, 240, 240, 240);
            this.tabcontrol4.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tabcontrol4.Dock = (System.Windows.Forms.DockStyle)5;
            this.tabcontrol4.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tabcontrol4.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabcontrol4.Padding = new System.Drawing.Point(20, 9);
            this.tabcontrol4.TabIndex = 1;
            this.tabcontrol4.TabStop = true;
            this.tabcontrol4.AutoSize = false;
            this.tabcontrol4.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tabcontrol4.Multiline = false;
            this.tabcontrol4.SizeMode = (System.Windows.Forms.TabSizeMode)0;
            this.tabcontrol4.Name = "tabcontrol4";
            // tabpage5
            this.tabpage5.Text = "Movimentação";
            this.tabpage5.AccessibleName = null;
            this.tabpage5.Location = new System.Drawing.Point(4, 38);
            this.tabpage5.Size = new System.Drawing.Size(970, 550);
            this.tabpage5.MinimumSize = new System.Drawing.Size(0, 0);
            this.tabpage5.MaximumSize = new System.Drawing.Size(0, 0);
            this.tabpage5.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.tabpage5.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.tabpage5.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tabpage5.Dock = (System.Windows.Forms.DockStyle)0;
            this.tabpage5.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tabpage5.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabpage5.Padding = new System.Windows.Forms.Padding(16, 16, 16, 16);
            this.tabpage5.TabIndex = 0;
            this.tabpage5.TabStop = false;
            this.tabpage5.AutoSize = false;
            this.tabpage5.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tabpage5.AutoScroll = false;
            this.tabpage5.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tabpage5.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tabpage5.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tabpage5.UseVisualStyleBackColor = false;
            this.tabpage5.Name = "tabpage5";
            // panel6
            this.panel6.Text = "";
            this.panel6.AccessibleName = null;
            this.panel6.Location = new System.Drawing.Point(16, 16);
            this.panel6.Size = new System.Drawing.Size(938, 518);
            this.panel6.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel6.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel6.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel6.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel6.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel6.Dock = (System.Windows.Forms.DockStyle)5;
            this.panel6.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel6.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.panel6.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel6.TabIndex = 0;
            this.panel6.TabStop = false;
            this.panel6.AutoSize = false;
            this.panel6.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel6.AutoScroll = true;
            this.panel6.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel6.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel6.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel6.Name = "panel6";
            // flowlayoutpanel7
            this.flowlayoutpanel7.Text = "";
            this.flowlayoutpanel7.AccessibleName = null;
            this.flowlayoutpanel7.Location = new System.Drawing.Point(0, 0);
            this.flowlayoutpanel7.Size = new System.Drawing.Size(910, 399);
            this.flowlayoutpanel7.MinimumSize = new System.Drawing.Size(910, 0);
            this.flowlayoutpanel7.MaximumSize = new System.Drawing.Size(910, 0);
            this.flowlayoutpanel7.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel7.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel7.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel7.Dock = (System.Windows.Forms.DockStyle)0;
            this.flowlayoutpanel7.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel7.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.flowlayoutpanel7.Padding = new System.Windows.Forms.Padding(10, 10, 10, 10);
            this.flowlayoutpanel7.TabIndex = 0;
            this.flowlayoutpanel7.TabStop = false;
            this.flowlayoutpanel7.AutoSize = true;
            this.flowlayoutpanel7.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.flowlayoutpanel7.AutoScroll = false;
            this.flowlayoutpanel7.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel7.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel7.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel7.FlowDirection = (System.Windows.Forms.FlowDirection)1;
            this.flowlayoutpanel7.WrapContents = false;
            this.flowlayoutpanel7.Name = "flowlayoutpanel7";
            // lblPeca
            this.lblPeca.Text = "Peça";
            this.lblPeca.AccessibleName = null;
            this.lblPeca.Location = new System.Drawing.Point(13, 10);
            this.lblPeca.Size = new System.Drawing.Size(884, 36);
            this.lblPeca.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblPeca.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblPeca.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.lblPeca.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblPeca.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblPeca.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblPeca.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.lblPeca.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblPeca.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblPeca.TabIndex = 0;
            this.lblPeca.TabStop = false;
            this.lblPeca.AutoSize = false;
            this.lblPeca.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblPeca.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblPeca.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblPeca.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblPeca.UseCompatibleTextRendering = false;
            this.lblPeca.Name = "lblPeca";
            // label8
            this.label8.Text = "Movimentar estoque";
            this.label8.AccessibleName = null;
            this.label8.Location = new System.Drawing.Point(13, 60);
            this.label8.Size = new System.Drawing.Size(884, 32);
            this.label8.MinimumSize = new System.Drawing.Size(0, 0);
            this.label8.MaximumSize = new System.Drawing.Size(0, 0);
            this.label8.Font = new System.Drawing.Font("Segoe UI", 12F, (System.Drawing.FontStyle)1);
            this.label8.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.label8.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.label8.Dock = (System.Windows.Forms.DockStyle)0;
            this.label8.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label8.Margin = new System.Windows.Forms.Padding(3, 14, 3, 4);
            this.label8.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label8.TabIndex = 1;
            this.label8.TabStop = false;
            this.label8.AutoSize = false;
            this.label8.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label8.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label8.TextAlign = (System.Drawing.ContentAlignment)1;
            this.label8.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label8.UseCompatibleTextRendering = false;
            this.label8.Name = "label8";
            // flowlayoutpanel9
            this.flowlayoutpanel9.Text = "";
            this.flowlayoutpanel9.AccessibleName = null;
            this.flowlayoutpanel9.Location = new System.Drawing.Point(10, 96);
            this.flowlayoutpanel9.Size = new System.Drawing.Size(884, 192);
            this.flowlayoutpanel9.MinimumSize = new System.Drawing.Size(884, 0);
            this.flowlayoutpanel9.MaximumSize = new System.Drawing.Size(884, 0);
            this.flowlayoutpanel9.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel9.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel9.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel9.Dock = (System.Windows.Forms.DockStyle)0;
            this.flowlayoutpanel9.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel9.Margin = new System.Windows.Forms.Padding(0, 0, 0, 10);
            this.flowlayoutpanel9.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.flowlayoutpanel9.TabIndex = 2;
            this.flowlayoutpanel9.TabStop = false;
            this.flowlayoutpanel9.AutoSize = true;
            this.flowlayoutpanel9.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.flowlayoutpanel9.AutoScroll = false;
            this.flowlayoutpanel9.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel9.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel9.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel9.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel9.WrapContents = true;
            this.flowlayoutpanel9.Name = "flowlayoutpanel9";
            // panel10
            this.panel10.Text = "";
            this.panel10.AccessibleName = null;
            this.panel10.Location = new System.Drawing.Point(3, 3);
            this.panel10.Size = new System.Drawing.Size(430, 84);
            this.panel10.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel10.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel10.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel10.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel10.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel10.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel10.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel10.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel10.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel10.TabIndex = 0;
            this.panel10.TabStop = false;
            this.panel10.AutoSize = false;
            this.panel10.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel10.AutoScroll = false;
            this.panel10.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel10.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel10.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel10.Name = "panel10";
            // lblTipo
            this.lblTipo.Text = "Movimentação";
            this.lblTipo.AccessibleName = null;
            this.lblTipo.Location = new System.Drawing.Point(0, 0);
            this.lblTipo.Size = new System.Drawing.Size(410, 25);
            this.lblTipo.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblTipo.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblTipo.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblTipo.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblTipo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblTipo.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblTipo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblTipo.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblTipo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblTipo.TabIndex = 1;
            this.lblTipo.TabStop = false;
            this.lblTipo.AutoSize = false;
            this.lblTipo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblTipo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblTipo.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblTipo.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblTipo.UseCompatibleTextRendering = false;
            this.lblTipo.Name = "lblTipo";
            // cmbTipo
            this.cmbTipo.Text = "";
            this.cmbTipo.AccessibleName = "Movimentação";
            this.cmbTipo.Location = new System.Drawing.Point(0, 32);
            this.cmbTipo.Size = new System.Drawing.Size(410, 25);
            this.cmbTipo.MinimumSize = new System.Drawing.Size(0, 0);
            this.cmbTipo.MaximumSize = new System.Drawing.Size(0, 0);
            this.cmbTipo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.cmbTipo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.cmbTipo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.cmbTipo.Dock = (System.Windows.Forms.DockStyle)0;
            this.cmbTipo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.cmbTipo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.cmbTipo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.cmbTipo.TabIndex = 0;
            this.cmbTipo.TabStop = true;
            this.cmbTipo.AutoSize = false;
            this.cmbTipo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.cmbTipo.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.cmbTipo.MaxLength = 0;
            this.cmbTipo.DropDownStyle = (System.Windows.Forms.ComboBoxStyle)2;
            this.cmbTipo.IntegralHeight = true;
            this.cmbTipo.DropDownWidth = 410;
            this.cmbTipo.MaxDropDownItems = 8;
            this.cmbTipo.Name = "cmbTipo";
            this.cmbTipo.Items.AddRange(new object[] { "Entrada", "Saída" });
            // panel11
            this.panel11.Text = "";
            this.panel11.AccessibleName = null;
            this.panel11.Location = new System.Drawing.Point(445, 3);
            this.panel11.Size = new System.Drawing.Size(430, 84);
            this.panel11.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel11.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel11.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel11.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel11.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel11.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel11.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel11.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel11.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel11.TabIndex = 1;
            this.panel11.TabStop = false;
            this.panel11.AutoSize = false;
            this.panel11.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel11.AutoScroll = false;
            this.panel11.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel11.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel11.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel11.Name = "panel11";
            // lblQuantidade
            this.lblQuantidade.Text = "Quantidade";
            this.lblQuantidade.AccessibleName = null;
            this.lblQuantidade.Location = new System.Drawing.Point(0, 0);
            this.lblQuantidade.Size = new System.Drawing.Size(410, 25);
            this.lblQuantidade.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblQuantidade.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblQuantidade.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblQuantidade.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblQuantidade.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblQuantidade.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblQuantidade.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblQuantidade.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblQuantidade.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblQuantidade.TabIndex = 3;
            this.lblQuantidade.TabStop = false;
            this.lblQuantidade.AutoSize = false;
            this.lblQuantidade.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblQuantidade.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblQuantidade.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblQuantidade.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblQuantidade.UseCompatibleTextRendering = false;
            this.lblQuantidade.Name = "lblQuantidade";
            // numQuantidade
            this.numQuantidade.Text = "1";
            this.numQuantidade.AccessibleName = "Quantidade";
            this.numQuantidade.Location = new System.Drawing.Point(0, 32);
            this.numQuantidade.Size = new System.Drawing.Size(410, 25);
            this.numQuantidade.MinimumSize = new System.Drawing.Size(0, 0);
            this.numQuantidade.MaximumSize = new System.Drawing.Size(0, 0);
            this.numQuantidade.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.numQuantidade.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.numQuantidade.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.numQuantidade.Dock = (System.Windows.Forms.DockStyle)0;
            this.numQuantidade.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.numQuantidade.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.numQuantidade.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.numQuantidade.TabIndex = 0;
            this.numQuantidade.TabStop = true;
            this.numQuantidade.AutoSize = false;
            this.numQuantidade.AutoScroll = false;
            this.numQuantidade.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.numQuantidade.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.numQuantidade.BorderStyle = (System.Windows.Forms.BorderStyle)1;
            this.numQuantidade.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.numQuantidade.ReadOnly = false;
            this.numQuantidade.Minimum = 1M;
            this.numQuantidade.Maximum = 999999M;
            this.numQuantidade.Increment = 1M;
            this.numQuantidade.DecimalPlaces = 0;
            this.numQuantidade.ThousandsSeparator = false;
            this.numQuantidade.Value = 1M;
            this.numQuantidade.Name = "numQuantidade";
            // panel12
            this.panel12.Text = "";
            this.panel12.AccessibleName = null;
            this.panel12.Location = new System.Drawing.Point(3, 99);
            this.panel12.Size = new System.Drawing.Size(430, 84);
            this.panel12.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel12.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel12.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel12.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel12.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel12.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel12.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel12.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel12.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel12.TabIndex = 2;
            this.panel12.TabStop = false;
            this.panel12.AutoSize = false;
            this.panel12.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel12.AutoScroll = false;
            this.panel12.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel12.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel12.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel12.Name = "panel12";
            // lblMotivo
            this.lblMotivo.Text = "Motivo / fornecedor";
            this.lblMotivo.AccessibleName = null;
            this.lblMotivo.Location = new System.Drawing.Point(0, 0);
            this.lblMotivo.Size = new System.Drawing.Size(410, 25);
            this.lblMotivo.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblMotivo.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblMotivo.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblMotivo.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblMotivo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblMotivo.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblMotivo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblMotivo.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblMotivo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblMotivo.TabIndex = 5;
            this.lblMotivo.TabStop = false;
            this.lblMotivo.AutoSize = false;
            this.lblMotivo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblMotivo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblMotivo.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblMotivo.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblMotivo.UseCompatibleTextRendering = false;
            this.lblMotivo.Name = "lblMotivo";
            // txtMotivoFundo
            this.txtMotivoFundo.Text = "";
            this.txtMotivoFundo.AccessibleName = null;
            this.txtMotivoFundo.Location = new System.Drawing.Point(0, 28);
            this.txtMotivoFundo.Size = new System.Drawing.Size(410, 42);
            this.txtMotivoFundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtMotivoFundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtMotivoFundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtMotivoFundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtMotivoFundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtMotivoFundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtMotivoFundo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtMotivoFundo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtMotivoFundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtMotivoFundo.TabIndex = 0;
            this.txtMotivoFundo.TabStop = false;
            this.txtMotivoFundo.AutoSize = false;
            this.txtMotivoFundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.txtMotivoFundo.AutoScroll = false;
            this.txtMotivoFundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.txtMotivoFundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtMotivoFundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtMotivoFundo.Name = "txtMotivoFundo";
            // txtMotivo
            this.txtMotivo.Text = "";
            this.txtMotivo.AccessibleName = "Motivo / fornecedor";
            this.txtMotivo.Location = new System.Drawing.Point(12, 12);
            this.txtMotivo.Size = new System.Drawing.Size(386, 18);
            this.txtMotivo.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtMotivo.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtMotivo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtMotivo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtMotivo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtMotivo.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtMotivo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtMotivo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtMotivo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtMotivo.TabIndex = 0;
            this.txtMotivo.TabStop = true;
            this.txtMotivo.AutoSize = true;
            this.txtMotivo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtMotivo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtMotivo.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.txtMotivo.ReadOnly = false;
            this.txtMotivo.Multiline = false;
            this.txtMotivo.MaxLength = 300;
            this.txtMotivo.UseSystemPasswordChar = false;
            this.txtMotivo.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.txtMotivo.WordWrap = true;
            this.txtMotivo.AcceptsReturn = false;
            this.txtMotivo.AcceptsTab = false;
            this.txtMotivo.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.txtMotivo.Name = "txtMotivo";
            // lblDica
            this.lblDica.Text = "Para utilizar uma peça em um conserto, abra a ordem de serviço.";
            this.lblDica.AccessibleName = null;
            this.lblDica.Location = new System.Drawing.Point(13, 298);
            this.lblDica.Size = new System.Drawing.Size(884, 24);
            this.lblDica.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblDica.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblDica.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.lblDica.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblDica.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblDica.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblDica.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.lblDica.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblDica.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblDica.TabIndex = 7;
            this.lblDica.TabStop = false;
            this.lblDica.AutoSize = false;
            this.lblDica.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblDica.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblDica.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblDica.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblDica.UseCompatibleTextRendering = false;
            this.lblDica.Name = "lblDica";
            // flowlayoutpanel13
            this.flowlayoutpanel13.Text = "";
            this.flowlayoutpanel13.AccessibleName = null;
            this.flowlayoutpanel13.Location = new System.Drawing.Point(13, 325);
            this.flowlayoutpanel13.Size = new System.Drawing.Size(884, 61);
            this.flowlayoutpanel13.MinimumSize = new System.Drawing.Size(884, 0);
            this.flowlayoutpanel13.MaximumSize = new System.Drawing.Size(884, 0);
            this.flowlayoutpanel13.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel13.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel13.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel13.Dock = (System.Windows.Forms.DockStyle)5;
            this.flowlayoutpanel13.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel13.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.flowlayoutpanel13.Padding = new System.Windows.Forms.Padding(0, 5, 0, 10);
            this.flowlayoutpanel13.TabIndex = 8;
            this.flowlayoutpanel13.TabStop = false;
            this.flowlayoutpanel13.AutoSize = true;
            this.flowlayoutpanel13.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.flowlayoutpanel13.AutoScroll = false;
            this.flowlayoutpanel13.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel13.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel13.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel13.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel13.WrapContents = true;
            this.flowlayoutpanel13.Name = "flowlayoutpanel13";
            // btnSalvar
            this.btnSalvar.Text = "Registrar movimentação";
            this.btnSalvar.AccessibleName = null;
            this.btnSalvar.Location = new System.Drawing.Point(0, 8);
            this.btnSalvar.Size = new System.Drawing.Size(176, 38);
            this.btnSalvar.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnSalvar.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnSalvar.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnSalvar.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnSalvar.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnSalvar.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnSalvar.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnSalvar.Margin = new System.Windows.Forms.Padding(0, 3, 10, 5);
            this.btnSalvar.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnSalvar.TabIndex = 0;
            this.btnSalvar.TabStop = true;
            this.btnSalvar.AutoSize = false;
            this.btnSalvar.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnSalvar.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnSalvar.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnSalvar.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnSalvar.UseVisualStyleBackColor = false;
            this.btnSalvar.UseCompatibleTextRendering = false;
            this.btnSalvar.FlatAppearance.BorderSize = 0;
            this.btnSalvar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnSalvar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnSalvar.Name = "btnSalvar";
            this.btnSalvar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Controls.Add(this.tablelayoutpanel1);
            this.tablelayoutpanel1.Controls.Add(this.panel2, 0, 0);
            this.panel2.Controls.Add(this.label3);
            this.panel2.Controls.Add(this.marcaSecundaria);
            this.tablelayoutpanel1.Controls.Add(this.tabcontrol4, 0, 1);
            this.tabcontrol4.Controls.Add(this.tabpage5);
            this.tabpage5.Controls.Add(this.panel6);
            this.panel6.Controls.Add(this.flowlayoutpanel7);
            this.flowlayoutpanel7.Controls.Add(this.lblPeca);
            this.flowlayoutpanel7.Controls.Add(this.label8);
            this.flowlayoutpanel7.Controls.Add(this.flowlayoutpanel9);
            this.flowlayoutpanel9.Controls.Add(this.panel10);
            this.panel10.Controls.Add(this.lblTipo);
            this.panel10.Controls.Add(this.cmbTipo);
            this.flowlayoutpanel9.Controls.Add(this.panel11);
            this.panel11.Controls.Add(this.lblQuantidade);
            this.panel11.Controls.Add(this.numQuantidade);
            this.flowlayoutpanel9.Controls.Add(this.panel12);
            this.panel12.Controls.Add(this.lblMotivo);
            this.panel12.Controls.Add(this.txtMotivoFundo);
            this.txtMotivoFundo.Controls.Add(this.txtMotivo);
            this.flowlayoutpanel7.Controls.Add(this.lblDica);
            this.flowlayoutpanel7.Controls.Add(this.flowlayoutpanel13);
            this.flowlayoutpanel13.Controls.Add(this.btnSalvar);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.btnSalvar.Click += new System.EventHandler(this.btnSalvar_Click);
            this.Load += new System.EventHandler(this.MovimentoForm_Load);
            this.txtMotivoFundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnSalvar.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.panel6.SizeChanged += new System.EventHandler(this.flowlayoutpanel7_Redimensionar);
            this.flowlayoutpanel13.ResumeLayout(false);
            this.flowlayoutpanel13.PerformLayout();
            this.txtMotivoFundo.ResumeLayout(false);
            this.txtMotivoFundo.PerformLayout();
            this.panel12.ResumeLayout(false);
            this.panel12.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numQuantidade)).EndInit();
            this.panel11.ResumeLayout(false);
            this.panel11.PerformLayout();
            this.panel10.ResumeLayout(false);
            this.panel10.PerformLayout();
            this.flowlayoutpanel9.ResumeLayout(false);
            this.flowlayoutpanel9.PerformLayout();
            this.flowlayoutpanel7.ResumeLayout(false);
            this.flowlayoutpanel7.PerformLayout();
            this.panel6.ResumeLayout(false);
            this.panel6.PerformLayout();
            this.tabpage5.ResumeLayout(false);
            this.tabpage5.PerformLayout();
            this.tabcontrol4.ResumeLayout(false);
            this.tabcontrol4.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.marcaSecundaria)).EndInit();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.tablelayoutpanel1.ResumeLayout(false);
            this.tablelayoutpanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.TableLayoutPanel tablelayoutpanel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.PictureBox marcaSecundaria;
        private System.Windows.Forms.TabControl tabcontrol4;
        private System.Windows.Forms.TabPage tabpage5;
        private System.Windows.Forms.Panel panel6;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel7;
        private System.Windows.Forms.Label lblPeca;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel9;
        private System.Windows.Forms.Panel panel10;
        private System.Windows.Forms.Label lblTipo;
        private System.Windows.Forms.ComboBox cmbTipo;
        private System.Windows.Forms.Panel panel11;
        private System.Windows.Forms.Label lblQuantidade;
        private System.Windows.Forms.NumericUpDown numQuantidade;
        private System.Windows.Forms.Panel panel12;
        private System.Windows.Forms.Label lblMotivo;
        private System.Windows.Forms.Panel txtMotivoFundo;
        private System.Windows.Forms.TextBox txtMotivo;
        private System.Windows.Forms.Label lblDica;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel13;
        private System.Windows.Forms.Button btnSalvar;
    }
}
