namespace Tecnologia
{
    partial class OrdensForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null) components.Dispose();
                if (BackgroundImage != null) BackgroundImage.Dispose();
                if (marcaSecundaria != null && marcaSecundaria.Image != null) marcaSecundaria.Image.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(OrdensForm));
            this.tablelayoutpanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.marcaSecundaria = new System.Windows.Forms.PictureBox();
            this.tabcontrol3 = new System.Windows.Forms.TabControl();
            this.tabpage4 = new System.Windows.Forms.TabPage();
            this.tablelayoutpanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.flowlayoutpanel6 = new System.Windows.Forms.FlowLayoutPanel();
            this.cmbStatus = new System.Windows.Forms.ComboBox();
            this.txtBusca = new System.Windows.Forms.TextBox();
            this.btnPesquisar = new System.Windows.Forms.Button();
            this.btnNova = new System.Windows.Forms.Button();
            this.grade = new System.Windows.Forms.DataGridView();
            this.flowlayoutpanel7 = new System.Windows.Forms.FlowLayoutPanel();
            this.btnDetalhes = new System.Windows.Forms.Button();
            this.btnExportar = new System.Windows.Forms.Button();
            this.lblDica = new System.Windows.Forms.Label();
            this.SuspendLayout();
            this.tablelayoutpanel1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.marcaSecundaria)).BeginInit();
            this.tabcontrol3.SuspendLayout();
            this.tabpage4.SuspendLayout();
            this.tablelayoutpanel5.SuspendLayout();
            this.flowlayoutpanel6.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grade)).BeginInit();
            this.flowlayoutpanel7.SuspendLayout();
            // OrdensForm
            this.Text = "Ordens de serviço";
            this.AccessibleName = null;
            this.MinimumSize = new System.Drawing.Size(780, 520);
            this.MaximumSize = new System.Drawing.Size(0, 0);
            this.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Dock = (System.Windows.Forms.DockStyle)0;
            this.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.TabIndex = 0;
            this.TabStop = true;
            this.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.AutoScroll = true;
            this.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)3;
            this.ClientSize = new System.Drawing.Size(1060, 720);
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.Name = "OrdensForm";
            // tablelayoutpanel1
            this.tablelayoutpanel1.Text = "";
            this.tablelayoutpanel1.AccessibleName = null;
            this.tablelayoutpanel1.Location = new System.Drawing.Point(0, 0);
            this.tablelayoutpanel1.Size = new System.Drawing.Size(1028, 720);
            this.tablelayoutpanel1.MinimumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.MaximumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.tablelayoutpanel1.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.tablelayoutpanel1.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tablelayoutpanel1.Dock = (System.Windows.Forms.DockStyle)5;
            this.tablelayoutpanel1.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tablelayoutpanel1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tablelayoutpanel1.Padding = new System.Windows.Forms.Padding(22, 22, 22, 22);
            this.tablelayoutpanel1.TabIndex = 0;
            this.tablelayoutpanel1.TabStop = false;
            this.tablelayoutpanel1.AutoSize = false;
            this.tablelayoutpanel1.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tablelayoutpanel1.AutoScroll = false;
            this.tablelayoutpanel1.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tablelayoutpanel1.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tablelayoutpanel1.RowCount = 2;
            this.tablelayoutpanel1.ColumnCount = 1;
            this.tablelayoutpanel1.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.tablelayoutpanel1.Name = "tablelayoutpanel1";
            this.tablelayoutpanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 100F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)1, 78F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)2, 100F));
            // panel2
            this.panel2.Text = "";
            this.panel2.AccessibleName = null;
            this.panel2.Location = new System.Drawing.Point(25, 25);
            this.panel2.Size = new System.Drawing.Size(978, 72);
            this.panel2.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel2.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel2.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.panel2.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.panel2.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel2.Dock = (System.Windows.Forms.DockStyle)5;
            this.panel2.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel2.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.panel2.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel2.TabIndex = 0;
            this.panel2.TabStop = false;
            this.panel2.AutoSize = false;
            this.panel2.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel2.AutoScroll = false;
            this.panel2.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel2.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel2.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel2.Name = "panel2";
            // lblTitulo
            this.lblTitulo.Text = "Ordens de serviço";
            this.lblTitulo.AccessibleName = null;
            this.lblTitulo.Location = new System.Drawing.Point(0, 10);
            this.lblTitulo.Size = new System.Drawing.Size(728, 50);
            this.lblTitulo.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblTitulo.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 22F, (System.Drawing.FontStyle)1);
            this.lblTitulo.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblTitulo.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.lblTitulo.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblTitulo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblTitulo.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblTitulo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.TabStop = false;
            this.lblTitulo.AutoSize = false;
            this.lblTitulo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblTitulo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblTitulo.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblTitulo.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblTitulo.UseCompatibleTextRendering = false;
            this.lblTitulo.Name = "lblTitulo";
            // marcaSecundaria
            this.marcaSecundaria.Text = "";
            this.marcaSecundaria.AccessibleName = null;
            this.marcaSecundaria.Location = new System.Drawing.Point(758, 8);
            this.marcaSecundaria.Size = new System.Drawing.Size(220, 48);
            this.marcaSecundaria.MinimumSize = new System.Drawing.Size(0, 0);
            this.marcaSecundaria.MaximumSize = new System.Drawing.Size(0, 0);
            this.marcaSecundaria.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.marcaSecundaria.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.marcaSecundaria.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.marcaSecundaria.Dock = (System.Windows.Forms.DockStyle)0;
            this.marcaSecundaria.Anchor = (System.Windows.Forms.AnchorStyles)9;
            this.marcaSecundaria.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.marcaSecundaria.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.marcaSecundaria.TabIndex = 1;
            this.marcaSecundaria.TabStop = false;
            this.marcaSecundaria.AutoSize = false;
            this.marcaSecundaria.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.marcaSecundaria.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.marcaSecundaria.SizeMode = (System.Windows.Forms.PictureBoxSizeMode)4;
            this.marcaSecundaria.Image = ((System.Drawing.Image)(resources.GetObject("marcaSecundaria.Image")));
            this.marcaSecundaria.Name = "marcaSecundaria";
            // tabcontrol3
            this.tabcontrol3.Text = "";
            this.tabcontrol3.AccessibleName = null;
            this.tabcontrol3.Location = new System.Drawing.Point(25, 103);
            this.tabcontrol3.Size = new System.Drawing.Size(978, 592);
            this.tabcontrol3.MinimumSize = new System.Drawing.Size(0, 0);
            this.tabcontrol3.MaximumSize = new System.Drawing.Size(0, 0);
            this.tabcontrol3.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.tabcontrol3.BackColor = System.Drawing.Color.FromArgb(255, 240, 240, 240);
            this.tabcontrol3.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tabcontrol3.Dock = (System.Windows.Forms.DockStyle)5;
            this.tabcontrol3.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tabcontrol3.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabcontrol3.Padding = new System.Drawing.Point(20, 9);
            this.tabcontrol3.TabIndex = 1;
            this.tabcontrol3.TabStop = true;
            this.tabcontrol3.AutoSize = false;
            this.tabcontrol3.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tabcontrol3.Multiline = false;
            this.tabcontrol3.SizeMode = (System.Windows.Forms.TabSizeMode)0;
            this.tabcontrol3.Name = "tabcontrol3";
            // tabpage4
            this.tabpage4.Text = "Ordens de serviço";
            this.tabpage4.AccessibleName = null;
            this.tabpage4.Location = new System.Drawing.Point(4, 38);
            this.tabpage4.Size = new System.Drawing.Size(970, 550);
            this.tabpage4.MinimumSize = new System.Drawing.Size(0, 0);
            this.tabpage4.MaximumSize = new System.Drawing.Size(0, 0);
            this.tabpage4.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.tabpage4.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.tabpage4.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tabpage4.Dock = (System.Windows.Forms.DockStyle)0;
            this.tabpage4.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tabpage4.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabpage4.Padding = new System.Windows.Forms.Padding(16, 16, 16, 16);
            this.tabpage4.TabIndex = 0;
            this.tabpage4.TabStop = false;
            this.tabpage4.AutoSize = false;
            this.tabpage4.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tabpage4.AutoScroll = false;
            this.tabpage4.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tabpage4.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tabpage4.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tabpage4.UseVisualStyleBackColor = false;
            this.tabpage4.Name = "tabpage4";
            // tablelayoutpanel5
            this.tablelayoutpanel5.Text = "";
            this.tablelayoutpanel5.AccessibleName = null;
            this.tablelayoutpanel5.Location = new System.Drawing.Point(16, 16);
            this.tablelayoutpanel5.Size = new System.Drawing.Size(938, 518);
            this.tablelayoutpanel5.MinimumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel5.MaximumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel5.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.tablelayoutpanel5.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.tablelayoutpanel5.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tablelayoutpanel5.Dock = (System.Windows.Forms.DockStyle)5;
            this.tablelayoutpanel5.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tablelayoutpanel5.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tablelayoutpanel5.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.tablelayoutpanel5.TabIndex = 0;
            this.tablelayoutpanel5.TabStop = false;
            this.tablelayoutpanel5.AutoSize = false;
            this.tablelayoutpanel5.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tablelayoutpanel5.AutoScroll = false;
            this.tablelayoutpanel5.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel5.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tablelayoutpanel5.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tablelayoutpanel5.RowCount = 3;
            this.tablelayoutpanel5.ColumnCount = 1;
            this.tablelayoutpanel5.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.tablelayoutpanel5.Name = "tablelayoutpanel5";
            this.tablelayoutpanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 100F));
            this.tablelayoutpanel5.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)0, 0F));
            this.tablelayoutpanel5.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)2, 100F));
            this.tablelayoutpanel5.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)0, 0F));
            // flowlayoutpanel6
            this.flowlayoutpanel6.Text = "";
            this.flowlayoutpanel6.AccessibleName = null;
            this.flowlayoutpanel6.Location = new System.Drawing.Point(3, 3);
            this.flowlayoutpanel6.Size = new System.Drawing.Size(932, 61);
            this.flowlayoutpanel6.MinimumSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel6.MaximumSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel6.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel6.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel6.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel6.Dock = (System.Windows.Forms.DockStyle)5;
            this.flowlayoutpanel6.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel6.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.flowlayoutpanel6.Padding = new System.Windows.Forms.Padding(0, 5, 0, 10);
            this.flowlayoutpanel6.TabIndex = 0;
            this.flowlayoutpanel6.TabStop = false;
            this.flowlayoutpanel6.AutoSize = true;
            this.flowlayoutpanel6.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.flowlayoutpanel6.AutoScroll = false;
            this.flowlayoutpanel6.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel6.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel6.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel6.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel6.WrapContents = true;
            this.flowlayoutpanel6.Name = "flowlayoutpanel6";
            // cmbStatus
            this.cmbStatus.Text = "";
            this.cmbStatus.AccessibleName = null;
            this.cmbStatus.Location = new System.Drawing.Point(0, 8);
            this.cmbStatus.Size = new System.Drawing.Size(180, 25);
            this.cmbStatus.MinimumSize = new System.Drawing.Size(0, 0);
            this.cmbStatus.MaximumSize = new System.Drawing.Size(0, 0);
            this.cmbStatus.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.cmbStatus.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.cmbStatus.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.cmbStatus.Dock = (System.Windows.Forms.DockStyle)0;
            this.cmbStatus.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.cmbStatus.Margin = new System.Windows.Forms.Padding(0, 3, 10, 5);
            this.cmbStatus.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.cmbStatus.TabIndex = 0;
            this.cmbStatus.TabStop = true;
            this.cmbStatus.AutoSize = false;
            this.cmbStatus.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.cmbStatus.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.cmbStatus.MaxLength = 0;
            this.cmbStatus.DropDownStyle = (System.Windows.Forms.ComboBoxStyle)2;
            this.cmbStatus.IntegralHeight = true;
            this.cmbStatus.DropDownWidth = 180;
            this.cmbStatus.MaxDropDownItems = 8;
            this.cmbStatus.Name = "cmbStatus";
            this.cmbStatus.Items.AddRange(new object[] { "Todas", "Aberta", "Em manutenção", "Aguardando peça", "Concluída", "Entregue", "Em andamento", "Concluídas e entregues" });
            // txtBusca
            this.txtBusca.Text = "";
            this.txtBusca.AccessibleName = "Pesquisar ordem, cliente ou aparelho";
            this.txtBusca.Location = new System.Drawing.Point(190, 8);
            this.txtBusca.Size = new System.Drawing.Size(250, 25);
            this.txtBusca.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtBusca.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtBusca.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtBusca.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtBusca.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtBusca.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtBusca.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.txtBusca.Margin = new System.Windows.Forms.Padding(0, 3, 10, 5);
            this.txtBusca.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtBusca.TabIndex = 1;
            this.txtBusca.TabStop = true;
            this.txtBusca.AutoSize = true;
            this.txtBusca.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtBusca.BorderStyle = (System.Windows.Forms.BorderStyle)1;
            this.txtBusca.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.txtBusca.ReadOnly = false;
            this.txtBusca.Multiline = false;
            this.txtBusca.MaxLength = 100;
            this.txtBusca.UseSystemPasswordChar = false;
            this.txtBusca.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.txtBusca.WordWrap = true;
            this.txtBusca.AcceptsReturn = false;
            this.txtBusca.AcceptsTab = false;
            this.txtBusca.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.txtBusca.Name = "txtBusca";
            // btnPesquisar
            this.btnPesquisar.Text = "Pesquisar";
            this.btnPesquisar.AccessibleName = null;
            this.btnPesquisar.Location = new System.Drawing.Point(450, 8);
            this.btnPesquisar.Size = new System.Drawing.Size(144, 38);
            this.btnPesquisar.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnPesquisar.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnPesquisar.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnPesquisar.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnPesquisar.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnPesquisar.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnPesquisar.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnPesquisar.Margin = new System.Windows.Forms.Padding(0, 3, 10, 5);
            this.btnPesquisar.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnPesquisar.TabIndex = 2;
            this.btnPesquisar.TabStop = true;
            this.btnPesquisar.AutoSize = false;
            this.btnPesquisar.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnPesquisar.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnPesquisar.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnPesquisar.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnPesquisar.UseVisualStyleBackColor = false;
            this.btnPesquisar.UseCompatibleTextRendering = false;
            this.btnPesquisar.FlatAppearance.BorderSize = 0;
            this.btnPesquisar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnPesquisar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnPesquisar.Name = "btnPesquisar";
            this.btnPesquisar.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnNova
            this.btnNova.Text = "Abrir nova ordem";
            this.btnNova.AccessibleName = null;
            this.btnNova.Location = new System.Drawing.Point(604, 8);
            this.btnNova.Size = new System.Drawing.Size(144, 38);
            this.btnNova.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnNova.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnNova.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnNova.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnNova.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnNova.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnNova.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnNova.Margin = new System.Windows.Forms.Padding(0, 3, 10, 5);
            this.btnNova.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnNova.TabIndex = 3;
            this.btnNova.TabStop = true;
            this.btnNova.AutoSize = false;
            this.btnNova.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnNova.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnNova.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnNova.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnNova.UseVisualStyleBackColor = false;
            this.btnNova.UseCompatibleTextRendering = false;
            this.btnNova.FlatAppearance.BorderSize = 0;
            this.btnNova.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnNova.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnNova.Name = "btnNova";
            this.btnNova.Cursor = System.Windows.Forms.Cursors.Hand;
            // grade
            this.grade.Text = "";
            this.grade.AccessibleName = null;
            this.grade.Location = new System.Drawing.Point(3, 70);
            this.grade.Size = new System.Drawing.Size(932, 378);
            this.grade.MinimumSize = new System.Drawing.Size(0, 0);
            this.grade.MaximumSize = new System.Drawing.Size(0, 0);
            this.grade.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.grade.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.grade.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.grade.Dock = (System.Windows.Forms.DockStyle)5;
            this.grade.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.grade.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.grade.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.grade.TabIndex = 8;
            this.grade.TabStop = true;
            this.grade.AutoSize = false;
            this.grade.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.grade.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.grade.ReadOnly = true;
            this.grade.ScrollBars = (System.Windows.Forms.ScrollBars)3;
            this.grade.AllowUserToAddRows = false;
            this.grade.AllowUserToDeleteRows = false;
            this.grade.AllowUserToResizeRows = true;
            this.grade.AutoSizeColumnsMode = (System.Windows.Forms.DataGridViewAutoSizeColumnsMode)10;
            this.grade.AutoSizeRowsMode = (System.Windows.Forms.DataGridViewAutoSizeRowsMode)0;
            this.grade.MultiSelect = false;
            this.grade.SelectionMode = (System.Windows.Forms.DataGridViewSelectionMode)1;
            this.grade.RowHeadersVisible = false;
            this.grade.ColumnHeadersHeight = 34;
            this.grade.ColumnHeadersHeightSizeMode = (System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode)0;
            this.grade.EnableHeadersVisualStyles = false;
            this.grade.GridColor = System.Drawing.Color.FromArgb(255, 218, 228, 220);
            this.grade.BackgroundColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.grade.RowTemplate.Height = 28;
            this.grade.Name = "grade";
            System.Windows.Forms.DataGridViewCellStyle gradeDefaultCellStyle = new System.Windows.Forms.DataGridViewCellStyle();
            gradeDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            gradeDefaultCellStyle.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            gradeDefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(255, 200, 243, 219);
            gradeDefaultCellStyle.SelectionForeColor = System.Drawing.Color.FromArgb(255, 20, 66, 43);
            gradeDefaultCellStyle.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            gradeDefaultCellStyle.Alignment = (System.Windows.Forms.DataGridViewContentAlignment)16;
            gradeDefaultCellStyle.WrapMode = (System.Windows.Forms.DataGridViewTriState)2;
            gradeDefaultCellStyle.Format = "";
            this.grade.DefaultCellStyle = gradeDefaultCellStyle;
            System.Windows.Forms.DataGridViewCellStyle gradeColumnHeadersDefaultCellStyle = new System.Windows.Forms.DataGridViewCellStyle();
            gradeColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            gradeColumnHeadersDefaultCellStyle.ForeColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            gradeColumnHeadersDefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(255, 0, 120, 215);
            gradeColumnHeadersDefaultCellStyle.SelectionForeColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            gradeColumnHeadersDefaultCellStyle.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            gradeColumnHeadersDefaultCellStyle.Alignment = (System.Windows.Forms.DataGridViewContentAlignment)16;
            gradeColumnHeadersDefaultCellStyle.WrapMode = (System.Windows.Forms.DataGridViewTriState)1;
            gradeColumnHeadersDefaultCellStyle.Format = "";
            this.grade.ColumnHeadersDefaultCellStyle = gradeColumnHeadersDefaultCellStyle;
            System.Windows.Forms.DataGridViewCellStyle gradeAlternatingRowsDefaultCellStyle = new System.Windows.Forms.DataGridViewCellStyle();
            gradeAlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(255, 243, 248, 245);
            gradeAlternatingRowsDefaultCellStyle.Alignment = (System.Windows.Forms.DataGridViewContentAlignment)0;
            gradeAlternatingRowsDefaultCellStyle.WrapMode = (System.Windows.Forms.DataGridViewTriState)0;
            gradeAlternatingRowsDefaultCellStyle.Format = "";
            this.grade.AlternatingRowsDefaultCellStyle = gradeAlternatingRowsDefaultCellStyle;
            // flowlayoutpanel7
            this.flowlayoutpanel7.Text = "";
            this.flowlayoutpanel7.AccessibleName = null;
            this.flowlayoutpanel7.Location = new System.Drawing.Point(3, 454);
            this.flowlayoutpanel7.Size = new System.Drawing.Size(932, 61);
            this.flowlayoutpanel7.MinimumSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel7.MaximumSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel7.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel7.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel7.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel7.Dock = (System.Windows.Forms.DockStyle)5;
            this.flowlayoutpanel7.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel7.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.flowlayoutpanel7.Padding = new System.Windows.Forms.Padding(0, 5, 0, 10);
            this.flowlayoutpanel7.TabIndex = 9;
            this.flowlayoutpanel7.TabStop = false;
            this.flowlayoutpanel7.AutoSize = true;
            this.flowlayoutpanel7.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.flowlayoutpanel7.AutoScroll = false;
            this.flowlayoutpanel7.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel7.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel7.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel7.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel7.WrapContents = true;
            this.flowlayoutpanel7.Name = "flowlayoutpanel7";
            // btnDetalhes
            this.btnDetalhes.Text = "Ver ordem selecionada";
            this.btnDetalhes.AccessibleName = null;
            this.btnDetalhes.Location = new System.Drawing.Point(0, 8);
            this.btnDetalhes.Size = new System.Drawing.Size(165, 38);
            this.btnDetalhes.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnDetalhes.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnDetalhes.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnDetalhes.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnDetalhes.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnDetalhes.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnDetalhes.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnDetalhes.Margin = new System.Windows.Forms.Padding(0, 3, 10, 5);
            this.btnDetalhes.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnDetalhes.TabIndex = 0;
            this.btnDetalhes.TabStop = true;
            this.btnDetalhes.AutoSize = false;
            this.btnDetalhes.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnDetalhes.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnDetalhes.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnDetalhes.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnDetalhes.UseVisualStyleBackColor = false;
            this.btnDetalhes.UseCompatibleTextRendering = false;
            this.btnDetalhes.FlatAppearance.BorderSize = 0;
            this.btnDetalhes.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnDetalhes.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnDetalhes.Name = "btnDetalhes";
            this.btnDetalhes.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnExportar
            this.btnExportar.Text = "Exportar Excel";
            this.btnExportar.AccessibleName = null;
            this.btnExportar.Location = new System.Drawing.Point(175, 8);
            this.btnExportar.Size = new System.Drawing.Size(144, 38);
            this.btnExportar.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnExportar.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnExportar.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnExportar.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnExportar.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnExportar.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnExportar.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnExportar.Margin = new System.Windows.Forms.Padding(0, 3, 10, 5);
            this.btnExportar.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnExportar.TabIndex = 1;
            this.btnExportar.TabStop = true;
            this.btnExportar.AutoSize = false;
            this.btnExportar.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnExportar.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnExportar.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnExportar.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnExportar.UseVisualStyleBackColor = false;
            this.btnExportar.UseCompatibleTextRendering = false;
            this.btnExportar.FlatAppearance.BorderSize = 0;
            this.btnExportar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnExportar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnExportar.Name = "btnExportar";
            this.btnExportar.Cursor = System.Windows.Forms.Cursors.Hand;
            // lblDica
            this.lblDica.Text = "Pesquise por número, cliente, aparelho ou técnico.";
            this.lblDica.AccessibleName = null;
            this.lblDica.Location = new System.Drawing.Point(329, 8);
            this.lblDica.Size = new System.Drawing.Size(314, 19);
            this.lblDica.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblDica.MaximumSize = new System.Drawing.Size(580, 0);
            this.lblDica.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.lblDica.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblDica.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblDica.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblDica.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.lblDica.Margin = new System.Windows.Forms.Padding(0, 3, 10, 5);
            this.lblDica.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblDica.TabIndex = 2;
            this.lblDica.TabStop = false;
            this.lblDica.AutoSize = true;
            this.lblDica.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblDica.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblDica.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblDica.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblDica.UseCompatibleTextRendering = false;
            this.lblDica.Name = "lblDica";
            this.Controls.Add(this.tablelayoutpanel1);
            this.tablelayoutpanel1.Controls.Add(this.panel2, 0, 0);
            this.panel2.Controls.Add(this.lblTitulo);
            this.panel2.Controls.Add(this.marcaSecundaria);
            this.tablelayoutpanel1.Controls.Add(this.tabcontrol3, 0, 1);
            this.tabcontrol3.Controls.Add(this.tabpage4);
            this.tabpage4.Controls.Add(this.tablelayoutpanel5);
            this.tablelayoutpanel5.Controls.Add(this.flowlayoutpanel6, 0, 0);
            this.flowlayoutpanel6.Controls.Add(this.cmbStatus);
            this.flowlayoutpanel6.Controls.Add(this.txtBusca);
            this.flowlayoutpanel6.Controls.Add(this.btnPesquisar);
            this.flowlayoutpanel6.Controls.Add(this.btnNova);
            this.tablelayoutpanel5.Controls.Add(this.grade, 0, 1);
            this.tablelayoutpanel5.Controls.Add(this.flowlayoutpanel7, 0, 2);
            this.flowlayoutpanel7.Controls.Add(this.btnDetalhes);
            this.flowlayoutpanel7.Controls.Add(this.btnExportar);
            this.flowlayoutpanel7.Controls.Add(this.lblDica);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.btnPesquisar.Click += new System.EventHandler(this.btnPesquisar_Click);
            this.btnExportar.Click += new System.EventHandler(this.btnExportar_Click);
            this.btnNova.Click += new System.EventHandler(this.btnNova_Click);
            this.btnDetalhes.Click += new System.EventHandler(this.btnDetalhes_Click);
            this.Load += new System.EventHandler(this.OrdensForm_Load);
            this.btnPesquisar.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnNova.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnDetalhes.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnExportar.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.flowlayoutpanel7.ResumeLayout(false);
            this.flowlayoutpanel7.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.grade)).EndInit();
            this.flowlayoutpanel6.ResumeLayout(false);
            this.flowlayoutpanel6.PerformLayout();
            this.tablelayoutpanel5.ResumeLayout(false);
            this.tablelayoutpanel5.PerformLayout();
            this.tabpage4.ResumeLayout(false);
            this.tabpage4.PerformLayout();
            this.tabcontrol3.ResumeLayout(false);
            this.tabcontrol3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.marcaSecundaria)).EndInit();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.tablelayoutpanel1.ResumeLayout(false);
            this.tablelayoutpanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.TableLayoutPanel tablelayoutpanel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.PictureBox marcaSecundaria;
        private System.Windows.Forms.TabControl tabcontrol3;
        private System.Windows.Forms.TabPage tabpage4;
        private System.Windows.Forms.TableLayoutPanel tablelayoutpanel5;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel6;
        private System.Windows.Forms.ComboBox cmbStatus;
        private System.Windows.Forms.TextBox txtBusca;
        private System.Windows.Forms.Button btnPesquisar;
        private System.Windows.Forms.Button btnNova;
        private System.Windows.Forms.DataGridView grade;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel7;
        private System.Windows.Forms.Button btnDetalhes;
        private System.Windows.Forms.Button btnExportar;
        private System.Windows.Forms.Label lblDica;
    }
}
