namespace Tecnologia
{
    partial class OrdemForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Location = new System.Drawing.Point(22, 10);
            this.lblTitulo.Size = new System.Drawing.Size(1050, 24);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Ordem de serviço";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblTitulo);
            this.txtRecebimento = new System.Windows.Forms.TextBox();
            this.txtRecebimento.Name = "txtRecebimento";
            this.txtRecebimento.Location = new System.Drawing.Point(22, 45);
            this.txtRecebimento.Size = new System.Drawing.Size(1076, 124);
            this.txtRecebimento.TabIndex = 1;
            this.txtRecebimento.MaxLength = 100;
            this.txtRecebimento.Multiline=true;
            this.txtRecebimento.ReadOnly=true;
            this.txtRecebimento.ScrollBars=System.Windows.Forms.ScrollBars.Vertical;
            this.txtRecebimento.MaxLength=10000;
            this.Controls.Add(this.txtRecebimento);
            this.lblDiagnostico = new System.Windows.Forms.Label();
            this.lblDiagnostico.Name = "lblDiagnostico";
            this.lblDiagnostico.Location = new System.Drawing.Point(22, 178);
            this.lblDiagnostico.Size = new System.Drawing.Size(520, 24);
            this.lblDiagnostico.TabIndex = 2;
            this.lblDiagnostico.Text = "Diagnóstico";
            this.lblDiagnostico.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblDiagnostico);
            this.lblServico = new System.Windows.Forms.Label();
            this.lblServico.Name = "lblServico";
            this.lblServico.Location = new System.Drawing.Point(574, 178);
            this.lblServico.Size = new System.Drawing.Size(520, 24);
            this.lblServico.TabIndex = 3;
            this.lblServico.Text = "Serviço necessário / realizado";
            this.lblServico.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblServico);
            this.txtDiagnostico = new System.Windows.Forms.TextBox();
            this.txtDiagnostico.Name = "txtDiagnostico";
            this.txtDiagnostico.Location = new System.Drawing.Point(22, 204);
            this.txtDiagnostico.Size = new System.Drawing.Size(524, 76);
            this.txtDiagnostico.TabIndex = 4;
            this.txtDiagnostico.MaxLength = 100;
            this.txtDiagnostico.Multiline=true;
            this.txtDiagnostico.MaxLength=3000;
            this.txtDiagnostico.ScrollBars=System.Windows.Forms.ScrollBars.Vertical;
            this.Controls.Add(this.txtDiagnostico);
            this.txtServico = new System.Windows.Forms.TextBox();
            this.txtServico.Name = "txtServico";
            this.txtServico.Location = new System.Drawing.Point(574, 204);
            this.txtServico.Size = new System.Drawing.Size(524, 76);
            this.txtServico.TabIndex = 5;
            this.txtServico.MaxLength = 100;
            this.txtServico.Multiline=true;
            this.txtServico.MaxLength=2000;
            this.txtServico.ScrollBars=System.Windows.Forms.ScrollBars.Vertical;
            this.Controls.Add(this.txtServico);
            this.lblStatus = new System.Windows.Forms.Label();
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Location = new System.Drawing.Point(22, 288);
            this.lblStatus.Size = new System.Drawing.Size(240, 24);
            this.lblStatus.TabIndex = 6;
            this.lblStatus.Text = "Andamento";
            this.lblStatus.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblStatus);
            this.cmbStatus = new System.Windows.Forms.ComboBox();
            this.cmbStatus.Name = "cmbStatus";
            this.cmbStatus.Location = new System.Drawing.Point(22, 314);
            this.cmbStatus.Size = new System.Drawing.Size(250, 26);
            this.cmbStatus.TabIndex = 7;
            this.cmbStatus.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbStatus.Items.AddRange(new object[] { "Em manutenção", "Aguardando peça", "Concluída", "Entregue" });
            this.Controls.Add(this.cmbStatus);
            this.lblMaoObra = new System.Windows.Forms.Label();
            this.lblMaoObra.Name = "lblMaoObra";
            this.lblMaoObra.Location = new System.Drawing.Point(292, 288);
            this.lblMaoObra.Size = new System.Drawing.Size(200, 24);
            this.lblMaoObra.TabIndex = 8;
            this.lblMaoObra.Text = "Mão de obra (R$)";
            this.lblMaoObra.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblMaoObra);
            this.numMaoObra = new System.Windows.Forms.NumericUpDown();
            this.numMaoObra.Name = "numMaoObra";
            this.numMaoObra.Location = new System.Drawing.Point(292, 314);
            this.numMaoObra.Size = new System.Drawing.Size(230, 26);
            this.numMaoObra.TabIndex = 9;
            this.numMaoObra.Maximum = 999999;
            this.numMaoObra.DecimalPlaces = 0;
            this.numMaoObra.DecimalPlaces=2;
            this.numMaoObra.Maximum=99999999;
            this.Controls.Add(this.numMaoObra);
            this.lblDesconto = new System.Windows.Forms.Label();
            this.lblDesconto.Name = "lblDesconto";
            this.lblDesconto.Location = new System.Drawing.Point(542, 288);
            this.lblDesconto.Size = new System.Drawing.Size(200, 24);
            this.lblDesconto.TabIndex = 10;
            this.lblDesconto.Text = "Desconto (R$)";
            this.lblDesconto.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblDesconto);
            this.numDesconto = new System.Windows.Forms.NumericUpDown();
            this.numDesconto.Name = "numDesconto";
            this.numDesconto.Location = new System.Drawing.Point(542, 314);
            this.numDesconto.Size = new System.Drawing.Size(230, 26);
            this.numDesconto.TabIndex = 11;
            this.numDesconto.Maximum = 999999;
            this.numDesconto.DecimalPlaces = 0;
            this.numDesconto.DecimalPlaces=2;
            this.numDesconto.Maximum=99999999;
            this.Controls.Add(this.numDesconto);
            this.lblTotal = new System.Windows.Forms.Label();
            this.lblTotal.Name = "lblTotal";
            this.lblTotal.Location = new System.Drawing.Point(798, 314);
            this.lblTotal.Size = new System.Drawing.Size(300, 24);
            this.lblTotal.TabIndex = 12;
            this.lblTotal.Text = "Total salvo:";
            this.lblTotal.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblTotal);
            this.btnSalvar = new System.Windows.Forms.Button();
            this.btnSalvar.Name = "btnSalvar";
            this.btnSalvar.Location = new System.Drawing.Point(22, 354);
            this.btnSalvar.Size = new System.Drawing.Size(288, 34);
            this.btnSalvar.TabIndex = 13;
            this.btnSalvar.Text = "Salvar diagnóstico e andamento";
            this.btnSalvar.UseVisualStyleBackColor = true;
            this.btnSalvar.Click += new System.EventHandler(this.btnSalvar_Click);
            this.Controls.Add(this.btnSalvar);
            this.btnEntregar = new System.Windows.Forms.Button();
            this.btnEntregar.Name = "btnEntregar";
            this.btnEntregar.Location = new System.Drawing.Point(328, 354);
            this.btnEntregar.Size = new System.Drawing.Size(210, 34);
            this.btnEntregar.TabIndex = 14;
            this.btnEntregar.Text = "Registrar entrega";
            this.btnEntregar.UseVisualStyleBackColor = true;
            this.btnEntregar.Click += new System.EventHandler(this.btnEntregar_Click);
            this.Controls.Add(this.btnEntregar);
            this.btnHistorico = new System.Windows.Forms.Button();
            this.btnHistorico.Name = "btnHistorico";
            this.btnHistorico.Location = new System.Drawing.Point(556, 354);
            this.btnHistorico.Size = new System.Drawing.Size(210, 34);
            this.btnHistorico.TabIndex = 15;
            this.btnHistorico.Text = "Histórico da ordem";
            this.btnHistorico.UseVisualStyleBackColor = true;
            this.btnHistorico.Click += new System.EventHandler(this.btnHistorico_Click);
            this.Controls.Add(this.btnHistorico);
            this.btnAtualizar = new System.Windows.Forms.Button();
            this.btnAtualizar.Name = "btnAtualizar";
            this.btnAtualizar.Location = new System.Drawing.Point(784, 354);
            this.btnAtualizar.Size = new System.Drawing.Size(200, 34);
            this.btnAtualizar.TabIndex = 16;
            this.btnAtualizar.Text = "Recarregar ordem";
            this.btnAtualizar.UseVisualStyleBackColor = true;
            this.btnAtualizar.Click += new System.EventHandler(this.btnAtualizar_Click);
            this.Controls.Add(this.btnAtualizar);
            this.lblPecas = new System.Windows.Forms.Label();
            this.lblPecas.Name = "lblPecas";
            this.lblPecas.Location = new System.Drawing.Point(22, 399);
            this.lblPecas.Size = new System.Drawing.Size(720, 24);
            this.lblPecas.TabIndex = 17;
            this.lblPecas.Text = "Peças compatíveis disponíveis no estoque";
            this.lblPecas.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblPecas);
            this.cmbPeca = new System.Windows.Forms.ComboBox();
            this.cmbPeca.Name = "cmbPeca";
            this.cmbPeca.Location = new System.Drawing.Point(22, 426);
            this.cmbPeca.Size = new System.Drawing.Size(620, 26);
            this.cmbPeca.TabIndex = 18;
            this.cmbPeca.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.Controls.Add(this.cmbPeca);
            this.numQuantidade = new System.Windows.Forms.NumericUpDown();
            this.numQuantidade.Name = "numQuantidade";
            this.numQuantidade.Location = new System.Drawing.Point(662, 426);
            this.numQuantidade.Size = new System.Drawing.Size(112, 26);
            this.numQuantidade.TabIndex = 19;
            this.numQuantidade.Maximum = 999999;
            this.numQuantidade.DecimalPlaces = 0;
            this.numQuantidade.Minimum=1;
            this.numQuantidade.Value=1;
            this.Controls.Add(this.numQuantidade);
            this.btnAdicionar = new System.Windows.Forms.Button();
            this.btnAdicionar.Name = "btnAdicionar";
            this.btnAdicionar.Location = new System.Drawing.Point(794, 421);
            this.btnAdicionar.Size = new System.Drawing.Size(304, 34);
            this.btnAdicionar.TabIndex = 20;
            this.btnAdicionar.Text = "Usar peça na ordem";
            this.btnAdicionar.UseVisualStyleBackColor = true;
            this.btnAdicionar.Click += new System.EventHandler(this.btnAdicionar_Click);
            this.Controls.Add(this.btnAdicionar);
            this.grade = new System.Windows.Forms.DataGridView();
            this.grade.Name = "grade";
            this.grade.Location = new System.Drawing.Point(22, 475);
            this.grade.Size = new System.Drawing.Size(1076, 172);
            this.grade.TabIndex = 21;
            this.grade.ReadOnly = true;
            this.grade.AllowUserToAddRows = false;
            this.grade.AllowUserToDeleteRows = false;
            this.grade.MultiSelect = false;
            this.grade.RowHeadersVisible = false;
            this.grade.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.grade.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.grade.BackgroundColor = System.Drawing.Color.White;
            this.grade.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.Controls.Add(this.grade);
            this.btnDevolver = new System.Windows.Forms.Button();
            this.btnDevolver.Name = "btnDevolver";
            this.btnDevolver.Location = new System.Drawing.Point(22, 662);
            this.btnDevolver.Size = new System.Drawing.Size(265, 34);
            this.btnDevolver.TabIndex = 22;
            this.btnDevolver.Text = "Devolver peça selecionada";
            this.btnDevolver.UseVisualStyleBackColor = true;
            this.btnDevolver.Click += new System.EventHandler(this.btnDevolver_Click);
            this.Controls.Add(this.btnDevolver);
            this.btnExportar = new System.Windows.Forms.Button();
            this.btnExportar.Name = "btnExportar";
            this.btnExportar.Location = new System.Drawing.Point(305, 662);
            this.btnExportar.Size = new System.Drawing.Size(265, 34);
            this.btnExportar.TabIndex = 23;
            this.btnExportar.Text = "Exportar peças para Excel";
            this.btnExportar.UseVisualStyleBackColor = true;
            this.btnExportar.Click += new System.EventHandler(this.btnExportar_Click);
            this.Controls.Add(this.btnExportar);
            this.lblDica = new System.Windows.Forms.Label();
            this.lblDica.Name = "lblDica";
            this.lblDica.Location = new System.Drawing.Point(22, 710);
            this.lblDica.Size = new System.Drawing.Size(1076, 24);
            this.lblDica.TabIndex = 24;
            this.lblDica.Text = "Salve o diagnóstico antes de usar peças. Após concluir, a ordem fica bloqueada.";
            this.lblDica.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblDica);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(1120, 752);
            this.MinimumSize = new System.Drawing.Size(1120, 752);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Ordem de serviço";
            this.Name = "OrdemForm";
            this.Load += new System.EventHandler(this.OrdemForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.TextBox txtRecebimento;
        private System.Windows.Forms.Label lblDiagnostico;
        private System.Windows.Forms.Label lblServico;
        private System.Windows.Forms.TextBox txtDiagnostico;
        private System.Windows.Forms.TextBox txtServico;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.ComboBox cmbStatus;
        private System.Windows.Forms.Label lblMaoObra;
        private System.Windows.Forms.NumericUpDown numMaoObra;
        private System.Windows.Forms.Label lblDesconto;
        private System.Windows.Forms.NumericUpDown numDesconto;
        private System.Windows.Forms.Label lblTotal;
        private System.Windows.Forms.Button btnSalvar;
        private System.Windows.Forms.Button btnEntregar;
        private System.Windows.Forms.Button btnHistorico;
        private System.Windows.Forms.Button btnAtualizar;
        private System.Windows.Forms.Label lblPecas;
        private System.Windows.Forms.ComboBox cmbPeca;
        private System.Windows.Forms.NumericUpDown numQuantidade;
        private System.Windows.Forms.Button btnAdicionar;
        private System.Windows.Forms.DataGridView grade;
        private System.Windows.Forms.Button btnDevolver;
        private System.Windows.Forms.Button btnExportar;
        private System.Windows.Forms.Label lblDica;
    }
}
