namespace Tecnologia
{
    partial class PecasForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Location = new System.Drawing.Point(22, 14);
            this.lblTitulo.Size = new System.Drawing.Size(900, 24);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Peças e estoque";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblTitulo);
            this.cmbCampo = new System.Windows.Forms.ComboBox();
            this.cmbCampo.Name = "cmbCampo";
            this.cmbCampo.Location = new System.Drawing.Point(22, 55);
            this.cmbCampo.Size = new System.Drawing.Size(180, 26);
            this.cmbCampo.TabIndex = 1;
            this.cmbCampo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCampo.Items.AddRange(new object[] { "Nome", "Código da peça", "Modelo compatível", "Marca", "Tipo" });
            this.Controls.Add(this.cmbCampo);
            this.txtBusca = new System.Windows.Forms.TextBox();
            this.txtBusca.Name = "txtBusca";
            this.txtBusca.Location = new System.Drawing.Point(216, 55);
            this.txtBusca.Size = new System.Drawing.Size(350, 26);
            this.txtBusca.TabIndex = 2;
            this.txtBusca.MaxLength = 100;
            this.txtBusca.MaxLength = 100;
            this.Controls.Add(this.txtBusca);
            this.btnPesquisar = new System.Windows.Forms.Button();
            this.btnPesquisar.Name = "btnPesquisar";
            this.btnPesquisar.Location = new System.Drawing.Point(580, 50);
            this.btnPesquisar.Size = new System.Drawing.Size(142, 34);
            this.btnPesquisar.TabIndex = 3;
            this.btnPesquisar.Text = "Pesquisar";
            this.btnPesquisar.UseVisualStyleBackColor = true;
            this.btnPesquisar.Click += new System.EventHandler(this.btnPesquisar_Click);
            this.Controls.Add(this.btnPesquisar);
            this.btnExportar = new System.Windows.Forms.Button();
            this.btnExportar.Name = "btnExportar";
            this.btnExportar.Location = new System.Drawing.Point(738, 50);
            this.btnExportar.Size = new System.Drawing.Size(142, 34);
            this.btnExportar.TabIndex = 4;
            this.btnExportar.Text = "Exportar Excel";
            this.btnExportar.UseVisualStyleBackColor = true;
            this.btnExportar.Click += new System.EventHandler(this.btnExportar_Click);
            this.Controls.Add(this.btnExportar);
            this.lblcodigo = new System.Windows.Forms.Label();
            this.lblcodigo.Name = "lblcodigo";
            this.lblcodigo.Location = new System.Drawing.Point(22, 102);
            this.lblcodigo.Size = new System.Drawing.Size(320, 24);
            this.lblcodigo.TabIndex = 5;
            this.lblcodigo.Text = "Código da peça";
            this.lblcodigo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblcodigo);
            this.campocodigo = new System.Windows.Forms.TextBox();
            this.campocodigo.Name = "campocodigo";
            this.campocodigo.Location = new System.Drawing.Point(22, 126);
            this.campocodigo.Size = new System.Drawing.Size(338, 26);
            this.campocodigo.TabIndex = 6;
            this.campocodigo.MaxLength = 100;
            this.campocodigo.MaxLength = 40;
            this.Controls.Add(this.campocodigo);
            this.lblnome = new System.Windows.Forms.Label();
            this.lblnome.Name = "lblnome";
            this.lblnome.Location = new System.Drawing.Point(382, 102);
            this.lblnome.Size = new System.Drawing.Size(320, 24);
            this.lblnome.TabIndex = 7;
            this.lblnome.Text = "Nome da peça";
            this.lblnome.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblnome);
            this.camponome = new System.Windows.Forms.TextBox();
            this.camponome.Name = "camponome";
            this.camponome.Location = new System.Drawing.Point(382, 126);
            this.camponome.Size = new System.Drawing.Size(338, 26);
            this.camponome.TabIndex = 8;
            this.camponome.MaxLength = 100;
            this.camponome.MaxLength = 100;
            this.Controls.Add(this.camponome);
            this.lbltipo = new System.Windows.Forms.Label();
            this.lbltipo.Name = "lbltipo";
            this.lbltipo.Location = new System.Drawing.Point(742, 102);
            this.lbltipo.Size = new System.Drawing.Size(320, 24);
            this.lbltipo.TabIndex = 9;
            this.lbltipo.Text = "Tipo de aparelho";
            this.lbltipo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lbltipo);
            this.campotipo = new System.Windows.Forms.ComboBox();
            this.campotipo.Name = "campotipo";
            this.campotipo.Location = new System.Drawing.Point(742, 126);
            this.campotipo.Size = new System.Drawing.Size(338, 26);
            this.campotipo.TabIndex = 10;
            this.campotipo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.campotipo.Items.AddRange(new object[] { "Celular", "Notebook", "PC" });
            this.Controls.Add(this.campotipo);
            this.lblmarca = new System.Windows.Forms.Label();
            this.lblmarca.Name = "lblmarca";
            this.lblmarca.Location = new System.Drawing.Point(22, 158);
            this.lblmarca.Size = new System.Drawing.Size(320, 24);
            this.lblmarca.TabIndex = 11;
            this.lblmarca.Text = "Marca compatível (* = todas)";
            this.lblmarca.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblmarca);
            this.campomarca = new System.Windows.Forms.TextBox();
            this.campomarca.Name = "campomarca";
            this.campomarca.Location = new System.Drawing.Point(22, 182);
            this.campomarca.Size = new System.Drawing.Size(338, 26);
            this.campomarca.TabIndex = 12;
            this.campomarca.MaxLength = 100;
            this.campomarca.MaxLength = 80;
            this.Controls.Add(this.campomarca);
            this.lblmodelo_compativel = new System.Windows.Forms.Label();
            this.lblmodelo_compativel.Name = "lblmodelo_compativel";
            this.lblmodelo_compativel.Location = new System.Drawing.Point(382, 158);
            this.lblmodelo_compativel.Size = new System.Drawing.Size(320, 24);
            this.lblmodelo_compativel.TabIndex = 13;
            this.lblmodelo_compativel.Text = "Modelo compatível (* = todos)";
            this.lblmodelo_compativel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblmodelo_compativel);
            this.campomodelo_compativel = new System.Windows.Forms.TextBox();
            this.campomodelo_compativel.Name = "campomodelo_compativel";
            this.campomodelo_compativel.Location = new System.Drawing.Point(382, 182);
            this.campomodelo_compativel.Size = new System.Drawing.Size(338, 26);
            this.campomodelo_compativel.TabIndex = 14;
            this.campomodelo_compativel.MaxLength = 100;
            this.campomodelo_compativel.MaxLength = 100;
            this.Controls.Add(this.campomodelo_compativel);
            this.lblestoque_minimo = new System.Windows.Forms.Label();
            this.lblestoque_minimo.Name = "lblestoque_minimo";
            this.lblestoque_minimo.Location = new System.Drawing.Point(742, 158);
            this.lblestoque_minimo.Size = new System.Drawing.Size(320, 24);
            this.lblestoque_minimo.TabIndex = 15;
            this.lblestoque_minimo.Text = "Estoque mínimo";
            this.lblestoque_minimo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblestoque_minimo);
            this.campoestoque_minimo = new System.Windows.Forms.NumericUpDown();
            this.campoestoque_minimo.Name = "campoestoque_minimo";
            this.campoestoque_minimo.Location = new System.Drawing.Point(742, 182);
            this.campoestoque_minimo.Size = new System.Drawing.Size(338, 26);
            this.campoestoque_minimo.TabIndex = 16;
            this.campoestoque_minimo.Maximum = 999999;
            this.campoestoque_minimo.DecimalPlaces = 0;
            this.Controls.Add(this.campoestoque_minimo);
            this.lblvalor_compra = new System.Windows.Forms.Label();
            this.lblvalor_compra.Name = "lblvalor_compra";
            this.lblvalor_compra.Location = new System.Drawing.Point(22, 214);
            this.lblvalor_compra.Size = new System.Drawing.Size(320, 24);
            this.lblvalor_compra.TabIndex = 17;
            this.lblvalor_compra.Text = "Valor de compra (R$)";
            this.lblvalor_compra.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblvalor_compra);
            this.campovalor_compra = new System.Windows.Forms.NumericUpDown();
            this.campovalor_compra.Name = "campovalor_compra";
            this.campovalor_compra.Location = new System.Drawing.Point(22, 238);
            this.campovalor_compra.Size = new System.Drawing.Size(338, 26);
            this.campovalor_compra.TabIndex = 18;
            this.campovalor_compra.Maximum = 999999;
            this.campovalor_compra.DecimalPlaces = 0;
            this.campovalor_compra.DecimalPlaces = 2;
            this.campovalor_compra.Maximum = 99999999;
            this.Controls.Add(this.campovalor_compra);
            this.lblvalor_venda = new System.Windows.Forms.Label();
            this.lblvalor_venda.Name = "lblvalor_venda";
            this.lblvalor_venda.Location = new System.Drawing.Point(382, 214);
            this.lblvalor_venda.Size = new System.Drawing.Size(320, 24);
            this.lblvalor_venda.TabIndex = 19;
            this.lblvalor_venda.Text = "Valor de venda (R$)";
            this.lblvalor_venda.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblvalor_venda);
            this.campovalor_venda = new System.Windows.Forms.NumericUpDown();
            this.campovalor_venda.Name = "campovalor_venda";
            this.campovalor_venda.Location = new System.Drawing.Point(382, 238);
            this.campovalor_venda.Size = new System.Drawing.Size(338, 26);
            this.campovalor_venda.TabIndex = 20;
            this.campovalor_venda.Maximum = 999999;
            this.campovalor_venda.DecimalPlaces = 0;
            this.campovalor_venda.DecimalPlaces = 2;
            this.campovalor_venda.Maximum = 99999999;
            this.Controls.Add(this.campovalor_venda);
            this.lblativo = new System.Windows.Forms.Label();
            this.lblativo.Name = "lblativo";
            this.lblativo.Location = new System.Drawing.Point(742, 214);
            this.lblativo.Size = new System.Drawing.Size(320, 24);
            this.lblativo.TabIndex = 21;
            this.lblativo.Text = "Peça ativa";
            this.lblativo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblativo);
            this.campoativo = new System.Windows.Forms.CheckBox();
            this.campoativo.Name = "campoativo";
            this.campoativo.Location = new System.Drawing.Point(742, 238);
            this.campoativo.Size = new System.Drawing.Size(338, 26);
            this.campoativo.TabIndex = 22;
            this.campoativo.Text = "Sim";
            this.Controls.Add(this.campoativo);
            this.btnNovo = new System.Windows.Forms.Button();
            this.btnNovo.Name = "btnNovo";
            this.btnNovo.Location = new System.Drawing.Point(22, 340);
            this.btnNovo.Size = new System.Drawing.Size(142, 34);
            this.btnNovo.TabIndex = 23;
            this.btnNovo.Text = "Novo / limpar";
            this.btnNovo.UseVisualStyleBackColor = true;
            this.btnNovo.Click += new System.EventHandler(this.btnNovo_Click);
            this.Controls.Add(this.btnNovo);
            this.btnSalvar = new System.Windows.Forms.Button();
            this.btnSalvar.Name = "btnSalvar";
            this.btnSalvar.Location = new System.Drawing.Point(178, 340);
            this.btnSalvar.Size = new System.Drawing.Size(142, 34);
            this.btnSalvar.TabIndex = 24;
            this.btnSalvar.Text = "Salvar";
            this.btnSalvar.UseVisualStyleBackColor = true;
            this.btnSalvar.Click += new System.EventHandler(this.btnSalvar_Click);
            this.Controls.Add(this.btnSalvar);
            this.btnEditar = new System.Windows.Forms.Button();
            this.btnEditar.Name = "btnEditar";
            this.btnEditar.Location = new System.Drawing.Point(334, 340);
            this.btnEditar.Size = new System.Drawing.Size(170, 34);
            this.btnEditar.TabIndex = 25;
            this.btnEditar.Text = "Editar selecionado";
            this.btnEditar.UseVisualStyleBackColor = true;
            this.btnEditar.Click += new System.EventHandler(this.btnEditar_Click);
            this.Controls.Add(this.btnEditar);
            this.btnExcluir = new System.Windows.Forms.Button();
            this.btnExcluir.Name = "btnExcluir";
            this.btnExcluir.Location = new System.Drawing.Point(518, 340);
            this.btnExcluir.Size = new System.Drawing.Size(170, 34);
            this.btnExcluir.TabIndex = 26;
            this.btnExcluir.Text = "Excluir selecionado";
            this.btnExcluir.UseVisualStyleBackColor = true;
            this.btnExcluir.Click += new System.EventHandler(this.btnExcluir_Click);
            this.Controls.Add(this.btnExcluir);
            this.lblEdicao = new System.Windows.Forms.Label();
            this.lblEdicao.Name = "lblEdicao";
            this.lblEdicao.Location = new System.Drawing.Point(22, 656);
            this.lblEdicao.Size = new System.Drawing.Size(365, 24);
            this.lblEdicao.TabIndex = 27;
            this.lblEdicao.Text = "Novo cadastro";
            this.lblEdicao.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblEdicao);
            this.grade = new System.Windows.Forms.DataGridView();
            this.grade.Name = "grade";
            this.grade.Location = new System.Drawing.Point(22, 390);
            this.grade.Size = new System.Drawing.Size(1076, 260);
            this.grade.TabIndex = 28;
            this.grade.ReadOnly = true;
            this.grade.AllowUserToAddRows = false;
            this.grade.AllowUserToDeleteRows = false;
            this.grade.MultiSelect = false;
            this.grade.RowHeadersVisible = false;
            this.grade.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.grade.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.grade.BackgroundColor = System.Drawing.Color.White;
            this.grade.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.Controls.Add(this.grade);
            this.btnMovimentar = new System.Windows.Forms.Button();
            this.btnMovimentar.Name = "btnMovimentar";
            this.btnMovimentar.Location = new System.Drawing.Point(730, 340);
            this.btnMovimentar.Size = new System.Drawing.Size(184, 34);
            this.btnMovimentar.TabIndex = 29;
            this.btnMovimentar.Text = "Movimentar estoque";
            this.btnMovimentar.UseVisualStyleBackColor = true;
            this.btnMovimentar.Click += new System.EventHandler(this.btnMovimentar_Click);
            this.Controls.Add(this.btnMovimentar);
            this.btnHistorico = new System.Windows.Forms.Button();
            this.btnHistorico.Name = "btnHistorico";
            this.btnHistorico.Location = new System.Drawing.Point(928, 340);
            this.btnHistorico.Size = new System.Drawing.Size(170, 34);
            this.btnHistorico.TabIndex = 30;
            this.btnHistorico.Text = "Histórico";
            this.btnHistorico.UseVisualStyleBackColor = true;
            this.btnHistorico.Click += new System.EventHandler(this.btnHistorico_Click);
            this.Controls.Add(this.btnHistorico);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(1120, 680);
            this.MinimumSize = new System.Drawing.Size(1120, 680);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Peças e estoque";
            this.Name = "PecasForm";
            this.Load += new System.EventHandler(this.PecasForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.ComboBox cmbCampo;
        private System.Windows.Forms.TextBox txtBusca;
        private System.Windows.Forms.Button btnPesquisar;
        private System.Windows.Forms.Button btnExportar;
        private System.Windows.Forms.Label lblcodigo;
        private System.Windows.Forms.TextBox campocodigo;
        private System.Windows.Forms.Label lblnome;
        private System.Windows.Forms.TextBox camponome;
        private System.Windows.Forms.Label lbltipo;
        private System.Windows.Forms.ComboBox campotipo;
        private System.Windows.Forms.Label lblmarca;
        private System.Windows.Forms.TextBox campomarca;
        private System.Windows.Forms.Label lblmodelo_compativel;
        private System.Windows.Forms.TextBox campomodelo_compativel;
        private System.Windows.Forms.Label lblestoque_minimo;
        private System.Windows.Forms.NumericUpDown campoestoque_minimo;
        private System.Windows.Forms.Label lblvalor_compra;
        private System.Windows.Forms.NumericUpDown campovalor_compra;
        private System.Windows.Forms.Label lblvalor_venda;
        private System.Windows.Forms.NumericUpDown campovalor_venda;
        private System.Windows.Forms.Label lblativo;
        private System.Windows.Forms.CheckBox campoativo;
        private System.Windows.Forms.Button btnNovo;
        private System.Windows.Forms.Button btnSalvar;
        private System.Windows.Forms.Button btnEditar;
        private System.Windows.Forms.Button btnExcluir;
        private System.Windows.Forms.Label lblEdicao;
        private System.Windows.Forms.DataGridView grade;
        private System.Windows.Forms.Button btnMovimentar;
        private System.Windows.Forms.Button btnHistorico;
    }
}
