namespace Tecnologia
{
    partial class PerfilForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Location = new System.Drawing.Point(22, 14);
            this.lblTitulo.Size = new System.Drawing.Size(320, 24);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Meus dados";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblTitulo);
            this.lblNome = new System.Windows.Forms.Label();
            this.lblNome.Name = "lblNome";
            this.lblNome.Location = new System.Drawing.Point(22, 62);
            this.lblNome.Size = new System.Drawing.Size(320, 24);
            this.lblNome.TabIndex = 1;
            this.lblNome.Text = "Nome";
            this.lblNome.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblNome);
            this.txtNome = new System.Windows.Forms.TextBox();
            this.txtNome.Name = "txtNome";
            this.txtNome.Location = new System.Drawing.Point(22, 88);
            this.txtNome.Size = new System.Drawing.Size(496, 26);
            this.txtNome.TabIndex = 2;
            this.txtNome.MaxLength = 100;
            this.txtNome.MaxLength = 100;
            this.Controls.Add(this.txtNome);
            this.lblEmail = new System.Windows.Forms.Label();
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.Location = new System.Drawing.Point(22, 130);
            this.lblEmail.Size = new System.Drawing.Size(320, 24);
            this.lblEmail.TabIndex = 3;
            this.lblEmail.Text = "E-mail";
            this.lblEmail.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblEmail);
            this.txtEmail = new System.Windows.Forms.TextBox();
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.Location = new System.Drawing.Point(22, 156);
            this.txtEmail.Size = new System.Drawing.Size(496, 26);
            this.txtEmail.TabIndex = 4;
            this.txtEmail.MaxLength = 100;
            this.txtEmail.MaxLength = 100;
            this.Controls.Add(this.txtEmail);
            this.lblTelefone = new System.Windows.Forms.Label();
            this.lblTelefone.Name = "lblTelefone";
            this.lblTelefone.Location = new System.Drawing.Point(22, 198);
            this.lblTelefone.Size = new System.Drawing.Size(320, 24);
            this.lblTelefone.TabIndex = 5;
            this.lblTelefone.Text = "Telefone";
            this.lblTelefone.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblTelefone);
            this.txtTelefone = new System.Windows.Forms.TextBox();
            this.txtTelefone.Name = "txtTelefone";
            this.txtTelefone.Location = new System.Drawing.Point(22, 224);
            this.txtTelefone.Size = new System.Drawing.Size(496, 26);
            this.txtTelefone.TabIndex = 6;
            this.txtTelefone.MaxLength = 100;
            this.txtTelefone.MaxLength = 20;
            this.Controls.Add(this.txtTelefone);
            this.lblAtual = new System.Windows.Forms.Label();
            this.lblAtual.Name = "lblAtual";
            this.lblAtual.Location = new System.Drawing.Point(22, 266);
            this.lblAtual.Size = new System.Drawing.Size(496, 24);
            this.lblAtual.TabIndex = 7;
            this.lblAtual.Text = "Senha atual (para confirmar as alterações)";
            this.lblAtual.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblAtual);
            this.txtAtual = new System.Windows.Forms.TextBox();
            this.txtAtual.Name = "txtAtual";
            this.txtAtual.Location = new System.Drawing.Point(22, 292);
            this.txtAtual.Size = new System.Drawing.Size(496, 26);
            this.txtAtual.TabIndex = 8;
            this.txtAtual.MaxLength = 100;
            this.txtAtual.UseSystemPasswordChar = true;
            this.txtAtual.MaxLength = 128;
            this.Controls.Add(this.txtAtual);
            this.lblNova = new System.Windows.Forms.Label();
            this.lblNova.Name = "lblNova";
            this.lblNova.Location = new System.Drawing.Point(22, 334);
            this.lblNova.Size = new System.Drawing.Size(496, 24);
            this.lblNova.TabIndex = 9;
            this.lblNova.Text = "Nova senha (deixe vazia para manter)";
            this.lblNova.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblNova);
            this.txtNova = new System.Windows.Forms.TextBox();
            this.txtNova.Name = "txtNova";
            this.txtNova.Location = new System.Drawing.Point(22, 360);
            this.txtNova.Size = new System.Drawing.Size(496, 26);
            this.txtNova.TabIndex = 10;
            this.txtNova.MaxLength = 100;
            this.txtNova.UseSystemPasswordChar = true;
            this.txtNova.MaxLength = 128;
            this.Controls.Add(this.txtNova);
            this.lblConfirmacao = new System.Windows.Forms.Label();
            this.lblConfirmacao.Name = "lblConfirmacao";
            this.lblConfirmacao.Location = new System.Drawing.Point(22, 402);
            this.lblConfirmacao.Size = new System.Drawing.Size(496, 24);
            this.lblConfirmacao.TabIndex = 11;
            this.lblConfirmacao.Text = "Confirme a nova senha";
            this.lblConfirmacao.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblConfirmacao);
            this.txtConfirmacao = new System.Windows.Forms.TextBox();
            this.txtConfirmacao.Name = "txtConfirmacao";
            this.txtConfirmacao.Location = new System.Drawing.Point(22, 428);
            this.txtConfirmacao.Size = new System.Drawing.Size(496, 26);
            this.txtConfirmacao.TabIndex = 12;
            this.txtConfirmacao.MaxLength = 100;
            this.txtConfirmacao.UseSystemPasswordChar = true;
            this.txtConfirmacao.MaxLength = 128;
            this.Controls.Add(this.txtConfirmacao);
            this.btnSalvar = new System.Windows.Forms.Button();
            this.btnSalvar.Name = "btnSalvar";
            this.btnSalvar.Location = new System.Drawing.Point(22, 490);
            this.btnSalvar.Size = new System.Drawing.Size(496, 34);
            this.btnSalvar.TabIndex = 13;
            this.btnSalvar.Text = "Salvar meus dados";
            this.btnSalvar.UseVisualStyleBackColor = true;
            this.btnSalvar.Click += new System.EventHandler(this.btnSalvar_Click);
            this.Controls.Add(this.btnSalvar);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(540, 550);
            this.MinimumSize = new System.Drawing.Size(540, 550);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Minha conta";
            this.Name = "PerfilForm";
            this.Load += new System.EventHandler(this.PerfilForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblNome;
        private System.Windows.Forms.TextBox txtNome;
        private System.Windows.Forms.Label lblEmail;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.Label lblTelefone;
        private System.Windows.Forms.TextBox txtTelefone;
        private System.Windows.Forms.Label lblAtual;
        private System.Windows.Forms.TextBox txtAtual;
        private System.Windows.Forms.Label lblNova;
        private System.Windows.Forms.TextBox txtNova;
        private System.Windows.Forms.Label lblConfirmacao;
        private System.Windows.Forms.TextBox txtConfirmacao;
        private System.Windows.Forms.Button btnSalvar;
    }
}
