namespace Tecnologia
{
    partial class PerfilForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null) components.Dispose();
                if (BackgroundImage != null) BackgroundImage.Dispose();
                if (marcaSecundaria != null && marcaSecundaria.Image != null) marcaSecundaria.Image.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PerfilForm));
            this.tablelayoutpanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.marcaSecundaria = new System.Windows.Forms.PictureBox();
            this.tabcontrol3 = new System.Windows.Forms.TabControl();
            this.tabpage4 = new System.Windows.Forms.TabPage();
            this.panel5 = new System.Windows.Forms.Panel();
            this.flowlayoutpanel6 = new System.Windows.Forms.FlowLayoutPanel();
            this.label7 = new System.Windows.Forms.Label();
            this.flowlayoutpanel8 = new System.Windows.Forms.FlowLayoutPanel();
            this.panel9 = new System.Windows.Forms.Panel();
            this.lblNome = new System.Windows.Forms.Label();
            this.txtNomeFundo = new System.Windows.Forms.Panel();
            this.txtNome = new System.Windows.Forms.TextBox();
            this.panel10 = new System.Windows.Forms.Panel();
            this.lblEmail = new System.Windows.Forms.Label();
            this.txtEmailFundo = new System.Windows.Forms.Panel();
            this.txtEmail = new System.Windows.Forms.TextBox();
            this.panel11 = new System.Windows.Forms.Panel();
            this.lblTelefone = new System.Windows.Forms.Label();
            this.txtTelefoneFundo = new System.Windows.Forms.Panel();
            this.txtTelefone = new System.Windows.Forms.TextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.flowlayoutpanel13 = new System.Windows.Forms.FlowLayoutPanel();
            this.panel14 = new System.Windows.Forms.Panel();
            this.lblAtual = new System.Windows.Forms.Label();
            this.txtAtualFundo = new System.Windows.Forms.Panel();
            this.txtAtual = new System.Windows.Forms.TextBox();
            this.panel15 = new System.Windows.Forms.Panel();
            this.lblNova = new System.Windows.Forms.Label();
            this.txtNovaFundo = new System.Windows.Forms.Panel();
            this.txtNova = new System.Windows.Forms.TextBox();
            this.panel16 = new System.Windows.Forms.Panel();
            this.lblConfirmacao = new System.Windows.Forms.Label();
            this.txtConfirmacaoFundo = new System.Windows.Forms.Panel();
            this.txtConfirmacao = new System.Windows.Forms.TextBox();
            this.flowlayoutpanel17 = new System.Windows.Forms.FlowLayoutPanel();
            this.btnSalvar = new System.Windows.Forms.Button();
            this.SuspendLayout();
            this.tablelayoutpanel1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.marcaSecundaria)).BeginInit();
            this.tabcontrol3.SuspendLayout();
            this.tabpage4.SuspendLayout();
            this.panel5.SuspendLayout();
            this.flowlayoutpanel6.SuspendLayout();
            this.flowlayoutpanel8.SuspendLayout();
            this.panel9.SuspendLayout();
            this.txtNomeFundo.SuspendLayout();
            this.panel10.SuspendLayout();
            this.txtEmailFundo.SuspendLayout();
            this.panel11.SuspendLayout();
            this.txtTelefoneFundo.SuspendLayout();
            this.flowlayoutpanel13.SuspendLayout();
            this.panel14.SuspendLayout();
            this.txtAtualFundo.SuspendLayout();
            this.panel15.SuspendLayout();
            this.txtNovaFundo.SuspendLayout();
            this.panel16.SuspendLayout();
            this.txtConfirmacaoFundo.SuspendLayout();
            this.flowlayoutpanel17.SuspendLayout();
            // PerfilForm
            this.Text = "Minha conta";
            this.AccessibleName = null;
            this.MinimumSize = new System.Drawing.Size(780, 520);
            this.MaximumSize = new System.Drawing.Size(0, 0);
            this.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Dock = (System.Windows.Forms.DockStyle)0;
            this.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.TabIndex = 0;
            this.TabStop = true;
            this.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.AutoScroll = true;
            this.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)3;
            this.ClientSize = new System.Drawing.Size(1060, 720);
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.Name = "PerfilForm";
            // tablelayoutpanel1
            this.tablelayoutpanel1.Text = "";
            this.tablelayoutpanel1.AccessibleName = null;
            this.tablelayoutpanel1.Location = new System.Drawing.Point(0, 0);
            this.tablelayoutpanel1.Size = new System.Drawing.Size(1028, 720);
            this.tablelayoutpanel1.MinimumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.MaximumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.tablelayoutpanel1.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.tablelayoutpanel1.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tablelayoutpanel1.Dock = (System.Windows.Forms.DockStyle)5;
            this.tablelayoutpanel1.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tablelayoutpanel1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tablelayoutpanel1.Padding = new System.Windows.Forms.Padding(22, 22, 22, 22);
            this.tablelayoutpanel1.TabIndex = 0;
            this.tablelayoutpanel1.TabStop = false;
            this.tablelayoutpanel1.AutoSize = false;
            this.tablelayoutpanel1.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tablelayoutpanel1.AutoScroll = false;
            this.tablelayoutpanel1.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tablelayoutpanel1.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tablelayoutpanel1.RowCount = 2;
            this.tablelayoutpanel1.ColumnCount = 1;
            this.tablelayoutpanel1.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.tablelayoutpanel1.Name = "tablelayoutpanel1";
            this.tablelayoutpanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 100F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)1, 78F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)2, 100F));
            // panel2
            this.panel2.Text = "";
            this.panel2.AccessibleName = null;
            this.panel2.Location = new System.Drawing.Point(25, 25);
            this.panel2.Size = new System.Drawing.Size(978, 72);
            this.panel2.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel2.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel2.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.panel2.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.panel2.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel2.Dock = (System.Windows.Forms.DockStyle)5;
            this.panel2.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel2.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.panel2.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel2.TabIndex = 0;
            this.panel2.TabStop = false;
            this.panel2.AutoSize = false;
            this.panel2.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel2.AutoScroll = false;
            this.panel2.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel2.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel2.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel2.Name = "panel2";
            // lblTitulo
            this.lblTitulo.Text = "Meus dados";
            this.lblTitulo.AccessibleName = null;
            this.lblTitulo.Location = new System.Drawing.Point(0, 10);
            this.lblTitulo.Size = new System.Drawing.Size(728, 50);
            this.lblTitulo.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblTitulo.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 22F, (System.Drawing.FontStyle)1);
            this.lblTitulo.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblTitulo.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.lblTitulo.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblTitulo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblTitulo.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblTitulo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.TabStop = false;
            this.lblTitulo.AutoSize = false;
            this.lblTitulo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblTitulo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblTitulo.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblTitulo.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblTitulo.UseCompatibleTextRendering = false;
            this.lblTitulo.Name = "lblTitulo";
            // marcaSecundaria
            this.marcaSecundaria.Text = "";
            this.marcaSecundaria.AccessibleName = null;
            this.marcaSecundaria.Location = new System.Drawing.Point(758, 8);
            this.marcaSecundaria.Size = new System.Drawing.Size(220, 48);
            this.marcaSecundaria.MinimumSize = new System.Drawing.Size(0, 0);
            this.marcaSecundaria.MaximumSize = new System.Drawing.Size(0, 0);
            this.marcaSecundaria.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.marcaSecundaria.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.marcaSecundaria.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.marcaSecundaria.Dock = (System.Windows.Forms.DockStyle)0;
            this.marcaSecundaria.Anchor = (System.Windows.Forms.AnchorStyles)9;
            this.marcaSecundaria.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.marcaSecundaria.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.marcaSecundaria.TabIndex = 1;
            this.marcaSecundaria.TabStop = false;
            this.marcaSecundaria.AutoSize = false;
            this.marcaSecundaria.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.marcaSecundaria.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.marcaSecundaria.SizeMode = (System.Windows.Forms.PictureBoxSizeMode)4;
            this.marcaSecundaria.Image = ((System.Drawing.Image)(resources.GetObject("marcaSecundaria.Image")));
            this.marcaSecundaria.Name = "marcaSecundaria";
            // tabcontrol3
            this.tabcontrol3.Text = "";
            this.tabcontrol3.AccessibleName = null;
            this.tabcontrol3.Location = new System.Drawing.Point(25, 103);
            this.tabcontrol3.Size = new System.Drawing.Size(978, 592);
            this.tabcontrol3.MinimumSize = new System.Drawing.Size(0, 0);
            this.tabcontrol3.MaximumSize = new System.Drawing.Size(0, 0);
            this.tabcontrol3.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.tabcontrol3.BackColor = System.Drawing.Color.FromArgb(255, 240, 240, 240);
            this.tabcontrol3.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tabcontrol3.Dock = (System.Windows.Forms.DockStyle)5;
            this.tabcontrol3.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tabcontrol3.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabcontrol3.Padding = new System.Drawing.Point(20, 9);
            this.tabcontrol3.TabIndex = 1;
            this.tabcontrol3.TabStop = true;
            this.tabcontrol3.AutoSize = false;
            this.tabcontrol3.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tabcontrol3.Multiline = false;
            this.tabcontrol3.SizeMode = (System.Windows.Forms.TabSizeMode)0;
            this.tabcontrol3.Name = "tabcontrol3";
            // tabpage4
            this.tabpage4.Text = "Conta / Perfil";
            this.tabpage4.AccessibleName = null;
            this.tabpage4.Location = new System.Drawing.Point(4, 38);
            this.tabpage4.Size = new System.Drawing.Size(970, 550);
            this.tabpage4.MinimumSize = new System.Drawing.Size(0, 0);
            this.tabpage4.MaximumSize = new System.Drawing.Size(0, 0);
            this.tabpage4.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.tabpage4.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.tabpage4.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tabpage4.Dock = (System.Windows.Forms.DockStyle)0;
            this.tabpage4.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tabpage4.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabpage4.Padding = new System.Windows.Forms.Padding(16, 16, 16, 16);
            this.tabpage4.TabIndex = 0;
            this.tabpage4.TabStop = false;
            this.tabpage4.AutoSize = false;
            this.tabpage4.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tabpage4.AutoScroll = false;
            this.tabpage4.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tabpage4.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tabpage4.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tabpage4.UseVisualStyleBackColor = false;
            this.tabpage4.Name = "tabpage4";
            // panel5
            this.panel5.Text = "";
            this.panel5.AccessibleName = null;
            this.panel5.Location = new System.Drawing.Point(16, 16);
            this.panel5.Size = new System.Drawing.Size(938, 518);
            this.panel5.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel5.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel5.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel5.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel5.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel5.Dock = (System.Windows.Forms.DockStyle)5;
            this.panel5.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel5.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.panel5.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel5.TabIndex = 0;
            this.panel5.TabStop = false;
            this.panel5.AutoSize = false;
            this.panel5.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel5.AutoScroll = true;
            this.panel5.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel5.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel5.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel5.Name = "panel5";
            // flowlayoutpanel6
            this.flowlayoutpanel6.Text = "";
            this.flowlayoutpanel6.AccessibleName = null;
            this.flowlayoutpanel6.Location = new System.Drawing.Point(0, 0);
            this.flowlayoutpanel6.Size = new System.Drawing.Size(893, 591);
            this.flowlayoutpanel6.MinimumSize = new System.Drawing.Size(893, 0);
            this.flowlayoutpanel6.MaximumSize = new System.Drawing.Size(893, 0);
            this.flowlayoutpanel6.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel6.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel6.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel6.Dock = (System.Windows.Forms.DockStyle)0;
            this.flowlayoutpanel6.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel6.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.flowlayoutpanel6.Padding = new System.Windows.Forms.Padding(10, 10, 10, 10);
            this.flowlayoutpanel6.TabIndex = 0;
            this.flowlayoutpanel6.TabStop = false;
            this.flowlayoutpanel6.AutoSize = true;
            this.flowlayoutpanel6.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.flowlayoutpanel6.AutoScroll = false;
            this.flowlayoutpanel6.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel6.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel6.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel6.FlowDirection = (System.Windows.Forms.FlowDirection)1;
            this.flowlayoutpanel6.WrapContents = false;
            this.flowlayoutpanel6.Name = "flowlayoutpanel6";
            // label7
            this.label7.Text = "Meus dados";
            this.label7.AccessibleName = null;
            this.label7.Location = new System.Drawing.Point(13, 24);
            this.label7.Size = new System.Drawing.Size(867, 32);
            this.label7.MinimumSize = new System.Drawing.Size(0, 0);
            this.label7.MaximumSize = new System.Drawing.Size(0, 0);
            this.label7.Font = new System.Drawing.Font("Segoe UI", 12F, (System.Drawing.FontStyle)1);
            this.label7.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.label7.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.label7.Dock = (System.Windows.Forms.DockStyle)0;
            this.label7.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label7.Margin = new System.Windows.Forms.Padding(3, 14, 3, 4);
            this.label7.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label7.TabIndex = 0;
            this.label7.TabStop = false;
            this.label7.AutoSize = false;
            this.label7.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label7.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label7.TextAlign = (System.Drawing.ContentAlignment)1;
            this.label7.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label7.UseCompatibleTextRendering = false;
            this.label7.Name = "label7";
            // flowlayoutpanel8
            this.flowlayoutpanel8.Text = "";
            this.flowlayoutpanel8.AccessibleName = null;
            this.flowlayoutpanel8.Location = new System.Drawing.Point(10, 60);
            this.flowlayoutpanel8.Size = new System.Drawing.Size(867, 192);
            this.flowlayoutpanel8.MinimumSize = new System.Drawing.Size(867, 0);
            this.flowlayoutpanel8.MaximumSize = new System.Drawing.Size(867, 0);
            this.flowlayoutpanel8.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel8.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel8.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel8.Dock = (System.Windows.Forms.DockStyle)0;
            this.flowlayoutpanel8.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel8.Margin = new System.Windows.Forms.Padding(0, 0, 0, 10);
            this.flowlayoutpanel8.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.flowlayoutpanel8.TabIndex = 1;
            this.flowlayoutpanel8.TabStop = false;
            this.flowlayoutpanel8.AutoSize = true;
            this.flowlayoutpanel8.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.flowlayoutpanel8.AutoScroll = false;
            this.flowlayoutpanel8.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel8.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel8.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel8.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel8.WrapContents = true;
            this.flowlayoutpanel8.Name = "flowlayoutpanel8";
            // panel9
            this.panel9.Text = "";
            this.panel9.AccessibleName = null;
            this.panel9.Location = new System.Drawing.Point(3, 3);
            this.panel9.Size = new System.Drawing.Size(421, 84);
            this.panel9.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel9.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel9.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel9.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel9.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel9.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel9.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel9.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel9.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel9.TabIndex = 0;
            this.panel9.TabStop = false;
            this.panel9.AutoSize = false;
            this.panel9.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel9.AutoScroll = false;
            this.panel9.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel9.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel9.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel9.Name = "panel9";
            // lblNome
            this.lblNome.Text = "Nome";
            this.lblNome.AccessibleName = null;
            this.lblNome.Location = new System.Drawing.Point(0, 0);
            this.lblNome.Size = new System.Drawing.Size(401, 25);
            this.lblNome.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblNome.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblNome.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblNome.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblNome.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblNome.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblNome.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblNome.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblNome.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblNome.TabIndex = 1;
            this.lblNome.TabStop = false;
            this.lblNome.AutoSize = false;
            this.lblNome.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblNome.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblNome.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblNome.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblNome.UseCompatibleTextRendering = false;
            this.lblNome.Name = "lblNome";
            // txtNomeFundo
            this.txtNomeFundo.Text = "";
            this.txtNomeFundo.AccessibleName = null;
            this.txtNomeFundo.Location = new System.Drawing.Point(0, 28);
            this.txtNomeFundo.Size = new System.Drawing.Size(401, 42);
            this.txtNomeFundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtNomeFundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtNomeFundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtNomeFundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtNomeFundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtNomeFundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtNomeFundo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtNomeFundo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtNomeFundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtNomeFundo.TabIndex = 0;
            this.txtNomeFundo.TabStop = false;
            this.txtNomeFundo.AutoSize = false;
            this.txtNomeFundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.txtNomeFundo.AutoScroll = false;
            this.txtNomeFundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.txtNomeFundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtNomeFundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtNomeFundo.Name = "txtNomeFundo";
            // txtNome
            this.txtNome.Text = "";
            this.txtNome.AccessibleName = "Nome";
            this.txtNome.Location = new System.Drawing.Point(12, 12);
            this.txtNome.Size = new System.Drawing.Size(377, 18);
            this.txtNome.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtNome.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtNome.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtNome.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtNome.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtNome.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtNome.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtNome.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtNome.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtNome.TabIndex = 0;
            this.txtNome.TabStop = true;
            this.txtNome.AutoSize = true;
            this.txtNome.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtNome.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtNome.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.txtNome.ReadOnly = false;
            this.txtNome.Multiline = false;
            this.txtNome.MaxLength = 100;
            this.txtNome.UseSystemPasswordChar = false;
            this.txtNome.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.txtNome.WordWrap = true;
            this.txtNome.AcceptsReturn = false;
            this.txtNome.AcceptsTab = false;
            this.txtNome.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.txtNome.Name = "txtNome";
            // panel10
            this.panel10.Text = "";
            this.panel10.AccessibleName = null;
            this.panel10.Location = new System.Drawing.Point(436, 3);
            this.panel10.Size = new System.Drawing.Size(421, 84);
            this.panel10.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel10.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel10.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel10.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel10.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel10.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel10.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel10.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel10.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel10.TabIndex = 1;
            this.panel10.TabStop = false;
            this.panel10.AutoSize = false;
            this.panel10.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel10.AutoScroll = false;
            this.panel10.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel10.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel10.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel10.Name = "panel10";
            // lblEmail
            this.lblEmail.Text = "E-mail";
            this.lblEmail.AccessibleName = null;
            this.lblEmail.Location = new System.Drawing.Point(0, 0);
            this.lblEmail.Size = new System.Drawing.Size(401, 25);
            this.lblEmail.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblEmail.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblEmail.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblEmail.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblEmail.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblEmail.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblEmail.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblEmail.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblEmail.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblEmail.TabIndex = 3;
            this.lblEmail.TabStop = false;
            this.lblEmail.AutoSize = false;
            this.lblEmail.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblEmail.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblEmail.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblEmail.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblEmail.UseCompatibleTextRendering = false;
            this.lblEmail.Name = "lblEmail";
            // txtEmailFundo
            this.txtEmailFundo.Text = "";
            this.txtEmailFundo.AccessibleName = null;
            this.txtEmailFundo.Location = new System.Drawing.Point(0, 28);
            this.txtEmailFundo.Size = new System.Drawing.Size(401, 42);
            this.txtEmailFundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtEmailFundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtEmailFundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtEmailFundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtEmailFundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtEmailFundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtEmailFundo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtEmailFundo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtEmailFundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtEmailFundo.TabIndex = 0;
            this.txtEmailFundo.TabStop = false;
            this.txtEmailFundo.AutoSize = false;
            this.txtEmailFundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.txtEmailFundo.AutoScroll = false;
            this.txtEmailFundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.txtEmailFundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtEmailFundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtEmailFundo.Name = "txtEmailFundo";
            // txtEmail
            this.txtEmail.Text = "";
            this.txtEmail.AccessibleName = "E-mail";
            this.txtEmail.Location = new System.Drawing.Point(12, 12);
            this.txtEmail.Size = new System.Drawing.Size(377, 18);
            this.txtEmail.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtEmail.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtEmail.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtEmail.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtEmail.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtEmail.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtEmail.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtEmail.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtEmail.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtEmail.TabIndex = 0;
            this.txtEmail.TabStop = true;
            this.txtEmail.AutoSize = true;
            this.txtEmail.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtEmail.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtEmail.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.txtEmail.ReadOnly = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.MaxLength = 100;
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.txtEmail.WordWrap = true;
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.txtEmail.Name = "txtEmail";
            // panel11
            this.panel11.Text = "";
            this.panel11.AccessibleName = null;
            this.panel11.Location = new System.Drawing.Point(3, 99);
            this.panel11.Size = new System.Drawing.Size(421, 84);
            this.panel11.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel11.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel11.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel11.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel11.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel11.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel11.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel11.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel11.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel11.TabIndex = 2;
            this.panel11.TabStop = false;
            this.panel11.AutoSize = false;
            this.panel11.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel11.AutoScroll = false;
            this.panel11.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel11.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel11.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel11.Name = "panel11";
            // lblTelefone
            this.lblTelefone.Text = "Telefone";
            this.lblTelefone.AccessibleName = null;
            this.lblTelefone.Location = new System.Drawing.Point(0, 0);
            this.lblTelefone.Size = new System.Drawing.Size(401, 25);
            this.lblTelefone.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblTelefone.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblTelefone.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblTelefone.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblTelefone.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblTelefone.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblTelefone.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblTelefone.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblTelefone.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblTelefone.TabIndex = 5;
            this.lblTelefone.TabStop = false;
            this.lblTelefone.AutoSize = false;
            this.lblTelefone.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblTelefone.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblTelefone.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblTelefone.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblTelefone.UseCompatibleTextRendering = false;
            this.lblTelefone.Name = "lblTelefone";
            // txtTelefoneFundo
            this.txtTelefoneFundo.Text = "";
            this.txtTelefoneFundo.AccessibleName = null;
            this.txtTelefoneFundo.Location = new System.Drawing.Point(0, 28);
            this.txtTelefoneFundo.Size = new System.Drawing.Size(401, 42);
            this.txtTelefoneFundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtTelefoneFundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtTelefoneFundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtTelefoneFundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtTelefoneFundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtTelefoneFundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtTelefoneFundo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtTelefoneFundo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtTelefoneFundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtTelefoneFundo.TabIndex = 0;
            this.txtTelefoneFundo.TabStop = false;
            this.txtTelefoneFundo.AutoSize = false;
            this.txtTelefoneFundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.txtTelefoneFundo.AutoScroll = false;
            this.txtTelefoneFundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.txtTelefoneFundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtTelefoneFundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtTelefoneFundo.Name = "txtTelefoneFundo";
            // txtTelefone
            this.txtTelefone.Text = "";
            this.txtTelefone.AccessibleName = "Telefone";
            this.txtTelefone.Location = new System.Drawing.Point(12, 12);
            this.txtTelefone.Size = new System.Drawing.Size(377, 18);
            this.txtTelefone.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtTelefone.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtTelefone.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtTelefone.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtTelefone.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtTelefone.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtTelefone.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtTelefone.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtTelefone.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtTelefone.TabIndex = 0;
            this.txtTelefone.TabStop = true;
            this.txtTelefone.AutoSize = true;
            this.txtTelefone.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtTelefone.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtTelefone.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.txtTelefone.ReadOnly = false;
            this.txtTelefone.Multiline = false;
            this.txtTelefone.MaxLength = 20;
            this.txtTelefone.UseSystemPasswordChar = false;
            this.txtTelefone.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.txtTelefone.WordWrap = true;
            this.txtTelefone.AcceptsReturn = false;
            this.txtTelefone.AcceptsTab = false;
            this.txtTelefone.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.txtTelefone.Name = "txtTelefone";
            // label12
            this.label12.Text = "Segurança";
            this.label12.AccessibleName = null;
            this.label12.Location = new System.Drawing.Point(13, 276);
            this.label12.Size = new System.Drawing.Size(867, 32);
            this.label12.MinimumSize = new System.Drawing.Size(0, 0);
            this.label12.MaximumSize = new System.Drawing.Size(0, 0);
            this.label12.Font = new System.Drawing.Font("Segoe UI", 12F, (System.Drawing.FontStyle)1);
            this.label12.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.label12.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.label12.Dock = (System.Windows.Forms.DockStyle)0;
            this.label12.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label12.Margin = new System.Windows.Forms.Padding(3, 14, 3, 4);
            this.label12.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label12.TabIndex = 2;
            this.label12.TabStop = false;
            this.label12.AutoSize = false;
            this.label12.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label12.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label12.TextAlign = (System.Drawing.ContentAlignment)1;
            this.label12.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label12.UseCompatibleTextRendering = false;
            this.label12.Name = "label12";
            // flowlayoutpanel13
            this.flowlayoutpanel13.Text = "";
            this.flowlayoutpanel13.AccessibleName = null;
            this.flowlayoutpanel13.Location = new System.Drawing.Point(10, 312);
            this.flowlayoutpanel13.Size = new System.Drawing.Size(867, 192);
            this.flowlayoutpanel13.MinimumSize = new System.Drawing.Size(867, 0);
            this.flowlayoutpanel13.MaximumSize = new System.Drawing.Size(867, 0);
            this.flowlayoutpanel13.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel13.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel13.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel13.Dock = (System.Windows.Forms.DockStyle)0;
            this.flowlayoutpanel13.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel13.Margin = new System.Windows.Forms.Padding(0, 0, 0, 10);
            this.flowlayoutpanel13.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.flowlayoutpanel13.TabIndex = 3;
            this.flowlayoutpanel13.TabStop = false;
            this.flowlayoutpanel13.AutoSize = true;
            this.flowlayoutpanel13.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.flowlayoutpanel13.AutoScroll = false;
            this.flowlayoutpanel13.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel13.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel13.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel13.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel13.WrapContents = true;
            this.flowlayoutpanel13.Name = "flowlayoutpanel13";
            // panel14
            this.panel14.Text = "";
            this.panel14.AccessibleName = null;
            this.panel14.Location = new System.Drawing.Point(3, 3);
            this.panel14.Size = new System.Drawing.Size(421, 84);
            this.panel14.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel14.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel14.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel14.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel14.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel14.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel14.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel14.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel14.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel14.TabIndex = 0;
            this.panel14.TabStop = false;
            this.panel14.AutoSize = false;
            this.panel14.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel14.AutoScroll = false;
            this.panel14.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel14.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel14.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel14.Name = "panel14";
            // lblAtual
            this.lblAtual.Text = "Senha atual (para confirmar as alterações)";
            this.lblAtual.AccessibleName = null;
            this.lblAtual.Location = new System.Drawing.Point(0, 0);
            this.lblAtual.Size = new System.Drawing.Size(401, 25);
            this.lblAtual.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblAtual.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblAtual.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblAtual.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblAtual.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblAtual.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblAtual.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblAtual.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblAtual.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblAtual.TabIndex = 7;
            this.lblAtual.TabStop = false;
            this.lblAtual.AutoSize = false;
            this.lblAtual.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblAtual.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblAtual.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblAtual.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblAtual.UseCompatibleTextRendering = false;
            this.lblAtual.Name = "lblAtual";
            // txtAtualFundo
            this.txtAtualFundo.Text = "";
            this.txtAtualFundo.AccessibleName = null;
            this.txtAtualFundo.Location = new System.Drawing.Point(0, 28);
            this.txtAtualFundo.Size = new System.Drawing.Size(401, 42);
            this.txtAtualFundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtAtualFundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtAtualFundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtAtualFundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtAtualFundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtAtualFundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtAtualFundo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtAtualFundo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtAtualFundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtAtualFundo.TabIndex = 0;
            this.txtAtualFundo.TabStop = false;
            this.txtAtualFundo.AutoSize = false;
            this.txtAtualFundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.txtAtualFundo.AutoScroll = false;
            this.txtAtualFundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.txtAtualFundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtAtualFundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtAtualFundo.Name = "txtAtualFundo";
            // txtAtual
            this.txtAtual.Text = "";
            this.txtAtual.AccessibleName = "Senha atual (para confirmar as alterações)";
            this.txtAtual.Location = new System.Drawing.Point(12, 12);
            this.txtAtual.Size = new System.Drawing.Size(377, 18);
            this.txtAtual.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtAtual.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtAtual.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtAtual.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtAtual.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtAtual.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtAtual.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtAtual.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtAtual.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtAtual.TabIndex = 0;
            this.txtAtual.TabStop = true;
            this.txtAtual.AutoSize = true;
            this.txtAtual.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtAtual.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtAtual.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.txtAtual.ReadOnly = false;
            this.txtAtual.Multiline = false;
            this.txtAtual.MaxLength = 128;
            this.txtAtual.UseSystemPasswordChar = true;
            this.txtAtual.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.txtAtual.WordWrap = true;
            this.txtAtual.AcceptsReturn = false;
            this.txtAtual.AcceptsTab = false;
            this.txtAtual.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.txtAtual.Name = "txtAtual";
            // panel15
            this.panel15.Text = "";
            this.panel15.AccessibleName = null;
            this.panel15.Location = new System.Drawing.Point(436, 3);
            this.panel15.Size = new System.Drawing.Size(421, 84);
            this.panel15.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel15.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel15.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel15.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel15.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel15.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel15.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel15.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel15.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel15.TabIndex = 1;
            this.panel15.TabStop = false;
            this.panel15.AutoSize = false;
            this.panel15.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel15.AutoScroll = false;
            this.panel15.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel15.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel15.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel15.Name = "panel15";
            // lblNova
            this.lblNova.Text = "Nova senha (deixe vazia para manter)";
            this.lblNova.AccessibleName = null;
            this.lblNova.Location = new System.Drawing.Point(0, 0);
            this.lblNova.Size = new System.Drawing.Size(401, 25);
            this.lblNova.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblNova.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblNova.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblNova.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblNova.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblNova.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblNova.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblNova.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblNova.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblNova.TabIndex = 9;
            this.lblNova.TabStop = false;
            this.lblNova.AutoSize = false;
            this.lblNova.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblNova.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblNova.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblNova.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblNova.UseCompatibleTextRendering = false;
            this.lblNova.Name = "lblNova";
            // txtNovaFundo
            this.txtNovaFundo.Text = "";
            this.txtNovaFundo.AccessibleName = null;
            this.txtNovaFundo.Location = new System.Drawing.Point(0, 28);
            this.txtNovaFundo.Size = new System.Drawing.Size(401, 42);
            this.txtNovaFundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtNovaFundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtNovaFundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtNovaFundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtNovaFundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtNovaFundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtNovaFundo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtNovaFundo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtNovaFundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtNovaFundo.TabIndex = 0;
            this.txtNovaFundo.TabStop = false;
            this.txtNovaFundo.AutoSize = false;
            this.txtNovaFundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.txtNovaFundo.AutoScroll = false;
            this.txtNovaFundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.txtNovaFundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtNovaFundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtNovaFundo.Name = "txtNovaFundo";
            // txtNova
            this.txtNova.Text = "";
            this.txtNova.AccessibleName = "Nova senha (deixe vazia para manter)";
            this.txtNova.Location = new System.Drawing.Point(12, 12);
            this.txtNova.Size = new System.Drawing.Size(377, 18);
            this.txtNova.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtNova.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtNova.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtNova.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtNova.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtNova.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtNova.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtNova.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtNova.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtNova.TabIndex = 0;
            this.txtNova.TabStop = true;
            this.txtNova.AutoSize = true;
            this.txtNova.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtNova.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtNova.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.txtNova.ReadOnly = false;
            this.txtNova.Multiline = false;
            this.txtNova.MaxLength = 128;
            this.txtNova.UseSystemPasswordChar = true;
            this.txtNova.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.txtNova.WordWrap = true;
            this.txtNova.AcceptsReturn = false;
            this.txtNova.AcceptsTab = false;
            this.txtNova.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.txtNova.Name = "txtNova";
            // panel16
            this.panel16.Text = "";
            this.panel16.AccessibleName = null;
            this.panel16.Location = new System.Drawing.Point(3, 99);
            this.panel16.Size = new System.Drawing.Size(421, 84);
            this.panel16.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel16.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel16.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel16.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.panel16.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel16.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel16.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel16.Margin = new System.Windows.Forms.Padding(3, 3, 9, 9);
            this.panel16.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel16.TabIndex = 2;
            this.panel16.TabStop = false;
            this.panel16.AutoSize = false;
            this.panel16.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel16.AutoScroll = false;
            this.panel16.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel16.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel16.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel16.Name = "panel16";
            // lblConfirmacao
            this.lblConfirmacao.Text = "Confirme a nova senha";
            this.lblConfirmacao.AccessibleName = null;
            this.lblConfirmacao.Location = new System.Drawing.Point(0, 0);
            this.lblConfirmacao.Size = new System.Drawing.Size(401, 25);
            this.lblConfirmacao.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblConfirmacao.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblConfirmacao.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblConfirmacao.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblConfirmacao.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblConfirmacao.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblConfirmacao.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblConfirmacao.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblConfirmacao.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblConfirmacao.TabIndex = 11;
            this.lblConfirmacao.TabStop = false;
            this.lblConfirmacao.AutoSize = false;
            this.lblConfirmacao.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblConfirmacao.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblConfirmacao.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblConfirmacao.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblConfirmacao.UseCompatibleTextRendering = false;
            this.lblConfirmacao.Name = "lblConfirmacao";
            // txtConfirmacaoFundo
            this.txtConfirmacaoFundo.Text = "";
            this.txtConfirmacaoFundo.AccessibleName = null;
            this.txtConfirmacaoFundo.Location = new System.Drawing.Point(0, 28);
            this.txtConfirmacaoFundo.Size = new System.Drawing.Size(401, 42);
            this.txtConfirmacaoFundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtConfirmacaoFundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtConfirmacaoFundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtConfirmacaoFundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtConfirmacaoFundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtConfirmacaoFundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtConfirmacaoFundo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtConfirmacaoFundo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtConfirmacaoFundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtConfirmacaoFundo.TabIndex = 0;
            this.txtConfirmacaoFundo.TabStop = false;
            this.txtConfirmacaoFundo.AutoSize = false;
            this.txtConfirmacaoFundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.txtConfirmacaoFundo.AutoScroll = false;
            this.txtConfirmacaoFundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.txtConfirmacaoFundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtConfirmacaoFundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtConfirmacaoFundo.Name = "txtConfirmacaoFundo";
            // txtConfirmacao
            this.txtConfirmacao.Text = "";
            this.txtConfirmacao.AccessibleName = "Confirme a nova senha";
            this.txtConfirmacao.Location = new System.Drawing.Point(12, 12);
            this.txtConfirmacao.Size = new System.Drawing.Size(377, 18);
            this.txtConfirmacao.MinimumSize = new System.Drawing.Size(0, 0);
            this.txtConfirmacao.MaximumSize = new System.Drawing.Size(0, 0);
            this.txtConfirmacao.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.txtConfirmacao.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.txtConfirmacao.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.txtConfirmacao.Dock = (System.Windows.Forms.DockStyle)0;
            this.txtConfirmacao.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.txtConfirmacao.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.txtConfirmacao.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.txtConfirmacao.TabIndex = 0;
            this.txtConfirmacao.TabStop = true;
            this.txtConfirmacao.AutoSize = true;
            this.txtConfirmacao.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.txtConfirmacao.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.txtConfirmacao.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.txtConfirmacao.ReadOnly = false;
            this.txtConfirmacao.Multiline = false;
            this.txtConfirmacao.MaxLength = 128;
            this.txtConfirmacao.UseSystemPasswordChar = true;
            this.txtConfirmacao.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.txtConfirmacao.WordWrap = true;
            this.txtConfirmacao.AcceptsReturn = false;
            this.txtConfirmacao.AcceptsTab = false;
            this.txtConfirmacao.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.txtConfirmacao.Name = "txtConfirmacao";
            // flowlayoutpanel17
            this.flowlayoutpanel17.Text = "";
            this.flowlayoutpanel17.AccessibleName = null;
            this.flowlayoutpanel17.Location = new System.Drawing.Point(13, 517);
            this.flowlayoutpanel17.Size = new System.Drawing.Size(867, 61);
            this.flowlayoutpanel17.MinimumSize = new System.Drawing.Size(867, 0);
            this.flowlayoutpanel17.MaximumSize = new System.Drawing.Size(867, 0);
            this.flowlayoutpanel17.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel17.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.flowlayoutpanel17.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel17.Dock = (System.Windows.Forms.DockStyle)5;
            this.flowlayoutpanel17.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel17.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.flowlayoutpanel17.Padding = new System.Windows.Forms.Padding(0, 5, 0, 10);
            this.flowlayoutpanel17.TabIndex = 4;
            this.flowlayoutpanel17.TabStop = false;
            this.flowlayoutpanel17.AutoSize = true;
            this.flowlayoutpanel17.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.flowlayoutpanel17.AutoScroll = false;
            this.flowlayoutpanel17.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel17.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel17.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel17.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel17.WrapContents = true;
            this.flowlayoutpanel17.Name = "flowlayoutpanel17";
            // btnSalvar
            this.btnSalvar.Text = "Salvar meus dados";
            this.btnSalvar.AccessibleName = null;
            this.btnSalvar.Location = new System.Drawing.Point(0, 8);
            this.btnSalvar.Size = new System.Drawing.Size(144, 38);
            this.btnSalvar.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnSalvar.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnSalvar.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnSalvar.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnSalvar.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnSalvar.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnSalvar.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnSalvar.Margin = new System.Windows.Forms.Padding(0, 3, 10, 5);
            this.btnSalvar.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnSalvar.TabIndex = 0;
            this.btnSalvar.TabStop = true;
            this.btnSalvar.AutoSize = false;
            this.btnSalvar.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnSalvar.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnSalvar.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnSalvar.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnSalvar.UseVisualStyleBackColor = false;
            this.btnSalvar.UseCompatibleTextRendering = false;
            this.btnSalvar.FlatAppearance.BorderSize = 0;
            this.btnSalvar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnSalvar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnSalvar.Name = "btnSalvar";
            this.btnSalvar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Controls.Add(this.tablelayoutpanel1);
            this.tablelayoutpanel1.Controls.Add(this.panel2, 0, 0);
            this.panel2.Controls.Add(this.lblTitulo);
            this.panel2.Controls.Add(this.marcaSecundaria);
            this.tablelayoutpanel1.Controls.Add(this.tabcontrol3, 0, 1);
            this.tabcontrol3.Controls.Add(this.tabpage4);
            this.tabpage4.Controls.Add(this.panel5);
            this.panel5.Controls.Add(this.flowlayoutpanel6);
            this.flowlayoutpanel6.Controls.Add(this.label7);
            this.flowlayoutpanel6.Controls.Add(this.flowlayoutpanel8);
            this.flowlayoutpanel8.Controls.Add(this.panel9);
            this.panel9.Controls.Add(this.lblNome);
            this.panel9.Controls.Add(this.txtNomeFundo);
            this.txtNomeFundo.Controls.Add(this.txtNome);
            this.flowlayoutpanel8.Controls.Add(this.panel10);
            this.panel10.Controls.Add(this.lblEmail);
            this.panel10.Controls.Add(this.txtEmailFundo);
            this.txtEmailFundo.Controls.Add(this.txtEmail);
            this.flowlayoutpanel8.Controls.Add(this.panel11);
            this.panel11.Controls.Add(this.lblTelefone);
            this.panel11.Controls.Add(this.txtTelefoneFundo);
            this.txtTelefoneFundo.Controls.Add(this.txtTelefone);
            this.flowlayoutpanel6.Controls.Add(this.label12);
            this.flowlayoutpanel6.Controls.Add(this.flowlayoutpanel13);
            this.flowlayoutpanel13.Controls.Add(this.panel14);
            this.panel14.Controls.Add(this.lblAtual);
            this.panel14.Controls.Add(this.txtAtualFundo);
            this.txtAtualFundo.Controls.Add(this.txtAtual);
            this.flowlayoutpanel13.Controls.Add(this.panel15);
            this.panel15.Controls.Add(this.lblNova);
            this.panel15.Controls.Add(this.txtNovaFundo);
            this.txtNovaFundo.Controls.Add(this.txtNova);
            this.flowlayoutpanel13.Controls.Add(this.panel16);
            this.panel16.Controls.Add(this.lblConfirmacao);
            this.panel16.Controls.Add(this.txtConfirmacaoFundo);
            this.txtConfirmacaoFundo.Controls.Add(this.txtConfirmacao);
            this.flowlayoutpanel6.Controls.Add(this.flowlayoutpanel17);
            this.flowlayoutpanel17.Controls.Add(this.btnSalvar);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.btnSalvar.Click += new System.EventHandler(this.btnSalvar_Click);
            this.Load += new System.EventHandler(this.PerfilForm_Load);
            this.txtNomeFundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.txtEmailFundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.txtTelefoneFundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.txtAtualFundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.txtNovaFundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.txtConfirmacaoFundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnSalvar.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.panel5.SizeChanged += new System.EventHandler(this.flowlayoutpanel6_Redimensionar);
            this.flowlayoutpanel17.ResumeLayout(false);
            this.flowlayoutpanel17.PerformLayout();
            this.txtConfirmacaoFundo.ResumeLayout(false);
            this.txtConfirmacaoFundo.PerformLayout();
            this.panel16.ResumeLayout(false);
            this.panel16.PerformLayout();
            this.txtNovaFundo.ResumeLayout(false);
            this.txtNovaFundo.PerformLayout();
            this.panel15.ResumeLayout(false);
            this.panel15.PerformLayout();
            this.txtAtualFundo.ResumeLayout(false);
            this.txtAtualFundo.PerformLayout();
            this.panel14.ResumeLayout(false);
            this.panel14.PerformLayout();
            this.flowlayoutpanel13.ResumeLayout(false);
            this.flowlayoutpanel13.PerformLayout();
            this.txtTelefoneFundo.ResumeLayout(false);
            this.txtTelefoneFundo.PerformLayout();
            this.panel11.ResumeLayout(false);
            this.panel11.PerformLayout();
            this.txtEmailFundo.ResumeLayout(false);
            this.txtEmailFundo.PerformLayout();
            this.panel10.ResumeLayout(false);
            this.panel10.PerformLayout();
            this.txtNomeFundo.ResumeLayout(false);
            this.txtNomeFundo.PerformLayout();
            this.panel9.ResumeLayout(false);
            this.panel9.PerformLayout();
            this.flowlayoutpanel8.ResumeLayout(false);
            this.flowlayoutpanel8.PerformLayout();
            this.flowlayoutpanel6.ResumeLayout(false);
            this.flowlayoutpanel6.PerformLayout();
            this.panel5.ResumeLayout(false);
            this.panel5.PerformLayout();
            this.tabpage4.ResumeLayout(false);
            this.tabpage4.PerformLayout();
            this.tabcontrol3.ResumeLayout(false);
            this.tabcontrol3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.marcaSecundaria)).EndInit();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.tablelayoutpanel1.ResumeLayout(false);
            this.tablelayoutpanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.TableLayoutPanel tablelayoutpanel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.PictureBox marcaSecundaria;
        private System.Windows.Forms.TabControl tabcontrol3;
        private System.Windows.Forms.TabPage tabpage4;
        private System.Windows.Forms.Panel panel5;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel8;
        private System.Windows.Forms.Panel panel9;
        private System.Windows.Forms.Label lblNome;
        private System.Windows.Forms.Panel txtNomeFundo;
        private System.Windows.Forms.TextBox txtNome;
        private System.Windows.Forms.Panel panel10;
        private System.Windows.Forms.Label lblEmail;
        private System.Windows.Forms.Panel txtEmailFundo;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.Panel panel11;
        private System.Windows.Forms.Label lblTelefone;
        private System.Windows.Forms.Panel txtTelefoneFundo;
        private System.Windows.Forms.TextBox txtTelefone;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel13;
        private System.Windows.Forms.Panel panel14;
        private System.Windows.Forms.Label lblAtual;
        private System.Windows.Forms.Panel txtAtualFundo;
        private System.Windows.Forms.TextBox txtAtual;
        private System.Windows.Forms.Panel panel15;
        private System.Windows.Forms.Label lblNova;
        private System.Windows.Forms.Panel txtNovaFundo;
        private System.Windows.Forms.TextBox txtNova;
        private System.Windows.Forms.Panel panel16;
        private System.Windows.Forms.Label lblConfirmacao;
        private System.Windows.Forms.Panel txtConfirmacaoFundo;
        private System.Windows.Forms.TextBox txtConfirmacao;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel17;
        private System.Windows.Forms.Button btnSalvar;
    }
}
