namespace Tecnologia
{
    partial class PrincipalForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null) components.Dispose();
                if (BackgroundImage != null) BackgroundImage.Dispose();
                if (picturebox3 != null && picturebox3.Image != null) picturebox3.Image.Dispose();
                if (picturebox7 != null && picturebox7.Image != null) picturebox7.Image.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PrincipalForm));
            this.tablelayoutpanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tablelayoutpanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.picturebox3 = new System.Windows.Forms.PictureBox();
            this.lblUsuario = new System.Windows.Forms.Label();
            this.flowlayoutpanel4 = new System.Windows.Forms.FlowLayoutPanel();
            this.btnAtualizar = new System.Windows.Forms.Button();
            this.btnOrdens = new System.Windows.Forms.Button();
            this.btnPecas = new System.Windows.Forms.Button();
            this.btnCadastros = new System.Windows.Forms.Button();
            this.btnPerfil = new System.Windows.Forms.Button();
            this.btnSair = new System.Windows.Forms.Button();
            this.conteudo = new System.Windows.Forms.TableLayoutPanel();
            this.menuCadastros = new System.Windows.Forms.FlowLayoutPanel();
            this.btnClientes = new System.Windows.Forms.Button();
            this.btnAparelhos = new System.Windows.Forms.Button();
            this.btnUsuarios = new System.Windows.Forms.Button();
            this.area = new System.Windows.Forms.Panel();
            this.dashboard = new System.Windows.Forms.TableLayoutPanel();
            this.tablelayoutpanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.panel6 = new System.Windows.Forms.Panel();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.btnNova = new System.Windows.Forms.Button();
            this.picturebox7 = new System.Windows.Forms.PictureBox();
            this.tablelayoutpanel8 = new System.Windows.Forms.TableLayoutPanel();
            this.btnAbertas = new System.Windows.Forms.Button();
            this.btnManutencao = new System.Windows.Forms.Button();
            this.btnConcluidas = new System.Windows.Forms.Button();
            this.btnProntas = new System.Windows.Forms.Button();
            this.lblResumo = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            this.tablelayoutpanel1.SuspendLayout();
            this.tablelayoutpanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picturebox3)).BeginInit();
            this.flowlayoutpanel4.SuspendLayout();
            this.conteudo.SuspendLayout();
            this.menuCadastros.SuspendLayout();
            this.area.SuspendLayout();
            this.dashboard.SuspendLayout();
            this.tablelayoutpanel5.SuspendLayout();
            this.panel6.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picturebox7)).BeginInit();
            this.tablelayoutpanel8.SuspendLayout();
            // PrincipalForm
            this.Text = "Tecnologia — Painel principal";
            this.AccessibleName = null;
            this.MinimumSize = new System.Drawing.Size(940, 650);
            this.MaximumSize = new System.Drawing.Size(0, 0);
            this.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Dock = (System.Windows.Forms.DockStyle)0;
            this.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.TabIndex = 0;
            this.TabStop = true;
            this.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.AutoScroll = true;
            this.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)3;
            this.ClientSize = new System.Drawing.Size(1180, 820);
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.Name = "PrincipalForm";
            // tablelayoutpanel1
            this.tablelayoutpanel1.Text = "";
            this.tablelayoutpanel1.AccessibleName = null;
            this.tablelayoutpanel1.Location = new System.Drawing.Point(0, 0);
            this.tablelayoutpanel1.Size = new System.Drawing.Size(1028, 749);
            this.tablelayoutpanel1.MinimumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.MaximumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.tablelayoutpanel1.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.tablelayoutpanel1.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tablelayoutpanel1.Dock = (System.Windows.Forms.DockStyle)5;
            this.tablelayoutpanel1.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tablelayoutpanel1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tablelayoutpanel1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.tablelayoutpanel1.TabIndex = 0;
            this.tablelayoutpanel1.TabStop = false;
            this.tablelayoutpanel1.AutoSize = false;
            this.tablelayoutpanel1.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tablelayoutpanel1.AutoScroll = false;
            this.tablelayoutpanel1.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel1.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tablelayoutpanel1.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tablelayoutpanel1.RowCount = 4;
            this.tablelayoutpanel1.ColumnCount = 1;
            this.tablelayoutpanel1.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.tablelayoutpanel1.Name = "tablelayoutpanel1";
            this.tablelayoutpanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 100F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)1, 112F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)1, 54F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)2, 100F));
            this.tablelayoutpanel1.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)1, 34F));
            // tablelayoutpanel2
            this.tablelayoutpanel2.Text = "";
            this.tablelayoutpanel2.AccessibleName = null;
            this.tablelayoutpanel2.Location = new System.Drawing.Point(3, 3);
            this.tablelayoutpanel2.Size = new System.Drawing.Size(1022, 106);
            this.tablelayoutpanel2.MinimumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel2.MaximumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel2.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.tablelayoutpanel2.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.tablelayoutpanel2.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tablelayoutpanel2.Dock = (System.Windows.Forms.DockStyle)5;
            this.tablelayoutpanel2.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tablelayoutpanel2.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tablelayoutpanel2.Padding = new System.Windows.Forms.Padding(28, 12, 28, 10);
            this.tablelayoutpanel2.TabIndex = 0;
            this.tablelayoutpanel2.TabStop = false;
            this.tablelayoutpanel2.AutoSize = false;
            this.tablelayoutpanel2.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tablelayoutpanel2.AutoScroll = false;
            this.tablelayoutpanel2.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel2.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tablelayoutpanel2.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tablelayoutpanel2.RowCount = 0;
            this.tablelayoutpanel2.ColumnCount = 2;
            this.tablelayoutpanel2.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.tablelayoutpanel2.Name = "tablelayoutpanel2";
            this.tablelayoutpanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 50F));
            this.tablelayoutpanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 50F));
            // picturebox3
            this.picturebox3.Text = "";
            this.picturebox3.AccessibleName = null;
            this.picturebox3.Location = new System.Drawing.Point(31, 15);
            this.picturebox3.Size = new System.Drawing.Size(477, 78);
            this.picturebox3.MinimumSize = new System.Drawing.Size(0, 0);
            this.picturebox3.MaximumSize = new System.Drawing.Size(0, 0);
            this.picturebox3.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.picturebox3.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.picturebox3.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.picturebox3.Dock = (System.Windows.Forms.DockStyle)5;
            this.picturebox3.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.picturebox3.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.picturebox3.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.picturebox3.TabIndex = 0;
            this.picturebox3.TabStop = false;
            this.picturebox3.AutoSize = false;
            this.picturebox3.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.picturebox3.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.picturebox3.SizeMode = (System.Windows.Forms.PictureBoxSizeMode)4;
            this.picturebox3.Image = ((System.Drawing.Image)(resources.GetObject("picturebox3.Image")));
            this.picturebox3.Name = "picturebox3";
            // lblUsuario
            this.lblUsuario.Text = "";
            this.lblUsuario.AccessibleName = null;
            this.lblUsuario.Location = new System.Drawing.Point(514, 12);
            this.lblUsuario.Size = new System.Drawing.Size(477, 84);
            this.lblUsuario.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblUsuario.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblUsuario.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblUsuario.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblUsuario.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblUsuario.Dock = (System.Windows.Forms.DockStyle)5;
            this.lblUsuario.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.lblUsuario.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblUsuario.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblUsuario.TabIndex = 1;
            this.lblUsuario.TabStop = false;
            this.lblUsuario.AutoSize = false;
            this.lblUsuario.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblUsuario.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblUsuario.TextAlign = (System.Drawing.ContentAlignment)64;
            this.lblUsuario.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblUsuario.UseCompatibleTextRendering = false;
            this.lblUsuario.Name = "lblUsuario";
            // flowlayoutpanel4
            this.flowlayoutpanel4.Text = "";
            this.flowlayoutpanel4.AccessibleName = null;
            this.flowlayoutpanel4.Location = new System.Drawing.Point(3, 115);
            this.flowlayoutpanel4.Size = new System.Drawing.Size(1022, 48);
            this.flowlayoutpanel4.MinimumSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel4.MaximumSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel4.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.flowlayoutpanel4.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.flowlayoutpanel4.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.flowlayoutpanel4.Dock = (System.Windows.Forms.DockStyle)5;
            this.flowlayoutpanel4.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.flowlayoutpanel4.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.flowlayoutpanel4.Padding = new System.Windows.Forms.Padding(28, 5, 0, 0);
            this.flowlayoutpanel4.TabIndex = 1;
            this.flowlayoutpanel4.TabStop = false;
            this.flowlayoutpanel4.AutoSize = false;
            this.flowlayoutpanel4.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.flowlayoutpanel4.AutoScroll = false;
            this.flowlayoutpanel4.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.flowlayoutpanel4.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.flowlayoutpanel4.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.flowlayoutpanel4.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.flowlayoutpanel4.WrapContents = true;
            this.flowlayoutpanel4.Name = "flowlayoutpanel4";
            // btnAtualizar
            this.btnAtualizar.Text = "Dashboard";
            this.btnAtualizar.AccessibleName = null;
            this.btnAtualizar.Location = new System.Drawing.Point(28, 5);
            this.btnAtualizar.Size = new System.Drawing.Size(132, 36);
            this.btnAtualizar.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnAtualizar.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnAtualizar.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnAtualizar.BackColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.btnAtualizar.ForeColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.btnAtualizar.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnAtualizar.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnAtualizar.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.btnAtualizar.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnAtualizar.TabIndex = 0;
            this.btnAtualizar.TabStop = true;
            this.btnAtualizar.AutoSize = false;
            this.btnAtualizar.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnAtualizar.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnAtualizar.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnAtualizar.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnAtualizar.UseVisualStyleBackColor = false;
            this.btnAtualizar.UseCompatibleTextRendering = false;
            this.btnAtualizar.FlatAppearance.BorderSize = 0;
            this.btnAtualizar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnAtualizar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnAtualizar.Name = "btnAtualizar";
            this.btnAtualizar.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnOrdens
            this.btnOrdens.Text = "Manutenção";
            this.btnOrdens.AccessibleName = null;
            this.btnOrdens.Location = new System.Drawing.Point(172, 5);
            this.btnOrdens.Size = new System.Drawing.Size(132, 36);
            this.btnOrdens.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnOrdens.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnOrdens.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnOrdens.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnOrdens.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnOrdens.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnOrdens.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnOrdens.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.btnOrdens.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnOrdens.TabIndex = 1;
            this.btnOrdens.TabStop = true;
            this.btnOrdens.AutoSize = false;
            this.btnOrdens.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnOrdens.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnOrdens.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnOrdens.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnOrdens.UseVisualStyleBackColor = false;
            this.btnOrdens.UseCompatibleTextRendering = false;
            this.btnOrdens.FlatAppearance.BorderSize = 0;
            this.btnOrdens.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnOrdens.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnOrdens.Name = "btnOrdens";
            this.btnOrdens.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnPecas
            this.btnPecas.Text = "Peças";
            this.btnPecas.AccessibleName = null;
            this.btnPecas.Location = new System.Drawing.Point(316, 5);
            this.btnPecas.Size = new System.Drawing.Size(132, 36);
            this.btnPecas.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnPecas.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnPecas.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnPecas.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnPecas.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnPecas.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnPecas.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnPecas.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.btnPecas.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnPecas.TabIndex = 2;
            this.btnPecas.TabStop = true;
            this.btnPecas.AutoSize = false;
            this.btnPecas.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnPecas.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnPecas.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnPecas.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnPecas.UseVisualStyleBackColor = false;
            this.btnPecas.UseCompatibleTextRendering = false;
            this.btnPecas.FlatAppearance.BorderSize = 0;
            this.btnPecas.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnPecas.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnPecas.Name = "btnPecas";
            this.btnPecas.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnCadastros
            this.btnCadastros.Text = "Cadastros";
            this.btnCadastros.AccessibleName = null;
            this.btnCadastros.Location = new System.Drawing.Point(460, 5);
            this.btnCadastros.Size = new System.Drawing.Size(132, 36);
            this.btnCadastros.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnCadastros.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnCadastros.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnCadastros.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnCadastros.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnCadastros.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnCadastros.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnCadastros.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.btnCadastros.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnCadastros.TabIndex = 3;
            this.btnCadastros.TabStop = true;
            this.btnCadastros.AutoSize = false;
            this.btnCadastros.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnCadastros.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnCadastros.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnCadastros.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnCadastros.UseVisualStyleBackColor = false;
            this.btnCadastros.UseCompatibleTextRendering = false;
            this.btnCadastros.FlatAppearance.BorderSize = 0;
            this.btnCadastros.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnCadastros.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnCadastros.Name = "btnCadastros";
            this.btnCadastros.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnPerfil
            this.btnPerfil.Text = "Conta / Perfil";
            this.btnPerfil.AccessibleName = null;
            this.btnPerfil.Location = new System.Drawing.Point(604, 5);
            this.btnPerfil.Size = new System.Drawing.Size(132, 36);
            this.btnPerfil.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnPerfil.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnPerfil.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnPerfil.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnPerfil.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnPerfil.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnPerfil.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnPerfil.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.btnPerfil.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnPerfil.TabIndex = 4;
            this.btnPerfil.TabStop = true;
            this.btnPerfil.AutoSize = false;
            this.btnPerfil.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnPerfil.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnPerfil.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnPerfil.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnPerfil.UseVisualStyleBackColor = false;
            this.btnPerfil.UseCompatibleTextRendering = false;
            this.btnPerfil.FlatAppearance.BorderSize = 0;
            this.btnPerfil.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnPerfil.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnPerfil.Name = "btnPerfil";
            this.btnPerfil.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnSair
            this.btnSair.Text = "Sair";
            this.btnSair.AccessibleName = null;
            this.btnSair.Location = new System.Drawing.Point(748, 5);
            this.btnSair.Size = new System.Drawing.Size(132, 36);
            this.btnSair.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnSair.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnSair.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnSair.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnSair.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnSair.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnSair.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnSair.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.btnSair.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnSair.TabIndex = 5;
            this.btnSair.TabStop = true;
            this.btnSair.AutoSize = false;
            this.btnSair.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnSair.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnSair.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnSair.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnSair.UseVisualStyleBackColor = false;
            this.btnSair.UseCompatibleTextRendering = false;
            this.btnSair.FlatAppearance.BorderSize = 0;
            this.btnSair.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnSair.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnSair.Name = "btnSair";
            this.btnSair.Cursor = System.Windows.Forms.Cursors.Hand;
            // conteudo
            this.conteudo.Text = "";
            this.conteudo.AccessibleName = null;
            this.conteudo.Location = new System.Drawing.Point(3, 169);
            this.conteudo.Size = new System.Drawing.Size(1022, 543);
            this.conteudo.MinimumSize = new System.Drawing.Size(0, 0);
            this.conteudo.MaximumSize = new System.Drawing.Size(0, 0);
            this.conteudo.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.conteudo.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.conteudo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.conteudo.Dock = (System.Windows.Forms.DockStyle)5;
            this.conteudo.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.conteudo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.conteudo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.conteudo.TabIndex = 2;
            this.conteudo.TabStop = false;
            this.conteudo.AutoSize = false;
            this.conteudo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.conteudo.AutoScroll = false;
            this.conteudo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.conteudo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.conteudo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.conteudo.RowCount = 2;
            this.conteudo.ColumnCount = 1;
            this.conteudo.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.conteudo.Name = "conteudo";
            this.conteudo.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 100F));
            this.conteudo.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)1, 0F));
            this.conteudo.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)2, 100F));
            // menuCadastros
            this.menuCadastros.Text = "";
            this.menuCadastros.AccessibleName = null;
            this.menuCadastros.Location = new System.Drawing.Point(3, 3);
            this.menuCadastros.Size = new System.Drawing.Size(1016, 1);
            this.menuCadastros.MinimumSize = new System.Drawing.Size(0, 0);
            this.menuCadastros.MaximumSize = new System.Drawing.Size(0, 0);
            this.menuCadastros.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.menuCadastros.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.menuCadastros.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.menuCadastros.Dock = (System.Windows.Forms.DockStyle)5;
            this.menuCadastros.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.menuCadastros.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.menuCadastros.Padding = new System.Windows.Forms.Padding(28, 6, 0, 0);
            this.menuCadastros.TabIndex = 0;
            this.menuCadastros.TabStop = false;
            this.menuCadastros.AutoSize = false;
            this.menuCadastros.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.menuCadastros.AutoScroll = false;
            this.menuCadastros.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.menuCadastros.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.menuCadastros.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.menuCadastros.FlowDirection = (System.Windows.Forms.FlowDirection)0;
            this.menuCadastros.WrapContents = true;
            this.menuCadastros.Name = "menuCadastros";
            // btnClientes
            this.btnClientes.Text = "Clientes";
            this.btnClientes.AccessibleName = null;
            this.btnClientes.Location = new System.Drawing.Point(28, 6);
            this.btnClientes.Size = new System.Drawing.Size(190, 36);
            this.btnClientes.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnClientes.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnClientes.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnClientes.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnClientes.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnClientes.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnClientes.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnClientes.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.btnClientes.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnClientes.TabIndex = 2;
            this.btnClientes.TabStop = true;
            this.btnClientes.AutoSize = false;
            this.btnClientes.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnClientes.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnClientes.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnClientes.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnClientes.UseVisualStyleBackColor = false;
            this.btnClientes.UseCompatibleTextRendering = false;
            this.btnClientes.FlatAppearance.BorderSize = 0;
            this.btnClientes.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnClientes.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnClientes.Name = "btnClientes";
            this.btnClientes.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnAparelhos
            this.btnAparelhos.Text = "Aparelhos";
            this.btnAparelhos.AccessibleName = null;
            this.btnAparelhos.Location = new System.Drawing.Point(230, 6);
            this.btnAparelhos.Size = new System.Drawing.Size(190, 36);
            this.btnAparelhos.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnAparelhos.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnAparelhos.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnAparelhos.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnAparelhos.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnAparelhos.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnAparelhos.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnAparelhos.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.btnAparelhos.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnAparelhos.TabIndex = 3;
            this.btnAparelhos.TabStop = true;
            this.btnAparelhos.AutoSize = false;
            this.btnAparelhos.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnAparelhos.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnAparelhos.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnAparelhos.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnAparelhos.UseVisualStyleBackColor = false;
            this.btnAparelhos.UseCompatibleTextRendering = false;
            this.btnAparelhos.FlatAppearance.BorderSize = 0;
            this.btnAparelhos.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnAparelhos.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnAparelhos.Name = "btnAparelhos";
            this.btnAparelhos.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnUsuarios
            this.btnUsuarios.Text = "Atendentes e técnicos";
            this.btnUsuarios.AccessibleName = null;
            this.btnUsuarios.Location = new System.Drawing.Point(432, 6);
            this.btnUsuarios.Size = new System.Drawing.Size(190, 36);
            this.btnUsuarios.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnUsuarios.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnUsuarios.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnUsuarios.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnUsuarios.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnUsuarios.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnUsuarios.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnUsuarios.Margin = new System.Windows.Forms.Padding(0, 0, 12, 0);
            this.btnUsuarios.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnUsuarios.TabIndex = 4;
            this.btnUsuarios.TabStop = true;
            this.btnUsuarios.AutoSize = false;
            this.btnUsuarios.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnUsuarios.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnUsuarios.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnUsuarios.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnUsuarios.UseVisualStyleBackColor = false;
            this.btnUsuarios.UseCompatibleTextRendering = false;
            this.btnUsuarios.FlatAppearance.BorderSize = 0;
            this.btnUsuarios.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnUsuarios.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnUsuarios.Name = "btnUsuarios";
            this.btnUsuarios.Cursor = System.Windows.Forms.Cursors.Hand;
            // area
            this.area.Text = "";
            this.area.AccessibleName = null;
            this.area.Location = new System.Drawing.Point(3, 3);
            this.area.Size = new System.Drawing.Size(1016, 537);
            this.area.MinimumSize = new System.Drawing.Size(0, 0);
            this.area.MaximumSize = new System.Drawing.Size(0, 0);
            this.area.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.area.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.area.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.area.Dock = (System.Windows.Forms.DockStyle)5;
            this.area.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.area.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.area.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.area.TabIndex = 1;
            this.area.TabStop = false;
            this.area.AutoSize = false;
            this.area.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.area.AutoScroll = false;
            this.area.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.area.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.area.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.area.Name = "area";
            // dashboard
            this.dashboard.Text = "";
            this.dashboard.AccessibleName = null;
            this.dashboard.Location = new System.Drawing.Point(0, 0);
            this.dashboard.Size = new System.Drawing.Size(1016, 537);
            this.dashboard.MinimumSize = new System.Drawing.Size(0, 0);
            this.dashboard.MaximumSize = new System.Drawing.Size(0, 0);
            this.dashboard.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.dashboard.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.dashboard.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.dashboard.Dock = (System.Windows.Forms.DockStyle)5;
            this.dashboard.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.dashboard.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.dashboard.Padding = new System.Windows.Forms.Padding(32, 20, 32, 20);
            this.dashboard.TabIndex = 0;
            this.dashboard.TabStop = false;
            this.dashboard.AutoSize = false;
            this.dashboard.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.dashboard.AutoScroll = false;
            this.dashboard.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.dashboard.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.dashboard.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.dashboard.RowCount = 3;
            this.dashboard.ColumnCount = 1;
            this.dashboard.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.dashboard.Name = "dashboard";
            this.dashboard.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 100F));
            this.dashboard.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)2, 68F));
            this.dashboard.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)1, 100F));
            this.dashboard.RowStyles.Add(new System.Windows.Forms.RowStyle((System.Windows.Forms.SizeType)2, 32F));
            // tablelayoutpanel5
            this.tablelayoutpanel5.Text = "";
            this.tablelayoutpanel5.AccessibleName = null;
            this.tablelayoutpanel5.Location = new System.Drawing.Point(35, 23);
            this.tablelayoutpanel5.Size = new System.Drawing.Size(946, 263);
            this.tablelayoutpanel5.MinimumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel5.MaximumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel5.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.tablelayoutpanel5.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.tablelayoutpanel5.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tablelayoutpanel5.Dock = (System.Windows.Forms.DockStyle)5;
            this.tablelayoutpanel5.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tablelayoutpanel5.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tablelayoutpanel5.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.tablelayoutpanel5.TabIndex = 0;
            this.tablelayoutpanel5.TabStop = false;
            this.tablelayoutpanel5.AutoSize = false;
            this.tablelayoutpanel5.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tablelayoutpanel5.AutoScroll = false;
            this.tablelayoutpanel5.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel5.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tablelayoutpanel5.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tablelayoutpanel5.RowCount = 0;
            this.tablelayoutpanel5.ColumnCount = 2;
            this.tablelayoutpanel5.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.tablelayoutpanel5.Name = "tablelayoutpanel5";
            this.tablelayoutpanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 55F));
            this.tablelayoutpanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 45F));
            // panel6
            this.panel6.Text = "";
            this.panel6.AccessibleName = null;
            this.panel6.Location = new System.Drawing.Point(3, 3);
            this.panel6.Size = new System.Drawing.Size(514, 257);
            this.panel6.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel6.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel6.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.panel6.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.panel6.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel6.Dock = (System.Windows.Forms.DockStyle)5;
            this.panel6.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel6.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.panel6.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel6.TabIndex = 0;
            this.panel6.TabStop = false;
            this.panel6.AutoSize = false;
            this.panel6.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel6.AutoScroll = false;
            this.panel6.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel6.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel6.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel6.Name = "panel6";
            // lblTitulo
            this.lblTitulo.Text = "Bem\nvindo!";
            this.lblTitulo.AccessibleName = null;
            this.lblTitulo.Location = new System.Drawing.Point(0, 0);
            this.lblTitulo.Size = new System.Drawing.Size(814, 156);
            this.lblTitulo.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblTitulo.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 42F, (System.Drawing.FontStyle)1);
            this.lblTitulo.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblTitulo.ForeColor = System.Drawing.Color.FromArgb(255, 133, 150, 140);
            this.lblTitulo.Dock = (System.Windows.Forms.DockStyle)0;
            this.lblTitulo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.lblTitulo.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblTitulo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.TabStop = false;
            this.lblTitulo.AutoSize = false;
            this.lblTitulo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblTitulo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblTitulo.TextAlign = (System.Drawing.ContentAlignment)16;
            this.lblTitulo.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblTitulo.UseCompatibleTextRendering = false;
            this.lblTitulo.Name = "lblTitulo";
            // btnNova
            this.btnNova.Text = "Nova ordem de serviço";
            this.btnNova.AccessibleName = null;
            this.btnNova.Location = new System.Drawing.Point(6, 170);
            this.btnNova.Size = new System.Drawing.Size(230, 38);
            this.btnNova.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnNova.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnNova.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnNova.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.btnNova.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.btnNova.Dock = (System.Windows.Forms.DockStyle)0;
            this.btnNova.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnNova.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.btnNova.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnNova.TabIndex = 11;
            this.btnNova.TabStop = true;
            this.btnNova.AutoSize = false;
            this.btnNova.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnNova.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnNova.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnNova.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnNova.UseVisualStyleBackColor = false;
            this.btnNova.UseCompatibleTextRendering = false;
            this.btnNova.FlatAppearance.BorderSize = 0;
            this.btnNova.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnNova.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnNova.Name = "btnNova";
            this.btnNova.Cursor = System.Windows.Forms.Cursors.Hand;
            // picturebox7
            this.picturebox7.Text = "";
            this.picturebox7.AccessibleName = null;
            this.picturebox7.Location = new System.Drawing.Point(540, 0);
            this.picturebox7.Size = new System.Drawing.Size(386, 245);
            this.picturebox7.MinimumSize = new System.Drawing.Size(0, 0);
            this.picturebox7.MaximumSize = new System.Drawing.Size(0, 0);
            this.picturebox7.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.picturebox7.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.picturebox7.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.picturebox7.Dock = (System.Windows.Forms.DockStyle)5;
            this.picturebox7.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.picturebox7.Margin = new System.Windows.Forms.Padding(20, 0, 20, 18);
            this.picturebox7.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.picturebox7.TabIndex = 1;
            this.picturebox7.TabStop = false;
            this.picturebox7.AutoSize = false;
            this.picturebox7.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.picturebox7.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.picturebox7.SizeMode = (System.Windows.Forms.PictureBoxSizeMode)4;
            this.picturebox7.Image = ((System.Drawing.Image)(resources.GetObject("picturebox7.Image")));
            this.picturebox7.Name = "picturebox7";
            // tablelayoutpanel8
            this.tablelayoutpanel8.Text = "";
            this.tablelayoutpanel8.AccessibleName = null;
            this.tablelayoutpanel8.Location = new System.Drawing.Point(35, 292);
            this.tablelayoutpanel8.Size = new System.Drawing.Size(946, 94);
            this.tablelayoutpanel8.MinimumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel8.MaximumSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel8.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.tablelayoutpanel8.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.tablelayoutpanel8.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.tablelayoutpanel8.Dock = (System.Windows.Forms.DockStyle)5;
            this.tablelayoutpanel8.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.tablelayoutpanel8.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tablelayoutpanel8.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.tablelayoutpanel8.TabIndex = 1;
            this.tablelayoutpanel8.TabStop = false;
            this.tablelayoutpanel8.AutoSize = false;
            this.tablelayoutpanel8.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.tablelayoutpanel8.AutoScroll = false;
            this.tablelayoutpanel8.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.tablelayoutpanel8.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.tablelayoutpanel8.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.tablelayoutpanel8.RowCount = 0;
            this.tablelayoutpanel8.ColumnCount = 4;
            this.tablelayoutpanel8.GrowStyle = (System.Windows.Forms.TableLayoutPanelGrowStyle)1;
            this.tablelayoutpanel8.Name = "tablelayoutpanel8";
            this.tablelayoutpanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 25F));
            this.tablelayoutpanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 25F));
            this.tablelayoutpanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 25F));
            this.tablelayoutpanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle((System.Windows.Forms.SizeType)2, 25F));
            // btnAbertas
            this.btnAbertas.Text = "Ordens abertas";
            this.btnAbertas.AccessibleName = null;
            this.btnAbertas.Location = new System.Drawing.Point(5, 10);
            this.btnAbertas.Size = new System.Drawing.Size(226, 70);
            this.btnAbertas.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnAbertas.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnAbertas.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnAbertas.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.btnAbertas.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.btnAbertas.Dock = (System.Windows.Forms.DockStyle)5;
            this.btnAbertas.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnAbertas.Margin = new System.Windows.Forms.Padding(5, 10, 5, 14);
            this.btnAbertas.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnAbertas.TabIndex = 6;
            this.btnAbertas.TabStop = true;
            this.btnAbertas.AutoSize = false;
            this.btnAbertas.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnAbertas.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnAbertas.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnAbertas.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnAbertas.UseVisualStyleBackColor = false;
            this.btnAbertas.UseCompatibleTextRendering = false;
            this.btnAbertas.FlatAppearance.BorderSize = 0;
            this.btnAbertas.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnAbertas.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnAbertas.Name = "btnAbertas";
            this.btnAbertas.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnManutencao
            this.btnManutencao.Text = "Em manutenção";
            this.btnManutencao.AccessibleName = null;
            this.btnManutencao.Location = new System.Drawing.Point(241, 10);
            this.btnManutencao.Size = new System.Drawing.Size(226, 70);
            this.btnManutencao.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnManutencao.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnManutencao.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnManutencao.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.btnManutencao.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.btnManutencao.Dock = (System.Windows.Forms.DockStyle)5;
            this.btnManutencao.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnManutencao.Margin = new System.Windows.Forms.Padding(5, 10, 5, 14);
            this.btnManutencao.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnManutencao.TabIndex = 7;
            this.btnManutencao.TabStop = true;
            this.btnManutencao.AutoSize = false;
            this.btnManutencao.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnManutencao.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnManutencao.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnManutencao.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnManutencao.UseVisualStyleBackColor = false;
            this.btnManutencao.UseCompatibleTextRendering = false;
            this.btnManutencao.FlatAppearance.BorderSize = 0;
            this.btnManutencao.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnManutencao.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnManutencao.Name = "btnManutencao";
            this.btnManutencao.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnConcluidas
            this.btnConcluidas.Text = "Serviços concluídos";
            this.btnConcluidas.AccessibleName = null;
            this.btnConcluidas.Location = new System.Drawing.Point(477, 10);
            this.btnConcluidas.Size = new System.Drawing.Size(226, 70);
            this.btnConcluidas.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnConcluidas.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnConcluidas.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnConcluidas.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.btnConcluidas.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.btnConcluidas.Dock = (System.Windows.Forms.DockStyle)5;
            this.btnConcluidas.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnConcluidas.Margin = new System.Windows.Forms.Padding(5, 10, 5, 14);
            this.btnConcluidas.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnConcluidas.TabIndex = 8;
            this.btnConcluidas.TabStop = true;
            this.btnConcluidas.AutoSize = false;
            this.btnConcluidas.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnConcluidas.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnConcluidas.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnConcluidas.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnConcluidas.UseVisualStyleBackColor = false;
            this.btnConcluidas.UseCompatibleTextRendering = false;
            this.btnConcluidas.FlatAppearance.BorderSize = 0;
            this.btnConcluidas.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnConcluidas.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnConcluidas.Name = "btnConcluidas";
            this.btnConcluidas.Cursor = System.Windows.Forms.Cursors.Hand;
            // btnProntas
            this.btnProntas.Text = "Aguardando entrega";
            this.btnProntas.AccessibleName = null;
            this.btnProntas.Location = new System.Drawing.Point(713, 10);
            this.btnProntas.Size = new System.Drawing.Size(228, 70);
            this.btnProntas.MinimumSize = new System.Drawing.Size(0, 0);
            this.btnProntas.MaximumSize = new System.Drawing.Size(0, 0);
            this.btnProntas.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.btnProntas.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.btnProntas.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.btnProntas.Dock = (System.Windows.Forms.DockStyle)5;
            this.btnProntas.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.btnProntas.Margin = new System.Windows.Forms.Padding(5, 10, 5, 14);
            this.btnProntas.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnProntas.TabIndex = 9;
            this.btnProntas.TabStop = true;
            this.btnProntas.AutoSize = false;
            this.btnProntas.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.btnProntas.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.btnProntas.TextAlign = (System.Drawing.ContentAlignment)32;
            this.btnProntas.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.btnProntas.UseVisualStyleBackColor = false;
            this.btnProntas.UseCompatibleTextRendering = false;
            this.btnProntas.FlatAppearance.BorderSize = 0;
            this.btnProntas.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.btnProntas.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.btnProntas.Name = "btnProntas";
            this.btnProntas.Cursor = System.Windows.Forms.Cursors.Hand;
            // lblResumo
            this.lblResumo.Text = "Selecione uma área acima para começar.";
            this.lblResumo.AccessibleName = null;
            this.lblResumo.Location = new System.Drawing.Point(35, 389);
            this.lblResumo.Size = new System.Drawing.Size(946, 128);
            this.lblResumo.MinimumSize = new System.Drawing.Size(0, 0);
            this.lblResumo.MaximumSize = new System.Drawing.Size(0, 0);
            this.lblResumo.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.lblResumo.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.lblResumo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.lblResumo.Dock = (System.Windows.Forms.DockStyle)5;
            this.lblResumo.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.lblResumo.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblResumo.Padding = new System.Windows.Forms.Padding(7, 12, 7, 0);
            this.lblResumo.TabIndex = 12;
            this.lblResumo.TabStop = false;
            this.lblResumo.AutoSize = false;
            this.lblResumo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.lblResumo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.lblResumo.TextAlign = (System.Drawing.ContentAlignment)1;
            this.lblResumo.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.lblResumo.UseCompatibleTextRendering = false;
            this.lblResumo.Name = "lblResumo";
            // label9
            this.label9.Text = "Tecnologia  ·  Assistência técnica";
            this.label9.AccessibleName = null;
            this.label9.Location = new System.Drawing.Point(3, 715);
            this.label9.Size = new System.Drawing.Size(1022, 34);
            this.label9.MinimumSize = new System.Drawing.Size(0, 0);
            this.label9.MaximumSize = new System.Drawing.Size(0, 0);
            this.label9.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label9.BackColor = System.Drawing.Color.FromArgb(255, 189, 207, 195);
            this.label9.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label9.Dock = (System.Windows.Forms.DockStyle)5;
            this.label9.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label9.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.label9.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label9.TabIndex = 3;
            this.label9.TabStop = false;
            this.label9.AutoSize = false;
            this.label9.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label9.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label9.TextAlign = (System.Drawing.ContentAlignment)32;
            this.label9.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label9.UseCompatibleTextRendering = false;
            this.label9.Name = "label9";
            this.Controls.Add(this.tablelayoutpanel1);
            this.tablelayoutpanel1.Controls.Add(this.tablelayoutpanel2, 0, 0);
            this.tablelayoutpanel2.Controls.Add(this.picturebox3, 0, 0);
            this.tablelayoutpanel2.Controls.Add(this.lblUsuario, 1, 0);
            this.tablelayoutpanel1.Controls.Add(this.flowlayoutpanel4, 0, 1);
            this.flowlayoutpanel4.Controls.Add(this.btnAtualizar);
            this.flowlayoutpanel4.Controls.Add(this.btnOrdens);
            this.flowlayoutpanel4.Controls.Add(this.btnPecas);
            this.flowlayoutpanel4.Controls.Add(this.btnCadastros);
            this.flowlayoutpanel4.Controls.Add(this.btnPerfil);
            this.flowlayoutpanel4.Controls.Add(this.btnSair);
            this.tablelayoutpanel1.Controls.Add(this.conteudo, 0, 2);
            this.conteudo.Controls.Add(this.menuCadastros, 0, 0);
            this.menuCadastros.Controls.Add(this.btnClientes);
            this.menuCadastros.Controls.Add(this.btnAparelhos);
            this.menuCadastros.Controls.Add(this.btnUsuarios);
            this.conteudo.Controls.Add(this.area, 0, 1);
            this.area.Controls.Add(this.dashboard);
            this.dashboard.Controls.Add(this.tablelayoutpanel5, 0, 0);
            this.tablelayoutpanel5.Controls.Add(this.panel6, 0, 0);
            this.panel6.Controls.Add(this.lblTitulo);
            this.panel6.Controls.Add(this.btnNova);
            this.tablelayoutpanel5.Controls.Add(this.picturebox7, 1, 0);
            this.dashboard.Controls.Add(this.tablelayoutpanel8, 0, 1);
            this.tablelayoutpanel8.Controls.Add(this.btnAbertas);
            this.tablelayoutpanel8.Controls.Add(this.btnManutencao);
            this.tablelayoutpanel8.Controls.Add(this.btnConcluidas);
            this.tablelayoutpanel8.Controls.Add(this.btnProntas);
            this.dashboard.Controls.Add(this.lblResumo, 0, 2);
            this.tablelayoutpanel1.Controls.Add(this.label9, 0, 3);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.btnClientes.Click += new System.EventHandler(this.btnClientes_Click);
            this.btnAparelhos.Click += new System.EventHandler(this.btnAparelhos_Click);
            this.btnUsuarios.Click += new System.EventHandler(this.btnUsuarios_Click);
            this.btnPecas.Click += new System.EventHandler(this.btnPecas_Click);
            this.btnAbertas.Click += new System.EventHandler(this.btnAbertas_Click);
            this.btnManutencao.Click += new System.EventHandler(this.btnManutencao_Click);
            this.btnConcluidas.Click += new System.EventHandler(this.btnConcluidas_Click);
            this.btnProntas.Click += new System.EventHandler(this.btnProntas_Click);
            this.btnOrdens.Click += new System.EventHandler(this.btnOrdens_Click);
            this.btnNova.Click += new System.EventHandler(this.btnNova_Click);
            this.btnAtualizar.Click += new System.EventHandler(this.btnAtualizar_Click);
            this.btnPerfil.Click += new System.EventHandler(this.btnPerfil_Click);
            this.btnSair.Click += new System.EventHandler(this.btnSair_Click);
            this.Load += new System.EventHandler(this.PrincipalForm_Load);
            this.btnAtualizar.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnOrdens.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnPecas.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnCadastros.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnPerfil.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnSair.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnClientes.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnAparelhos.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnUsuarios.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnNova.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnAbertas.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnManutencao.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnConcluidas.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnProntas.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.btnCadastros.Click += new System.EventHandler(this.Cadastros_Click);
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.PrincipalForm_FormClosing);
            this.tablelayoutpanel8.ResumeLayout(false);
            this.tablelayoutpanel8.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picturebox7)).EndInit();
            this.panel6.ResumeLayout(false);
            this.panel6.PerformLayout();
            this.tablelayoutpanel5.ResumeLayout(false);
            this.tablelayoutpanel5.PerformLayout();
            this.dashboard.ResumeLayout(false);
            this.dashboard.PerformLayout();
            this.area.ResumeLayout(false);
            this.area.PerformLayout();
            this.menuCadastros.ResumeLayout(false);
            this.menuCadastros.PerformLayout();
            this.conteudo.ResumeLayout(false);
            this.conteudo.PerformLayout();
            this.flowlayoutpanel4.ResumeLayout(false);
            this.flowlayoutpanel4.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picturebox3)).EndInit();
            this.tablelayoutpanel2.ResumeLayout(false);
            this.tablelayoutpanel2.PerformLayout();
            this.tablelayoutpanel1.ResumeLayout(false);
            this.tablelayoutpanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.TableLayoutPanel tablelayoutpanel1;
        private System.Windows.Forms.TableLayoutPanel tablelayoutpanel2;
        private System.Windows.Forms.PictureBox picturebox3;
        private System.Windows.Forms.Label lblUsuario;
        private System.Windows.Forms.FlowLayoutPanel flowlayoutpanel4;
        private System.Windows.Forms.Button btnAtualizar;
        private System.Windows.Forms.Button btnOrdens;
        private System.Windows.Forms.Button btnPecas;
        private System.Windows.Forms.Button btnCadastros;
        private System.Windows.Forms.Button btnPerfil;
        private System.Windows.Forms.Button btnSair;
        private System.Windows.Forms.TableLayoutPanel conteudo;
        private System.Windows.Forms.FlowLayoutPanel menuCadastros;
        private System.Windows.Forms.Button btnClientes;
        private System.Windows.Forms.Button btnAparelhos;
        private System.Windows.Forms.Button btnUsuarios;
        private System.Windows.Forms.Panel area;
        private System.Windows.Forms.TableLayoutPanel dashboard;
        private System.Windows.Forms.TableLayoutPanel tablelayoutpanel5;
        private System.Windows.Forms.Panel panel6;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Button btnNova;
        private System.Windows.Forms.PictureBox picturebox7;
        private System.Windows.Forms.TableLayoutPanel tablelayoutpanel8;
        private System.Windows.Forms.Button btnAbertas;
        private System.Windows.Forms.Button btnManutencao;
        private System.Windows.Forms.Button btnConcluidas;
        private System.Windows.Forms.Button btnProntas;
        private System.Windows.Forms.Label lblResumo;
        private System.Windows.Forms.Label label9;
    }
}
