namespace Tecnologia
{
    partial class PrincipalForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Location = new System.Drawing.Point(24, 36);
            this.lblTitulo.Size = new System.Drawing.Size(850, 24);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Tecnologia | Assistência técnica";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblTitulo);
            this.lblUsuario = new System.Windows.Forms.Label();
            this.lblUsuario.Name = "lblUsuario";
            this.lblUsuario.Location = new System.Drawing.Point(24, 76);
            this.lblUsuario.Size = new System.Drawing.Size(1040, 24);
            this.lblUsuario.TabIndex = 1;
            this.lblUsuario.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblUsuario);
            this.btnClientes = new System.Windows.Forms.Button();
            this.btnClientes.Name = "btnClientes";
            this.btnClientes.Location = new System.Drawing.Point(24, 125);
            this.btnClientes.Size = new System.Drawing.Size(195, 34);
            this.btnClientes.TabIndex = 2;
            this.btnClientes.Text = "Clientes";
            this.btnClientes.UseVisualStyleBackColor = true;
            this.btnClientes.Click += new System.EventHandler(this.btnClientes_Click);
            this.Controls.Add(this.btnClientes);
            this.btnAparelhos = new System.Windows.Forms.Button();
            this.btnAparelhos.Name = "btnAparelhos";
            this.btnAparelhos.Location = new System.Drawing.Point(237, 125);
            this.btnAparelhos.Size = new System.Drawing.Size(195, 34);
            this.btnAparelhos.TabIndex = 3;
            this.btnAparelhos.Text = "Aparelhos";
            this.btnAparelhos.UseVisualStyleBackColor = true;
            this.btnAparelhos.Click += new System.EventHandler(this.btnAparelhos_Click);
            this.Controls.Add(this.btnAparelhos);
            this.btnUsuarios = new System.Windows.Forms.Button();
            this.btnUsuarios.Name = "btnUsuarios";
            this.btnUsuarios.Location = new System.Drawing.Point(450, 125);
            this.btnUsuarios.Size = new System.Drawing.Size(195, 34);
            this.btnUsuarios.TabIndex = 4;
            this.btnUsuarios.Text = "Atendentes e técnicos";
            this.btnUsuarios.UseVisualStyleBackColor = true;
            this.btnUsuarios.Click += new System.EventHandler(this.btnUsuarios_Click);
            this.Controls.Add(this.btnUsuarios);
            this.btnPecas = new System.Windows.Forms.Button();
            this.btnPecas.Name = "btnPecas";
            this.btnPecas.Location = new System.Drawing.Point(663, 125);
            this.btnPecas.Size = new System.Drawing.Size(195, 34);
            this.btnPecas.TabIndex = 5;
            this.btnPecas.Text = "Peças e estoque";
            this.btnPecas.UseVisualStyleBackColor = true;
            this.btnPecas.Click += new System.EventHandler(this.btnPecas_Click);
            this.Controls.Add(this.btnPecas);
            this.btnAbertas = new System.Windows.Forms.Button();
            this.btnAbertas.Name = "btnAbertas";
            this.btnAbertas.Location = new System.Drawing.Point(24, 220);
            this.btnAbertas.Size = new System.Drawing.Size(250, 34);
            this.btnAbertas.TabIndex = 6;
            this.btnAbertas.Text = "Ordens abertas";
            this.btnAbertas.UseVisualStyleBackColor = true;
            this.btnAbertas.Click += new System.EventHandler(this.btnAbertas_Click);
            this.Controls.Add(this.btnAbertas);
            this.btnManutencao = new System.Windows.Forms.Button();
            this.btnManutencao.Name = "btnManutencao";
            this.btnManutencao.Location = new System.Drawing.Point(294, 220);
            this.btnManutencao.Size = new System.Drawing.Size(250, 34);
            this.btnManutencao.TabIndex = 7;
            this.btnManutencao.Text = "Em manutenção";
            this.btnManutencao.UseVisualStyleBackColor = true;
            this.btnManutencao.Click += new System.EventHandler(this.btnManutencao_Click);
            this.Controls.Add(this.btnManutencao);
            this.btnConcluidas = new System.Windows.Forms.Button();
            this.btnConcluidas.Name = "btnConcluidas";
            this.btnConcluidas.Location = new System.Drawing.Point(564, 220);
            this.btnConcluidas.Size = new System.Drawing.Size(250, 34);
            this.btnConcluidas.TabIndex = 8;
            this.btnConcluidas.Text = "Serviços concluídos";
            this.btnConcluidas.UseVisualStyleBackColor = true;
            this.btnConcluidas.Click += new System.EventHandler(this.btnConcluidas_Click);
            this.Controls.Add(this.btnConcluidas);
            this.btnProntas = new System.Windows.Forms.Button();
            this.btnProntas.Name = "btnProntas";
            this.btnProntas.Location = new System.Drawing.Point(834, 220);
            this.btnProntas.Size = new System.Drawing.Size(250, 34);
            this.btnProntas.TabIndex = 9;
            this.btnProntas.Text = "Aguardando entrega";
            this.btnProntas.UseVisualStyleBackColor = true;
            this.btnProntas.Click += new System.EventHandler(this.btnProntas_Click);
            this.Controls.Add(this.btnProntas);
            this.btnOrdens = new System.Windows.Forms.Button();
            this.btnOrdens.Name = "btnOrdens";
            this.btnOrdens.Location = new System.Drawing.Point(24, 320);
            this.btnOrdens.Size = new System.Drawing.Size(220, 34);
            this.btnOrdens.TabIndex = 10;
            this.btnOrdens.Text = "Todas as ordens";
            this.btnOrdens.UseVisualStyleBackColor = true;
            this.btnOrdens.Click += new System.EventHandler(this.btnOrdens_Click);
            this.Controls.Add(this.btnOrdens);
            this.btnNova = new System.Windows.Forms.Button();
            this.btnNova.Name = "btnNova";
            this.btnNova.Location = new System.Drawing.Point(264, 320);
            this.btnNova.Size = new System.Drawing.Size(240, 34);
            this.btnNova.TabIndex = 11;
            this.btnNova.Text = "Abrir ordem de serviço";
            this.btnNova.UseVisualStyleBackColor = true;
            this.btnNova.Click += new System.EventHandler(this.btnNova_Click);
            this.Controls.Add(this.btnNova);
            this.lblResumo = new System.Windows.Forms.Label();
            this.lblResumo.Name = "lblResumo";
            this.lblResumo.Location = new System.Drawing.Point(24, 397);
            this.lblResumo.Size = new System.Drawing.Size(1060, 24);
            this.lblResumo.TabIndex = 12;
            this.lblResumo.Text = "Selecione uma área acima para começar.";
            this.lblResumo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblResumo);
            this.btnAtualizar = new System.Windows.Forms.Button();
            this.btnAtualizar.Name = "btnAtualizar";
            this.btnAtualizar.Location = new System.Drawing.Point(24, 474);
            this.btnAtualizar.Size = new System.Drawing.Size(195, 34);
            this.btnAtualizar.TabIndex = 13;
            this.btnAtualizar.Text = "Atualizar painel";
            this.btnAtualizar.UseVisualStyleBackColor = true;
            this.btnAtualizar.Click += new System.EventHandler(this.btnAtualizar_Click);
            this.Controls.Add(this.btnAtualizar);
            this.btnPerfil = new System.Windows.Forms.Button();
            this.btnPerfil.Name = "btnPerfil";
            this.btnPerfil.Location = new System.Drawing.Point(237, 474);
            this.btnPerfil.Size = new System.Drawing.Size(195, 34);
            this.btnPerfil.TabIndex = 14;
            this.btnPerfil.Text = "Minha conta";
            this.btnPerfil.UseVisualStyleBackColor = true;
            this.btnPerfil.Click += new System.EventHandler(this.btnPerfil_Click);
            this.Controls.Add(this.btnPerfil);
            this.btnSair = new System.Windows.Forms.Button();
            this.btnSair.Name = "btnSair";
            this.btnSair.Location = new System.Drawing.Point(450, 474);
            this.btnSair.Size = new System.Drawing.Size(195, 34);
            this.btnSair.TabIndex = 15;
            this.btnSair.Text = "Sair da conta";
            this.btnSair.UseVisualStyleBackColor = true;
            this.btnSair.Click += new System.EventHandler(this.btnSair_Click);
            this.Controls.Add(this.btnSair);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(1120, 570);
            this.MinimumSize = new System.Drawing.Size(1120, 570);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Tecnologia — Painel principal";
            this.Name = "PrincipalForm";
            this.Load += new System.EventHandler(this.PrincipalForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblUsuario;
        private System.Windows.Forms.Button btnClientes;
        private System.Windows.Forms.Button btnAparelhos;
        private System.Windows.Forms.Button btnUsuarios;
        private System.Windows.Forms.Button btnPecas;
        private System.Windows.Forms.Button btnAbertas;
        private System.Windows.Forms.Button btnManutencao;
        private System.Windows.Forms.Button btnConcluidas;
        private System.Windows.Forms.Button btnProntas;
        private System.Windows.Forms.Button btnOrdens;
        private System.Windows.Forms.Button btnNova;
        private System.Windows.Forms.Label lblResumo;
        private System.Windows.Forms.Button btnAtualizar;
        private System.Windows.Forms.Button btnPerfil;
        private System.Windows.Forms.Button btnSair;
    }
}
