namespace Tecnologia
{
    partial class RecuperarSenhaForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null) components.Dispose();
                if (BackgroundImage != null) BackgroundImage.Dispose();
                if (picturebox1 != null && picturebox1.Image != null) picturebox1.Image.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RecuperarSenhaForm));
            this.picturebox1 = new System.Windows.Forms.PictureBox();
            this.cartaoAcesso = new System.Windows.Forms.FlowLayoutPanel();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.Fundo = new System.Windows.Forms.Panel();
            this.email = new System.Windows.Forms.TextBox();
            this.enviar = new System.Windows.Forms.Button();
            this.linklabel5 = new System.Windows.Forms.LinkLabel();
            this.linklabel6 = new System.Windows.Forms.LinkLabel();
            this.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picturebox1)).BeginInit();
            this.cartaoAcesso.SuspendLayout();
            this.Fundo.SuspendLayout();
            // RecuperarSenhaForm
            this.Text = "Tecnologia — Esqueci a senha";
            this.AccessibleName = null;
            this.MinimumSize = new System.Drawing.Size(480, 360);
            this.MaximumSize = new System.Drawing.Size(0, 0);
            this.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Dock = (System.Windows.Forms.DockStyle)0;
            this.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.TabIndex = 0;
            this.TabStop = true;
            this.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.AutoScroll = true;
            this.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)3;
            this.ClientSize = new System.Drawing.Size(1040, 780);
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.Name = "RecuperarSenhaForm";
            // picturebox1
            this.picturebox1.Text = "";
            this.picturebox1.AccessibleName = "Tecnologia";
            this.picturebox1.Location = new System.Drawing.Point(294, 24);
            this.picturebox1.Size = new System.Drawing.Size(440, 94);
            this.picturebox1.MinimumSize = new System.Drawing.Size(0, 0);
            this.picturebox1.MaximumSize = new System.Drawing.Size(0, 0);
            this.picturebox1.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.picturebox1.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.picturebox1.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.picturebox1.Dock = (System.Windows.Forms.DockStyle)0;
            this.picturebox1.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.picturebox1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.picturebox1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.picturebox1.TabIndex = 0;
            this.picturebox1.TabStop = false;
            this.picturebox1.AutoSize = false;
            this.picturebox1.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.picturebox1.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.picturebox1.SizeMode = (System.Windows.Forms.PictureBoxSizeMode)4;
            this.picturebox1.Image = ((System.Drawing.Image)(resources.GetObject("picturebox1.Image")));
            this.picturebox1.Name = "picturebox1";
            // cartaoAcesso
            this.cartaoAcesso.Text = "";
            this.cartaoAcesso.AccessibleName = null;
            this.cartaoAcesso.Location = new System.Drawing.Point(322, 146);
            this.cartaoAcesso.Size = new System.Drawing.Size(384, 335);
            this.cartaoAcesso.MinimumSize = new System.Drawing.Size(384, 0);
            this.cartaoAcesso.MaximumSize = new System.Drawing.Size(384, 0);
            this.cartaoAcesso.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.cartaoAcesso.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.cartaoAcesso.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.cartaoAcesso.Dock = (System.Windows.Forms.DockStyle)0;
            this.cartaoAcesso.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.cartaoAcesso.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.cartaoAcesso.Padding = new System.Windows.Forms.Padding(28, 24, 28, 24);
            this.cartaoAcesso.TabIndex = 1;
            this.cartaoAcesso.TabStop = false;
            this.cartaoAcesso.AutoSize = true;
            this.cartaoAcesso.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.cartaoAcesso.AutoScroll = false;
            this.cartaoAcesso.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.cartaoAcesso.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.cartaoAcesso.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.cartaoAcesso.FlowDirection = (System.Windows.Forms.FlowDirection)1;
            this.cartaoAcesso.WrapContents = false;
            this.cartaoAcesso.Name = "cartaoAcesso";
            // label2
            this.label2.Text = "Esqueceu a senha?";
            this.label2.AccessibleName = null;
            this.label2.Location = new System.Drawing.Point(28, 24);
            this.label2.Size = new System.Drawing.Size(322, 32);
            this.label2.MinimumSize = new System.Drawing.Size(322, 0);
            this.label2.MaximumSize = new System.Drawing.Size(322, 0);
            this.label2.Font = new System.Drawing.Font("Segoe UI", 18F, (System.Drawing.FontStyle)1);
            this.label2.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label2.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.label2.Dock = (System.Windows.Forms.DockStyle)0;
            this.label2.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label2.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.label2.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label2.TabIndex = 0;
            this.label2.TabStop = false;
            this.label2.AutoSize = true;
            this.label2.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label2.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label2.TextAlign = (System.Drawing.ContentAlignment)32;
            this.label2.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label2.UseCompatibleTextRendering = false;
            this.label2.Name = "label2";
            // label3
            this.label3.Text = "Informe o e-mail da sua conta. Enviaremos um código de verificação para redefinir a senha.";
            this.label3.AccessibleName = null;
            this.label3.Location = new System.Drawing.Point(28, 70);
            this.label3.Size = new System.Drawing.Size(322, 30);
            this.label3.MinimumSize = new System.Drawing.Size(322, 0);
            this.label3.MaximumSize = new System.Drawing.Size(322, 0);
            this.label3.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label3.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label3.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label3.Dock = (System.Windows.Forms.DockStyle)0;
            this.label3.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label3.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.label3.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label3.TabIndex = 1;
            this.label3.TabStop = false;
            this.label3.AutoSize = true;
            this.label3.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label3.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label3.TextAlign = (System.Drawing.ContentAlignment)32;
            this.label3.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label3.UseCompatibleTextRendering = false;
            this.label3.Name = "label3";
            // label4
            this.label4.Text = "E-mail";
            this.label4.AccessibleName = null;
            this.label4.Location = new System.Drawing.Point(28, 114);
            this.label4.Size = new System.Drawing.Size(322, 15);
            this.label4.MinimumSize = new System.Drawing.Size(322, 0);
            this.label4.MaximumSize = new System.Drawing.Size(322, 0);
            this.label4.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label4.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label4.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label4.Dock = (System.Windows.Forms.DockStyle)0;
            this.label4.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label4.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.label4.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label4.TabIndex = 2;
            this.label4.TabStop = false;
            this.label4.AutoSize = true;
            this.label4.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label4.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label4.TextAlign = (System.Drawing.ContentAlignment)16;
            this.label4.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label4.UseCompatibleTextRendering = false;
            this.label4.Name = "label4";
            // Fundo
            this.Fundo.Text = "";
            this.Fundo.AccessibleName = null;
            this.Fundo.Location = new System.Drawing.Point(28, 134);
            this.Fundo.Size = new System.Drawing.Size(322, 42);
            this.Fundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.Fundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.Fundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.Fundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.Fundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Fundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.Fundo.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Fundo.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.Fundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.Fundo.TabIndex = 3;
            this.Fundo.TabStop = false;
            this.Fundo.AutoSize = false;
            this.Fundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.Fundo.AutoScroll = false;
            this.Fundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.Fundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.Fundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.Fundo.Name = "Fundo";
            // email
            this.email.Text = "";
            this.email.AccessibleName = "E-mail";
            this.email.Location = new System.Drawing.Point(12, 12);
            this.email.Size = new System.Drawing.Size(298, 18);
            this.email.MinimumSize = new System.Drawing.Size(0, 0);
            this.email.MaximumSize = new System.Drawing.Size(0, 0);
            this.email.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.email.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.email.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.email.Dock = (System.Windows.Forms.DockStyle)0;
            this.email.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.email.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.email.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.email.TabIndex = 0;
            this.email.TabStop = true;
            this.email.AutoSize = true;
            this.email.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.email.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.email.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.email.ReadOnly = false;
            this.email.Multiline = false;
            this.email.MaxLength = 100;
            this.email.UseSystemPasswordChar = false;
            this.email.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.email.WordWrap = true;
            this.email.AcceptsReturn = false;
            this.email.AcceptsTab = false;
            this.email.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.email.Name = "email";
            // enviar
            this.enviar.Text = "ENVIAR CÓDIGO";
            this.enviar.AccessibleName = null;
            this.enviar.Location = new System.Drawing.Point(79, 195);
            this.enviar.Size = new System.Drawing.Size(220, 40);
            this.enviar.MinimumSize = new System.Drawing.Size(0, 0);
            this.enviar.MaximumSize = new System.Drawing.Size(0, 0);
            this.enviar.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.enviar.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.enviar.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.enviar.Dock = (System.Windows.Forms.DockStyle)0;
            this.enviar.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.enviar.Margin = new System.Windows.Forms.Padding(51, 5, 0, 12);
            this.enviar.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.enviar.TabIndex = 4;
            this.enviar.TabStop = true;
            this.enviar.AutoSize = false;
            this.enviar.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.enviar.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.enviar.TextAlign = (System.Drawing.ContentAlignment)32;
            this.enviar.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.enviar.UseVisualStyleBackColor = false;
            this.enviar.UseCompatibleTextRendering = false;
            this.enviar.FlatAppearance.BorderSize = 0;
            this.enviar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.enviar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.enviar.Name = "enviar";
            this.enviar.Cursor = System.Windows.Forms.Cursors.Hand;
            // linklabel5
            this.linklabel5.Text = "Já tenho um código";
            this.linklabel5.AccessibleName = null;
            this.linklabel5.Location = new System.Drawing.Point(28, 250);
            this.linklabel5.Size = new System.Drawing.Size(322, 26);
            this.linklabel5.MinimumSize = new System.Drawing.Size(0, 0);
            this.linklabel5.MaximumSize = new System.Drawing.Size(0, 0);
            this.linklabel5.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.linklabel5.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.linklabel5.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.linklabel5.Dock = (System.Windows.Forms.DockStyle)0;
            this.linklabel5.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.linklabel5.Margin = new System.Windows.Forms.Padding(0, 3, 0, 3);
            this.linklabel5.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.linklabel5.TabIndex = 5;
            this.linklabel5.TabStop = true;
            this.linklabel5.AutoSize = false;
            this.linklabel5.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.linklabel5.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.linklabel5.TextAlign = (System.Drawing.ContentAlignment)32;
            this.linklabel5.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.linklabel5.UseCompatibleTextRendering = false;
            this.linklabel5.LinkColor = System.Drawing.Color.FromArgb(255, 0, 112, 153);
            this.linklabel5.ActiveLinkColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.linklabel5.VisitedLinkColor = System.Drawing.Color.FromArgb(255, 0, 112, 153);
            this.linklabel5.Name = "linklabel5";
            this.linklabel5.Cursor = System.Windows.Forms.Cursors.Hand;
            // linklabel6
            this.linklabel6.Text = "Voltar para entrar";
            this.linklabel6.AccessibleName = null;
            this.linklabel6.Location = new System.Drawing.Point(28, 282);
            this.linklabel6.Size = new System.Drawing.Size(322, 26);
            this.linklabel6.MinimumSize = new System.Drawing.Size(0, 0);
            this.linklabel6.MaximumSize = new System.Drawing.Size(0, 0);
            this.linklabel6.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.linklabel6.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.linklabel6.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.linklabel6.Dock = (System.Windows.Forms.DockStyle)0;
            this.linklabel6.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.linklabel6.Margin = new System.Windows.Forms.Padding(0, 3, 0, 3);
            this.linklabel6.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.linklabel6.TabIndex = 6;
            this.linklabel6.TabStop = true;
            this.linklabel6.AutoSize = false;
            this.linklabel6.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.linklabel6.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.linklabel6.TextAlign = (System.Drawing.ContentAlignment)32;
            this.linklabel6.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.linklabel6.UseCompatibleTextRendering = false;
            this.linklabel6.LinkColor = System.Drawing.Color.FromArgb(255, 0, 112, 153);
            this.linklabel6.ActiveLinkColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.linklabel6.VisitedLinkColor = System.Drawing.Color.FromArgb(255, 0, 112, 153);
            this.linklabel6.Name = "linklabel6";
            this.linklabel6.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Controls.Add(this.picturebox1);
            this.Controls.Add(this.cartaoAcesso);
            this.cartaoAcesso.Controls.Add(this.label2);
            this.cartaoAcesso.Controls.Add(this.label3);
            this.cartaoAcesso.Controls.Add(this.label4);
            this.cartaoAcesso.Controls.Add(this.Fundo);
            this.Fundo.Controls.Add(this.email);
            this.cartaoAcesso.Controls.Add(this.enviar);
            this.cartaoAcesso.Controls.Add(this.linklabel5);
            this.cartaoAcesso.Controls.Add(this.linklabel6);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.cartaoAcesso.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.Fundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.enviar.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.Resize += new System.EventHandler(this.CentralizarAcesso);
            this.cartaoAcesso.SizeChanged += new System.EventHandler(this.CentralizarAcesso);
            this.enviar.Click += new System.EventHandler(this.Enviar_Click);
            this.AcceptButton = this.enviar;
            this.linklabel5.Click += new System.EventHandler(this.linklabel5_Click);
            this.linklabel6.Click += new System.EventHandler(this.linklabel6_Click);
            this.Fundo.ResumeLayout(false);
            this.Fundo.PerformLayout();
            this.cartaoAcesso.ResumeLayout(false);
            this.cartaoAcesso.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picturebox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.PictureBox picturebox1;
        private System.Windows.Forms.FlowLayoutPanel cartaoAcesso;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Panel Fundo;
        private System.Windows.Forms.TextBox email;
        private System.Windows.Forms.Button enviar;
        private System.Windows.Forms.LinkLabel linklabel5;
        private System.Windows.Forms.LinkLabel linklabel6;
    }
}
