namespace Tecnologia
{
    partial class RedefinirSenhaForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null) components.Dispose();
                if (BackgroundImage != null) BackgroundImage.Dispose();
                if (picturebox1 != null && picturebox1.Image != null) picturebox1.Image.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RedefinirSenhaForm));
            this.picturebox1 = new System.Windows.Forms.PictureBox();
            this.cartaoAcesso = new System.Windows.Forms.FlowLayoutPanel();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.Fundo = new System.Windows.Forms.Panel();
            this.codigo = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.panel6 = new System.Windows.Forms.Panel();
            this.senha = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.panel8 = new System.Windows.Forms.Panel();
            this.confirmacao = new System.Windows.Forms.TextBox();
            this.redefinir = new System.Windows.Forms.Button();
            this.linklabel9 = new System.Windows.Forms.LinkLabel();
            this.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picturebox1)).BeginInit();
            this.cartaoAcesso.SuspendLayout();
            this.Fundo.SuspendLayout();
            this.panel6.SuspendLayout();
            this.panel8.SuspendLayout();
            // RedefinirSenhaForm
            this.Text = "Tecnologia — Redefinir senha";
            this.AccessibleName = null;
            this.MinimumSize = new System.Drawing.Size(480, 360);
            this.MaximumSize = new System.Drawing.Size(0, 0);
            this.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.BackColor = System.Drawing.Color.FromArgb(255, 255, 255, 255);
            this.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Dock = (System.Windows.Forms.DockStyle)0;
            this.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.TabIndex = 0;
            this.TabStop = true;
            this.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.AutoScroll = true;
            this.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)3;
            this.ClientSize = new System.Drawing.Size(1040, 780);
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.Name = "RedefinirSenhaForm";
            // picturebox1
            this.picturebox1.Text = "";
            this.picturebox1.AccessibleName = "Tecnologia";
            this.picturebox1.Location = new System.Drawing.Point(294, 24);
            this.picturebox1.Size = new System.Drawing.Size(440, 94);
            this.picturebox1.MinimumSize = new System.Drawing.Size(0, 0);
            this.picturebox1.MaximumSize = new System.Drawing.Size(0, 0);
            this.picturebox1.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.picturebox1.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.picturebox1.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.picturebox1.Dock = (System.Windows.Forms.DockStyle)0;
            this.picturebox1.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.picturebox1.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.picturebox1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.picturebox1.TabIndex = 0;
            this.picturebox1.TabStop = false;
            this.picturebox1.AutoSize = false;
            this.picturebox1.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.picturebox1.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.picturebox1.SizeMode = (System.Windows.Forms.PictureBoxSizeMode)4;
            this.picturebox1.Image = ((System.Drawing.Image)(resources.GetObject("picturebox1.Image")));
            this.picturebox1.Name = "picturebox1";
            // cartaoAcesso
            this.cartaoAcesso.Text = "";
            this.cartaoAcesso.AccessibleName = null;
            this.cartaoAcesso.Location = new System.Drawing.Point(322, 146);
            this.cartaoAcesso.Size = new System.Drawing.Size(384, 455);
            this.cartaoAcesso.MinimumSize = new System.Drawing.Size(384, 0);
            this.cartaoAcesso.MaximumSize = new System.Drawing.Size(384, 0);
            this.cartaoAcesso.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.cartaoAcesso.BackColor = System.Drawing.Color.FromArgb(255, 238, 238, 238);
            this.cartaoAcesso.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.cartaoAcesso.Dock = (System.Windows.Forms.DockStyle)0;
            this.cartaoAcesso.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.cartaoAcesso.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.cartaoAcesso.Padding = new System.Windows.Forms.Padding(28, 24, 28, 24);
            this.cartaoAcesso.TabIndex = 1;
            this.cartaoAcesso.TabStop = false;
            this.cartaoAcesso.AutoSize = true;
            this.cartaoAcesso.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)0;
            this.cartaoAcesso.AutoScroll = false;
            this.cartaoAcesso.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.cartaoAcesso.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.cartaoAcesso.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.cartaoAcesso.FlowDirection = (System.Windows.Forms.FlowDirection)1;
            this.cartaoAcesso.WrapContents = false;
            this.cartaoAcesso.Name = "cartaoAcesso";
            // label2
            this.label2.Text = "Redefinir senha";
            this.label2.AccessibleName = null;
            this.label2.Location = new System.Drawing.Point(28, 24);
            this.label2.Size = new System.Drawing.Size(322, 32);
            this.label2.MinimumSize = new System.Drawing.Size(322, 0);
            this.label2.MaximumSize = new System.Drawing.Size(322, 0);
            this.label2.Font = new System.Drawing.Font("Segoe UI", 18F, (System.Drawing.FontStyle)1);
            this.label2.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label2.ForeColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.label2.Dock = (System.Windows.Forms.DockStyle)0;
            this.label2.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label2.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.label2.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label2.TabIndex = 0;
            this.label2.TabStop = false;
            this.label2.AutoSize = true;
            this.label2.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label2.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label2.TextAlign = (System.Drawing.ContentAlignment)32;
            this.label2.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label2.UseCompatibleTextRendering = false;
            this.label2.Name = "label2";
            // label3
            this.label3.Text = "Digite o código recebido por e-mail e escolha sua nova senha. O código expira em 10 minutos.";
            this.label3.AccessibleName = null;
            this.label3.Location = new System.Drawing.Point(28, 70);
            this.label3.Size = new System.Drawing.Size(322, 30);
            this.label3.MinimumSize = new System.Drawing.Size(322, 0);
            this.label3.MaximumSize = new System.Drawing.Size(322, 0);
            this.label3.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label3.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label3.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label3.Dock = (System.Windows.Forms.DockStyle)0;
            this.label3.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label3.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.label3.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label3.TabIndex = 1;
            this.label3.TabStop = false;
            this.label3.AutoSize = true;
            this.label3.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label3.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label3.TextAlign = (System.Drawing.ContentAlignment)32;
            this.label3.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label3.UseCompatibleTextRendering = false;
            this.label3.Name = "label3";
            // label4
            this.label4.Text = "Código de verificação";
            this.label4.AccessibleName = null;
            this.label4.Location = new System.Drawing.Point(28, 114);
            this.label4.Size = new System.Drawing.Size(322, 15);
            this.label4.MinimumSize = new System.Drawing.Size(322, 0);
            this.label4.MaximumSize = new System.Drawing.Size(322, 0);
            this.label4.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label4.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label4.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label4.Dock = (System.Windows.Forms.DockStyle)0;
            this.label4.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label4.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.label4.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label4.TabIndex = 2;
            this.label4.TabStop = false;
            this.label4.AutoSize = true;
            this.label4.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label4.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label4.TextAlign = (System.Drawing.ContentAlignment)16;
            this.label4.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label4.UseCompatibleTextRendering = false;
            this.label4.Name = "label4";
            // Fundo
            this.Fundo.Text = "";
            this.Fundo.AccessibleName = null;
            this.Fundo.Location = new System.Drawing.Point(28, 134);
            this.Fundo.Size = new System.Drawing.Size(322, 42);
            this.Fundo.MinimumSize = new System.Drawing.Size(0, 0);
            this.Fundo.MaximumSize = new System.Drawing.Size(0, 0);
            this.Fundo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.Fundo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.Fundo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.Fundo.Dock = (System.Windows.Forms.DockStyle)0;
            this.Fundo.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.Fundo.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.Fundo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.Fundo.TabIndex = 3;
            this.Fundo.TabStop = false;
            this.Fundo.AutoSize = false;
            this.Fundo.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.Fundo.AutoScroll = false;
            this.Fundo.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.Fundo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.Fundo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.Fundo.Name = "Fundo";
            // codigo
            this.codigo.Text = "";
            this.codigo.AccessibleName = "Código de verificação";
            this.codigo.Location = new System.Drawing.Point(12, 12);
            this.codigo.Size = new System.Drawing.Size(298, 18);
            this.codigo.MinimumSize = new System.Drawing.Size(0, 0);
            this.codigo.MaximumSize = new System.Drawing.Size(0, 0);
            this.codigo.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.codigo.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.codigo.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.codigo.Dock = (System.Windows.Forms.DockStyle)0;
            this.codigo.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.codigo.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.codigo.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.codigo.TabIndex = 0;
            this.codigo.TabStop = true;
            this.codigo.AutoSize = true;
            this.codigo.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.codigo.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.codigo.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.codigo.ReadOnly = false;
            this.codigo.Multiline = false;
            this.codigo.MaxLength = 6;
            this.codigo.UseSystemPasswordChar = false;
            this.codigo.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.codigo.WordWrap = true;
            this.codigo.AcceptsReturn = false;
            this.codigo.AcceptsTab = false;
            this.codigo.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.codigo.Name = "codigo";
            // label5
            this.label5.Text = "Nova senha (8 a 128 caracteres)";
            this.label5.AccessibleName = null;
            this.label5.Location = new System.Drawing.Point(28, 190);
            this.label5.Size = new System.Drawing.Size(322, 15);
            this.label5.MinimumSize = new System.Drawing.Size(322, 0);
            this.label5.MaximumSize = new System.Drawing.Size(322, 0);
            this.label5.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label5.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label5.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label5.Dock = (System.Windows.Forms.DockStyle)0;
            this.label5.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label5.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.label5.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label5.TabIndex = 4;
            this.label5.TabStop = false;
            this.label5.AutoSize = true;
            this.label5.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label5.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label5.TextAlign = (System.Drawing.ContentAlignment)16;
            this.label5.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label5.UseCompatibleTextRendering = false;
            this.label5.Name = "label5";
            // panel6
            this.panel6.Text = "";
            this.panel6.AccessibleName = null;
            this.panel6.Location = new System.Drawing.Point(28, 210);
            this.panel6.Size = new System.Drawing.Size(322, 42);
            this.panel6.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel6.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel6.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel6.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.panel6.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel6.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel6.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel6.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.panel6.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel6.TabIndex = 5;
            this.panel6.TabStop = false;
            this.panel6.AutoSize = false;
            this.panel6.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel6.AutoScroll = false;
            this.panel6.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel6.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel6.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel6.Name = "panel6";
            // senha
            this.senha.Text = "";
            this.senha.AccessibleName = "Nova senha (8 a 128 caracteres)";
            this.senha.Location = new System.Drawing.Point(12, 12);
            this.senha.Size = new System.Drawing.Size(298, 18);
            this.senha.MinimumSize = new System.Drawing.Size(0, 0);
            this.senha.MaximumSize = new System.Drawing.Size(0, 0);
            this.senha.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.senha.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.senha.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.senha.Dock = (System.Windows.Forms.DockStyle)0;
            this.senha.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.senha.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.senha.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.senha.TabIndex = 0;
            this.senha.TabStop = true;
            this.senha.AutoSize = true;
            this.senha.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.senha.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.senha.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.senha.ReadOnly = false;
            this.senha.Multiline = false;
            this.senha.MaxLength = 128;
            this.senha.UseSystemPasswordChar = true;
            this.senha.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.senha.WordWrap = true;
            this.senha.AcceptsReturn = false;
            this.senha.AcceptsTab = false;
            this.senha.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.senha.Name = "senha";
            // label7
            this.label7.Text = "Confirme a nova senha";
            this.label7.AccessibleName = null;
            this.label7.Location = new System.Drawing.Point(28, 266);
            this.label7.Size = new System.Drawing.Size(322, 15);
            this.label7.MinimumSize = new System.Drawing.Size(322, 0);
            this.label7.MaximumSize = new System.Drawing.Size(322, 0);
            this.label7.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)0);
            this.label7.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.label7.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.label7.Dock = (System.Windows.Forms.DockStyle)0;
            this.label7.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.label7.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.label7.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.label7.TabIndex = 6;
            this.label7.TabStop = false;
            this.label7.AutoSize = true;
            this.label7.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.label7.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.label7.TextAlign = (System.Drawing.ContentAlignment)16;
            this.label7.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.label7.UseCompatibleTextRendering = false;
            this.label7.Name = "label7";
            // panel8
            this.panel8.Text = "";
            this.panel8.AccessibleName = null;
            this.panel8.Location = new System.Drawing.Point(28, 286);
            this.panel8.Size = new System.Drawing.Size(322, 42);
            this.panel8.MinimumSize = new System.Drawing.Size(0, 0);
            this.panel8.MaximumSize = new System.Drawing.Size(0, 0);
            this.panel8.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.panel8.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.panel8.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.panel8.Dock = (System.Windows.Forms.DockStyle)0;
            this.panel8.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.panel8.Margin = new System.Windows.Forms.Padding(0, 0, 0, 14);
            this.panel8.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.panel8.TabIndex = 7;
            this.panel8.TabStop = false;
            this.panel8.AutoSize = false;
            this.panel8.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.panel8.AutoScroll = false;
            this.panel8.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.panel8.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.panel8.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.panel8.Name = "panel8";
            // confirmacao
            this.confirmacao.Text = "";
            this.confirmacao.AccessibleName = "Confirme a nova senha";
            this.confirmacao.Location = new System.Drawing.Point(12, 12);
            this.confirmacao.Size = new System.Drawing.Size(298, 18);
            this.confirmacao.MinimumSize = new System.Drawing.Size(0, 0);
            this.confirmacao.MaximumSize = new System.Drawing.Size(0, 0);
            this.confirmacao.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.confirmacao.BackColor = System.Drawing.Color.FromArgb(255, 218, 218, 218);
            this.confirmacao.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.confirmacao.Dock = (System.Windows.Forms.DockStyle)0;
            this.confirmacao.Anchor = (System.Windows.Forms.AnchorStyles)13;
            this.confirmacao.Margin = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.confirmacao.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.confirmacao.TabIndex = 0;
            this.confirmacao.TabStop = true;
            this.confirmacao.AutoSize = true;
            this.confirmacao.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.confirmacao.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.confirmacao.TextAlign = (System.Windows.Forms.HorizontalAlignment)0;
            this.confirmacao.ReadOnly = false;
            this.confirmacao.Multiline = false;
            this.confirmacao.MaxLength = 128;
            this.confirmacao.UseSystemPasswordChar = true;
            this.confirmacao.ScrollBars = (System.Windows.Forms.ScrollBars)0;
            this.confirmacao.WordWrap = true;
            this.confirmacao.AcceptsReturn = false;
            this.confirmacao.AcceptsTab = false;
            this.confirmacao.CharacterCasing = (System.Windows.Forms.CharacterCasing)0;
            this.confirmacao.Name = "confirmacao";
            // redefinir
            this.redefinir.Text = "REDEFINIR SENHA";
            this.redefinir.AccessibleName = null;
            this.redefinir.Location = new System.Drawing.Point(79, 347);
            this.redefinir.Size = new System.Drawing.Size(220, 40);
            this.redefinir.MinimumSize = new System.Drawing.Size(0, 0);
            this.redefinir.MaximumSize = new System.Drawing.Size(0, 0);
            this.redefinir.Font = new System.Drawing.Font("Segoe UI", 9F, (System.Drawing.FontStyle)1);
            this.redefinir.BackColor = System.Drawing.Color.FromArgb(255, 0, 235, 112);
            this.redefinir.ForeColor = System.Drawing.Color.FromArgb(255, 0, 61, 36);
            this.redefinir.Dock = (System.Windows.Forms.DockStyle)0;
            this.redefinir.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.redefinir.Margin = new System.Windows.Forms.Padding(51, 5, 0, 12);
            this.redefinir.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.redefinir.TabIndex = 8;
            this.redefinir.TabStop = true;
            this.redefinir.AutoSize = false;
            this.redefinir.AutoSizeMode = (System.Windows.Forms.AutoSizeMode)1;
            this.redefinir.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.redefinir.TextAlign = (System.Drawing.ContentAlignment)32;
            this.redefinir.FlatStyle = (System.Windows.Forms.FlatStyle)0;
            this.redefinir.UseVisualStyleBackColor = false;
            this.redefinir.UseCompatibleTextRendering = false;
            this.redefinir.FlatAppearance.BorderSize = 0;
            this.redefinir.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(255, 0, 211, 100);
            this.redefinir.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(255, 0, 183, 88);
            this.redefinir.Name = "redefinir";
            this.redefinir.Cursor = System.Windows.Forms.Cursors.Hand;
            // linklabel9
            this.linklabel9.Text = "Voltar / solicitar outro código";
            this.linklabel9.AccessibleName = null;
            this.linklabel9.Location = new System.Drawing.Point(28, 402);
            this.linklabel9.Size = new System.Drawing.Size(322, 26);
            this.linklabel9.MinimumSize = new System.Drawing.Size(0, 0);
            this.linklabel9.MaximumSize = new System.Drawing.Size(0, 0);
            this.linklabel9.Font = new System.Drawing.Font("Segoe UI", 10F, (System.Drawing.FontStyle)0);
            this.linklabel9.BackColor = System.Drawing.Color.FromArgb(0, 255, 255, 255);
            this.linklabel9.ForeColor = System.Drawing.Color.FromArgb(255, 70, 82, 76);
            this.linklabel9.Dock = (System.Windows.Forms.DockStyle)0;
            this.linklabel9.Anchor = (System.Windows.Forms.AnchorStyles)5;
            this.linklabel9.Margin = new System.Windows.Forms.Padding(0, 3, 0, 3);
            this.linklabel9.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.linklabel9.TabIndex = 9;
            this.linklabel9.TabStop = true;
            this.linklabel9.AutoSize = false;
            this.linklabel9.BackgroundImageLayout = (System.Windows.Forms.ImageLayout)1;
            this.linklabel9.BorderStyle = (System.Windows.Forms.BorderStyle)0;
            this.linklabel9.TextAlign = (System.Drawing.ContentAlignment)32;
            this.linklabel9.FlatStyle = (System.Windows.Forms.FlatStyle)2;
            this.linklabel9.UseCompatibleTextRendering = false;
            this.linklabel9.LinkColor = System.Drawing.Color.FromArgb(255, 0, 112, 153);
            this.linklabel9.ActiveLinkColor = System.Drawing.Color.FromArgb(255, 0, 118, 69);
            this.linklabel9.VisitedLinkColor = System.Drawing.Color.FromArgb(255, 0, 112, 153);
            this.linklabel9.Name = "linklabel9";
            this.linklabel9.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Controls.Add(this.picturebox1);
            this.Controls.Add(this.cartaoAcesso);
            this.cartaoAcesso.Controls.Add(this.label2);
            this.cartaoAcesso.Controls.Add(this.label3);
            this.cartaoAcesso.Controls.Add(this.label4);
            this.cartaoAcesso.Controls.Add(this.Fundo);
            this.Fundo.Controls.Add(this.codigo);
            this.cartaoAcesso.Controls.Add(this.label5);
            this.cartaoAcesso.Controls.Add(this.panel6);
            this.panel6.Controls.Add(this.senha);
            this.cartaoAcesso.Controls.Add(this.label7);
            this.cartaoAcesso.Controls.Add(this.panel8);
            this.panel8.Controls.Add(this.confirmacao);
            this.cartaoAcesso.Controls.Add(this.redefinir);
            this.cartaoAcesso.Controls.Add(this.linklabel9);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.cartaoAcesso.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.Fundo.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.panel6.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.panel8.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.redefinir.SizeChanged += new System.EventHandler(this.ControlRedimensionado);
            this.Resize += new System.EventHandler(this.CentralizarAcesso);
            this.cartaoAcesso.SizeChanged += new System.EventHandler(this.CentralizarAcesso);
            this.redefinir.Click += new System.EventHandler(this.Redefinir_Click);
            this.AcceptButton = this.redefinir;
            this.linklabel9.Click += new System.EventHandler(this.linklabel9_Click);
            this.panel8.ResumeLayout(false);
            this.panel8.PerformLayout();
            this.panel6.ResumeLayout(false);
            this.panel6.PerformLayout();
            this.Fundo.ResumeLayout(false);
            this.Fundo.PerformLayout();
            this.cartaoAcesso.ResumeLayout(false);
            this.cartaoAcesso.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picturebox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.PictureBox picturebox1;
        private System.Windows.Forms.FlowLayoutPanel cartaoAcesso;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Panel Fundo;
        private System.Windows.Forms.TextBox codigo;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Panel panel6;
        private System.Windows.Forms.TextBox senha;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Panel panel8;
        private System.Windows.Forms.TextBox confirmacao;
        private System.Windows.Forms.Button redefinir;
        private System.Windows.Forms.LinkLabel linklabel9;
    }
}
