namespace Tecnologia
{
    partial class UsuariosForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.SuspendLayout();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Location = new System.Drawing.Point(22, 14);
            this.lblTitulo.Size = new System.Drawing.Size(900, 24);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Atendentes e técnicos";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblTitulo);
            this.cmbCampo = new System.Windows.Forms.ComboBox();
            this.cmbCampo.Name = "cmbCampo";
            this.cmbCampo.Location = new System.Drawing.Point(22, 55);
            this.cmbCampo.Size = new System.Drawing.Size(180, 26);
            this.cmbCampo.TabIndex = 1;
            this.cmbCampo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCampo.Items.AddRange(new object[] { "Nome", "Código", "E-mail", "Perfil", "CPF", "RG", "Telefone", "Cidade", "Nascimento (AAAA-MM-DD)" });
            this.Controls.Add(this.cmbCampo);
            this.txtBusca = new System.Windows.Forms.TextBox();
            this.txtBusca.Name = "txtBusca";
            this.txtBusca.Location = new System.Drawing.Point(216, 55);
            this.txtBusca.Size = new System.Drawing.Size(350, 26);
            this.txtBusca.TabIndex = 2;
            this.txtBusca.MaxLength = 100;
            this.txtBusca.MaxLength = 100;
            this.Controls.Add(this.txtBusca);
            this.btnPesquisar = new System.Windows.Forms.Button();
            this.btnPesquisar.Name = "btnPesquisar";
            this.btnPesquisar.Location = new System.Drawing.Point(580, 50);
            this.btnPesquisar.Size = new System.Drawing.Size(142, 34);
            this.btnPesquisar.TabIndex = 3;
            this.btnPesquisar.Text = "Pesquisar";
            this.btnPesquisar.UseVisualStyleBackColor = true;
            this.btnPesquisar.Click += new System.EventHandler(this.btnPesquisar_Click);
            this.Controls.Add(this.btnPesquisar);
            this.btnExportar = new System.Windows.Forms.Button();
            this.btnExportar.Name = "btnExportar";
            this.btnExportar.Location = new System.Drawing.Point(738, 50);
            this.btnExportar.Size = new System.Drawing.Size(142, 34);
            this.btnExportar.TabIndex = 4;
            this.btnExportar.Text = "Exportar Excel";
            this.btnExportar.UseVisualStyleBackColor = true;
            this.btnExportar.Click += new System.EventHandler(this.btnExportar_Click);
            this.Controls.Add(this.btnExportar);
            this.lblnome = new System.Windows.Forms.Label();
            this.lblnome.Name = "lblnome";
            this.lblnome.Location = new System.Drawing.Point(22, 102);
            this.lblnome.Size = new System.Drawing.Size(320, 24);
            this.lblnome.TabIndex = 5;
            this.lblnome.Text = "Nome";
            this.lblnome.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblnome);
            this.camponome = new System.Windows.Forms.TextBox();
            this.camponome.Name = "camponome";
            this.camponome.Location = new System.Drawing.Point(22, 126);
            this.camponome.Size = new System.Drawing.Size(338, 26);
            this.camponome.TabIndex = 6;
            this.camponome.MaxLength = 100;
            this.camponome.MaxLength = 100;
            this.Controls.Add(this.camponome);
            this.lblemail = new System.Windows.Forms.Label();
            this.lblemail.Name = "lblemail";
            this.lblemail.Location = new System.Drawing.Point(382, 102);
            this.lblemail.Size = new System.Drawing.Size(320, 24);
            this.lblemail.TabIndex = 7;
            this.lblemail.Text = "E-mail de acesso";
            this.lblemail.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblemail);
            this.campoemail = new System.Windows.Forms.TextBox();
            this.campoemail.Name = "campoemail";
            this.campoemail.Location = new System.Drawing.Point(382, 126);
            this.campoemail.Size = new System.Drawing.Size(338, 26);
            this.campoemail.TabIndex = 8;
            this.campoemail.MaxLength = 100;
            this.campoemail.MaxLength = 100;
            this.Controls.Add(this.campoemail);
            this.lbltelefone = new System.Windows.Forms.Label();
            this.lbltelefone.Name = "lbltelefone";
            this.lbltelefone.Location = new System.Drawing.Point(742, 102);
            this.lbltelefone.Size = new System.Drawing.Size(320, 24);
            this.lbltelefone.TabIndex = 9;
            this.lbltelefone.Text = "Telefone";
            this.lbltelefone.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lbltelefone);
            this.campotelefone = new System.Windows.Forms.TextBox();
            this.campotelefone.Name = "campotelefone";
            this.campotelefone.Location = new System.Drawing.Point(742, 126);
            this.campotelefone.Size = new System.Drawing.Size(338, 26);
            this.campotelefone.TabIndex = 10;
            this.campotelefone.MaxLength = 100;
            this.campotelefone.MaxLength = 20;
            this.Controls.Add(this.campotelefone);
            this.lblcpf = new System.Windows.Forms.Label();
            this.lblcpf.Name = "lblcpf";
            this.lblcpf.Location = new System.Drawing.Point(22, 158);
            this.lblcpf.Size = new System.Drawing.Size(320, 24);
            this.lblcpf.TabIndex = 11;
            this.lblcpf.Text = "CPF (opcional)";
            this.lblcpf.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblcpf);
            this.campocpf = new System.Windows.Forms.TextBox();
            this.campocpf.Name = "campocpf";
            this.campocpf.Location = new System.Drawing.Point(22, 182);
            this.campocpf.Size = new System.Drawing.Size(338, 26);
            this.campocpf.TabIndex = 12;
            this.campocpf.MaxLength = 100;
            this.campocpf.MaxLength = 14;
            this.Controls.Add(this.campocpf);
            this.lblrg = new System.Windows.Forms.Label();
            this.lblrg.Name = "lblrg";
            this.lblrg.Location = new System.Drawing.Point(382, 158);
            this.lblrg.Size = new System.Drawing.Size(320, 24);
            this.lblrg.TabIndex = 13;
            this.lblrg.Text = "RG (opcional)";
            this.lblrg.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblrg);
            this.camporg = new System.Windows.Forms.TextBox();
            this.camporg.Name = "camporg";
            this.camporg.Location = new System.Drawing.Point(382, 182);
            this.camporg.Size = new System.Drawing.Size(338, 26);
            this.camporg.TabIndex = 14;
            this.camporg.MaxLength = 100;
            this.camporg.MaxLength = 20;
            this.Controls.Add(this.camporg);
            this.lblcidade = new System.Windows.Forms.Label();
            this.lblcidade.Name = "lblcidade";
            this.lblcidade.Location = new System.Drawing.Point(742, 158);
            this.lblcidade.Size = new System.Drawing.Size(320, 24);
            this.lblcidade.TabIndex = 15;
            this.lblcidade.Text = "Cidade";
            this.lblcidade.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblcidade);
            this.campocidade = new System.Windows.Forms.TextBox();
            this.campocidade.Name = "campocidade";
            this.campocidade.Location = new System.Drawing.Point(742, 182);
            this.campocidade.Size = new System.Drawing.Size(338, 26);
            this.campocidade.TabIndex = 16;
            this.campocidade.MaxLength = 100;
            this.campocidade.MaxLength = 60;
            this.Controls.Add(this.campocidade);
            this.lbldata_nascimento = new System.Windows.Forms.Label();
            this.lbldata_nascimento.Name = "lbldata_nascimento";
            this.lbldata_nascimento.Location = new System.Drawing.Point(22, 214);
            this.lbldata_nascimento.Size = new System.Drawing.Size(320, 24);
            this.lbldata_nascimento.TabIndex = 17;
            this.lbldata_nascimento.Text = "Nascimento (opcional)";
            this.lbldata_nascimento.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lbldata_nascimento);
            this.campodata_nascimento = new System.Windows.Forms.DateTimePicker();
            this.campodata_nascimento.Name = "campodata_nascimento";
            this.campodata_nascimento.Location = new System.Drawing.Point(22, 238);
            this.campodata_nascimento.Size = new System.Drawing.Size(338, 26);
            this.campodata_nascimento.TabIndex = 18;
            this.campodata_nascimento.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.campodata_nascimento.ShowCheckBox = true;
            this.Controls.Add(this.campodata_nascimento);
            this.lblperfil = new System.Windows.Forms.Label();
            this.lblperfil.Name = "lblperfil";
            this.lblperfil.Location = new System.Drawing.Point(382, 214);
            this.lblperfil.Size = new System.Drawing.Size(320, 24);
            this.lblperfil.TabIndex = 19;
            this.lblperfil.Text = "Perfil";
            this.lblperfil.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblperfil);
            this.campoperfil = new System.Windows.Forms.ComboBox();
            this.campoperfil.Name = "campoperfil";
            this.campoperfil.Location = new System.Drawing.Point(382, 238);
            this.campoperfil.Size = new System.Drawing.Size(338, 26);
            this.campoperfil.TabIndex = 20;
            this.campoperfil.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.campoperfil.Items.AddRange(new object[] { "Atendente", "Técnico" });
            this.Controls.Add(this.campoperfil);
            this.lblativo = new System.Windows.Forms.Label();
            this.lblativo.Name = "lblativo";
            this.lblativo.Location = new System.Drawing.Point(742, 214);
            this.lblativo.Size = new System.Drawing.Size(320, 24);
            this.lblativo.TabIndex = 21;
            this.lblativo.Text = "Conta ativa";
            this.lblativo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblativo);
            this.campoativo = new System.Windows.Forms.CheckBox();
            this.campoativo.Name = "campoativo";
            this.campoativo.Location = new System.Drawing.Point(742, 238);
            this.campoativo.Size = new System.Drawing.Size(338, 26);
            this.campoativo.TabIndex = 22;
            this.campoativo.Text = "Sim";
            this.Controls.Add(this.campoativo);
            this.lblsenha = new System.Windows.Forms.Label();
            this.lblsenha.Name = "lblsenha";
            this.lblsenha.Location = new System.Drawing.Point(22, 270);
            this.lblsenha.Size = new System.Drawing.Size(320, 24);
            this.lblsenha.TabIndex = 23;
            this.lblsenha.Text = "Senha (vazia na edição = manter)";
            this.lblsenha.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblsenha);
            this.camposenha = new System.Windows.Forms.TextBox();
            this.camposenha.Name = "camposenha";
            this.camposenha.Location = new System.Drawing.Point(22, 294);
            this.camposenha.Size = new System.Drawing.Size(338, 26);
            this.camposenha.TabIndex = 24;
            this.camposenha.MaxLength = 100;
            this.camposenha.UseSystemPasswordChar = true;
            this.camposenha.MaxLength = 128;
            this.Controls.Add(this.camposenha);
            this.btnNovo = new System.Windows.Forms.Button();
            this.btnNovo.Name = "btnNovo";
            this.btnNovo.Location = new System.Drawing.Point(22, 340);
            this.btnNovo.Size = new System.Drawing.Size(142, 34);
            this.btnNovo.TabIndex = 25;
            this.btnNovo.Text = "Novo / limpar";
            this.btnNovo.UseVisualStyleBackColor = true;
            this.btnNovo.Click += new System.EventHandler(this.btnNovo_Click);
            this.Controls.Add(this.btnNovo);
            this.btnSalvar = new System.Windows.Forms.Button();
            this.btnSalvar.Name = "btnSalvar";
            this.btnSalvar.Location = new System.Drawing.Point(178, 340);
            this.btnSalvar.Size = new System.Drawing.Size(142, 34);
            this.btnSalvar.TabIndex = 26;
            this.btnSalvar.Text = "Salvar";
            this.btnSalvar.UseVisualStyleBackColor = true;
            this.btnSalvar.Click += new System.EventHandler(this.btnSalvar_Click);
            this.Controls.Add(this.btnSalvar);
            this.btnEditar = new System.Windows.Forms.Button();
            this.btnEditar.Name = "btnEditar";
            this.btnEditar.Location = new System.Drawing.Point(334, 340);
            this.btnEditar.Size = new System.Drawing.Size(170, 34);
            this.btnEditar.TabIndex = 27;
            this.btnEditar.Text = "Editar selecionado";
            this.btnEditar.UseVisualStyleBackColor = true;
            this.btnEditar.Click += new System.EventHandler(this.btnEditar_Click);
            this.Controls.Add(this.btnEditar);
            this.btnExcluir = new System.Windows.Forms.Button();
            this.btnExcluir.Name = "btnExcluir";
            this.btnExcluir.Location = new System.Drawing.Point(518, 340);
            this.btnExcluir.Size = new System.Drawing.Size(170, 34);
            this.btnExcluir.TabIndex = 28;
            this.btnExcluir.Text = "Excluir selecionado";
            this.btnExcluir.UseVisualStyleBackColor = true;
            this.btnExcluir.Click += new System.EventHandler(this.btnExcluir_Click);
            this.Controls.Add(this.btnExcluir);
            this.lblEdicao = new System.Windows.Forms.Label();
            this.lblEdicao.Name = "lblEdicao";
            this.lblEdicao.Location = new System.Drawing.Point(710, 345);
            this.lblEdicao.Size = new System.Drawing.Size(365, 24);
            this.lblEdicao.TabIndex = 29;
            this.lblEdicao.Text = "Novo cadastro";
            this.lblEdicao.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Controls.Add(this.lblEdicao);
            this.grade = new System.Windows.Forms.DataGridView();
            this.grade.Name = "grade";
            this.grade.Location = new System.Drawing.Point(22, 390);
            this.grade.Size = new System.Drawing.Size(1076, 260);
            this.grade.TabIndex = 30;
            this.grade.ReadOnly = true;
            this.grade.AllowUserToAddRows = false;
            this.grade.AllowUserToDeleteRows = false;
            this.grade.MultiSelect = false;
            this.grade.RowHeadersVisible = false;
            this.grade.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.grade.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
            this.grade.BackgroundColor = System.Drawing.Color.White;
            this.grade.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.Controls.Add(this.grade);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ClientSize = new System.Drawing.Size(1120, 680);
            this.MinimumSize = new System.Drawing.Size(1120, 680);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Atendentes e técnicos";
            this.Name = "UsuariosForm";
            this.Load += new System.EventHandler(this.UsuariosForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.ComboBox cmbCampo;
        private System.Windows.Forms.TextBox txtBusca;
        private System.Windows.Forms.Button btnPesquisar;
        private System.Windows.Forms.Button btnExportar;
        private System.Windows.Forms.Label lblnome;
        private System.Windows.Forms.TextBox camponome;
        private System.Windows.Forms.Label lblemail;
        private System.Windows.Forms.TextBox campoemail;
        private System.Windows.Forms.Label lbltelefone;
        private System.Windows.Forms.TextBox campotelefone;
        private System.Windows.Forms.Label lblcpf;
        private System.Windows.Forms.TextBox campocpf;
        private System.Windows.Forms.Label lblrg;
        private System.Windows.Forms.TextBox camporg;
        private System.Windows.Forms.Label lblcidade;
        private System.Windows.Forms.TextBox campocidade;
        private System.Windows.Forms.Label lbldata_nascimento;
        private System.Windows.Forms.DateTimePicker campodata_nascimento;
        private System.Windows.Forms.Label lblperfil;
        private System.Windows.Forms.ComboBox campoperfil;
        private System.Windows.Forms.Label lblativo;
        private System.Windows.Forms.CheckBox campoativo;
        private System.Windows.Forms.Label lblsenha;
        private System.Windows.Forms.TextBox camposenha;
        private System.Windows.Forms.Button btnNovo;
        private System.Windows.Forms.Button btnSalvar;
        private System.Windows.Forms.Button btnEditar;
        private System.Windows.Forms.Button btnExcluir;
        private System.Windows.Forms.Label lblEdicao;
        private System.Windows.Forms.DataGridView grade;
    }
}
